/* Chapter 2 — Context-Free Languages (Sipser 2.1–2.4).
   CFG formal definition, derivations & parse trees, designing CFGs, ambiguity,
   Chomsky normal form, pushdown automata, CFG/PDA equivalence, the CFL pumping
   lemma, closure properties, and deterministic CFLs / DPDAs. */
TOC.addQuestions([
  // ---- CFG formal definition ----
  {
    id: "ch2-cfg-4tuple", chapter: 2, topic: "CFG formal definition", type: "mc",
    prompt: "A context-free grammar is formally defined as a 4-tuple \\((V,\\Sigma,R,S)\\). What is \\(R\\)?",
    choices: [
      "a finite set of rules (substitutions), each a variable paired with a string of variables and terminals",
      "the set of terminals (the input alphabet)",
      "the set of variables (nonterminals)",
      "a finite set of accept states"
    ],
    answer: 0,
    explanation: "In \\((V,\\Sigma,R,S)\\), \\(V\\) is the variables, \\(\\Sigma\\) the terminals (disjoint from \\(V\\)), \\(R\\) the rules where each rule is a variable \\(\\to\\) string over \\(V\\cup\\Sigma\\), and \\(S\\in V\\) the start variable.",
    source: "Sipser Def 2.2"
  },
  {
    id: "ch2-cfg-language-def", chapter: 2, topic: "CFG formal definition", type: "mc",
    prompt: "The language of a grammar \\(G\\) with start variable \\(S\\) is defined as:",
    choices: [
      "\\(\\{w\\in\\Sigma^*\\mid S\\stackrel{*}{\\Rightarrow}w\\}\\)",
      "\\(\\{w\\in(V\\cup\\Sigma)^*\\mid S\\Rightarrow w\\}\\)",
      "the set of all strings over \\(V\\cup\\Sigma\\)",
      "\\(\\{w\\in\\Sigma^*\\mid w\\stackrel{*}{\\Rightarrow}S\\}\\)"
    ],
    answer: 0,
    explanation: "\\(L(G)=\\{w\\in\\Sigma^*\\mid S\\stackrel{*}{\\Rightarrow}w\\}\\): strings of terminals derivable from the start variable. The yield must consist of terminals only.",
    source: "Sipser Def 2.2"
  },
  {
    id: "ch2-cfl-definition-fib", chapter: 2, topic: "CFG formal definition", type: "fib",
    prompt: "Any language that can be generated by some context-free grammar is called a ____ language (give the standard term).",
    accept: ["context-free", "context free", "contextfree"],
    explanation: "A context-free language (CFL) is by definition any language generated by some CFG. The class of CFLs is exactly the languages recognized by pushdown automata.",
    source: "Sipser §2.1"
  },

  // ---- Derivations, leftmost derivations, parse trees, yield ----
  {
    id: "ch2-leftmost-derivation", chapter: 2, topic: "Derivations & parse trees", type: "mc",
    prompt: "A derivation of a string \\(w\\) is a **leftmost derivation** if:",
    choices: [
      "at every step the leftmost remaining variable is the one replaced",
      "the rules are applied in alphabetical order",
      "only the rule listed first in the grammar is ever used",
      "the resulting parse tree is as short as possible"
    ],
    answer: 0,
    explanation: "A leftmost derivation always expands the leftmost variable. Fixing this order lets ambiguity be defined via distinct leftmost derivations rather than incidental reordering of steps.",
    source: "Sipser §2.1 (Ambiguity)"
  },
  {
    id: "ch2-parse-tree-yield-fib", chapter: 2, topic: "Derivations & parse trees", type: "fib",
    prompt: "The string of terminal symbols read left-to-right off the leaves of a parse tree is called the tree's ____.",
    accept: ["yield", "the yield"],
    explanation: "The yield of a parse tree is the terminal string at its leaves; the parse tree pictorially represents a derivation of that string.",
    source: "Sipser §2.1"
  },
  {
    id: "ch2-derivation-multi", chapter: 2, topic: "Derivations & parse trees", type: "multi",
    prompt: "Which statements about derivations and parse trees in a CFG are true?",
    choices: [
      "If \\(A\\to w\\) is a rule then \\(uAv\\Rightarrow uwv\\) (one substitution step)",
      "A single parse tree can correspond to several derivations that differ only in the order variables are replaced",
      "The yield of a parse tree is a string of terminals",
      "Two derivations of the same string always mean the grammar is ambiguous"
    ],
    answers: [0, 1, 2],
    explanation: "\\(\\Rightarrow\\) is the one-step yield relation, and reordering replacements can give the same tree — so ambiguity is defined by distinct parse trees (equivalently distinct leftmost derivations), not merely two derivations.",
    source: "Sipser Def 2.2 / §2.1 (Ambiguity)"
  },

  // ---- Designing CFGs / CFG for a given language ----
  {
    id: "ch2-design-anbn", chapter: 2, topic: "Designing CFGs", type: "mc",
    prompt: "Which grammar generates exactly \\(\\{0^n1^n\\mid n\\ge 0\\}\\)?",
    choices: [
      "\\(S\\to 0S1\\mid\\varepsilon\\)",
      "\\(S\\to 0S1\\mid 01\\)",
      "\\(S\\to 0S\\mid S1\\mid\\varepsilon\\)",
      "\\(S\\to 0S1\\mid 0\\mid 1\\)"
    ],
    answer: 0,
    explanation: "\\(S\\to 0S1\\) wraps a matching \\(0\\dots 1\\) pair around the recursion, and \\(S\\to\\varepsilon\\) supplies the base case \\(n=0\\). Choice 2 omits \\(\\varepsilon\\) so it excludes the empty string; choice 3 allows unequal counts.",
    source: "Sipser §2.1 (Designing CFGs)"
  },
  {
    id: "ch2-design-union", chapter: 2, topic: "Designing CFGs", type: "mc",
    prompt: "To build a CFG for a union \\(A_1\\cup A_2\\) of CFLs with grammars having start variables \\(S_1,S_2\\), the standard trick is to add:",
    choices: [
      "a new start variable \\(S\\) with the rule \\(S\\to S_1\\mid S_2\\)",
      "the rule \\(S_1\\to S_2\\)",
      "a rule \\(S\\to S_1 S_2\\)",
      "an \\(\\varepsilon\\)-rule to each original start variable"
    ],
    answer: 0,
    explanation: "Combining the two grammars' rules and adding \\(S\\to S_1\\mid S_2\\) yields a grammar for the union. (Using \\(S\\to S_1 S_2\\) would instead give the concatenation.)",
    source: "Sipser §2.1 (Designing CFGs)"
  },
  {
    id: "ch2-design-dfa-to-cfg-multi", chapter: 2, topic: "Designing CFGs", type: "multi",
    prompt: "To convert a DFA into an equivalent CFG (one variable \\(R_i\\) per state \\(q_i\\)), which rules are added?",
    choices: [
      "\\(R_i\\to aR_j\\) whenever \\(\\delta(q_i,a)=q_j\\)",
      "\\(R_i\\to\\varepsilon\\) whenever \\(q_i\\) is an accept state",
      "the start variable is \\(R_0\\), for the DFA's start state \\(q_0\\)",
      "\\(R_i\\to R_j a\\) whenever \\(\\delta(q_i,a)=q_j\\)"
    ],
    answers: [0, 1, 2],
    explanation: "Right-linear rules \\(R_i\\to aR_j\\) track transitions, \\(R_i\\to\\varepsilon\\) marks accept states, and \\(R_0\\) (start state) is the start variable. The result is a (right-linear) CFG generating the DFA's language.",
    source: "Sipser §2.1 (Designing CFGs)"
  },

  // ---- Every regular language is context-free ----
  {
    id: "ch2-regular-cfl-proper", chapter: 2, topic: "Regular vs context-free", type: "mc",
    prompt: "Which best describes the relationship between the regular languages and the context-free languages?",
    choices: [
      "the regular languages are a proper subset of the context-free languages",
      "they are exactly the same class",
      "the context-free languages are a proper subset of the regular languages",
      "the two classes are disjoint"
    ],
    answer: 0,
    explanation: "Regular \\(\\subsetneq\\) context-free: every regular language is a CFL (Cor 2.32, since every finite automaton is a PDA that ignores its stack), and \\(\\{0^n1^n\\}\\) is a CFL that is not regular, so the inclusion is strict.",
    source: "Sipser Cor 2.32 / Fig 2.33"
  },
  {
    id: "ch2-regular-cfl-why-multi", chapter: 2, topic: "Regular vs context-free", type: "multi",
    prompt: "Which facts together establish that every regular language is context-free, but not conversely?",
    choices: [
      "Every finite automaton is a PDA that simply ignores its stack",
      "Every DFA can be turned into an equivalent (right-linear) CFG",
      "\\(\\{0^n1^n\\mid n\\ge 0\\}\\) is context-free but not regular",
      "Every context-free language is regular"
    ],
    answers: [0, 1, 2],
    explanation: "A finite automaton is a stack-ignoring PDA and a DFA converts to a CFG, so regular \\(\\Rightarrow\\) context-free; \\(\\{0^n1^n\\}\\) witnesses that the inclusion is proper. The last claim is false.",
    source: "Sipser Cor 2.32"
  },

  // ---- Ambiguity ----
  {
    id: "ch2-ambiguous-def", chapter: 2, topic: "Ambiguity", type: "mc",
    prompt: "A grammar \\(G\\) is **ambiguous** exactly when:",
    choices: [
      "it generates some string with two or more different leftmost derivations (equivalently, two parse trees)",
      "it has two rules with the same left-hand side",
      "it contains an \\(\\varepsilon\\)-rule",
      "some variable never appears in any derivation"
    ],
    answer: 0,
    explanation: "Definition 2.7: a string is derived ambiguously if it has two or more distinct leftmost derivations, and \\(G\\) is ambiguous if it derives some string ambiguously. Multiple rules per variable alone is normal, not ambiguity.",
    source: "Sipser Def 2.7"
  },
  {
    id: "ch2-inherently-ambiguous", chapter: 2, topic: "Ambiguity", type: "mc",
    prompt: "A context-free language is called **inherently ambiguous** when:",
    choices: [
      "every grammar that generates it is ambiguous",
      "it has at least one ambiguous grammar",
      "no grammar generates it",
      "it is generated by an ambiguous grammar but also by some unambiguous one"
    ],
    answer: 0,
    explanation: "Inherently ambiguous means no unambiguous grammar exists for the language — every CFG generating it is ambiguous. Sipser notes \\(\\{a^ib^jc^k\\mid i=j\\text{ or }j=k\\}\\) is such a language.",
    source: "Sipser §2.1 (Ambiguity) / Prob 2.29"
  },
  {
    id: "ch2-ambiguous-not-inherent-tf", chapter: 2, topic: "Ambiguity", type: "tf",
    prompt: "If a grammar is ambiguous, then the language it generates is inherently ambiguous.",
    answer: false,
    explanation: "False. An ambiguous grammar may still have an equivalent unambiguous grammar (e.g. Sipser's expression grammars \\(G_5\\) vs \\(G_4\\) generate the same language). Inherent ambiguity means *no* unambiguous grammar exists.",
    source: "Sipser §2.1 (Ambiguity)"
  },

  // ---- Chomsky normal form ----
  {
    id: "ch2-cnf-rule-forms", chapter: 2, topic: "Chomsky normal form", type: "mc",
    prompt: "Which set of rule forms is permitted in Chomsky normal form?",
    choices: [
      "\\(A\\to BC\\) and \\(A\\to a\\), plus \\(S\\to\\varepsilon\\) for the start variable only",
      "\\(A\\to BC\\), \\(A\\to a\\), and \\(A\\to\\varepsilon\\) for any variable",
      "\\(A\\to aB\\) and \\(A\\to a\\) only",
      "any rule whose right-hand side has at most two symbols"
    ],
    answer: 0,
    explanation: "CNF allows \\(A\\to BC\\) (two variables, neither the start variable) and \\(A\\to a\\) (single terminal), plus the single exception \\(S\\to\\varepsilon\\). \\(A\\to aB\\) is right-linear form, not CNF.",
    source: "Sipser Def 2.8"
  },
  {
    id: "ch2-cnf-order", chapter: 2, topic: "Chomsky normal form", type: "order",
    prompt: "Order the stages of Sipser's procedure for converting a CFG to Chomsky normal form.",
    items: [
      "Add a new start variable \\(S_0\\) with \\(S_0\\to S\\)",
      "Eliminate all \\(\\varepsilon\\)-rules \\(A\\to\\varepsilon\\) (for \\(A\\) not the start variable)",
      "Eliminate all unit rules \\(A\\to B\\)",
      "Convert remaining long rules and isolate terminals into the forms \\(A\\to BC\\) and \\(A\\to a\\)"
    ],
    explanation: "Theorem 2.9 order: (1) new start variable, (2) remove \\(\\varepsilon\\)-rules, (3) remove unit rules, (4) shorten long right-hand sides and replace terminals in long rules with new variables.",
    source: "Sipser Thm 2.9"
  },
  {
    id: "ch2-cnf-unit-rule-fib", chapter: 2, topic: "Chomsky normal form", type: "fib",
    prompt: "A grammar rule of the form \\(A\\to B\\), where both sides are single variables, is called a ____ rule.",
    accept: ["unit", "a unit"],
    explanation: "A unit rule \\(A\\to B\\) has one variable deriving another. CNF conversion removes unit rules by, for each rule \\(B\\to u\\), adding \\(A\\to u\\).",
    source: "Sipser Thm 2.9"
  },

  // ---- Pushdown automata ----
  {
    id: "ch2-pda-6tuple", chapter: 2, topic: "Pushdown automata", type: "mc",
    prompt: "A pushdown automaton is a 6-tuple \\((Q,\\Sigma,\\Gamma,\\delta,q_0,F)\\). What is \\(\\Gamma\\)?",
    choices: [
      "the stack alphabet",
      "the input alphabet",
      "the set of accept states",
      "the transition function"
    ],
    answer: 0,
    explanation: "A PDA may use different alphabets for input and stack: \\(\\Sigma\\) is the input alphabet and \\(\\Gamma\\) the stack alphabet. \\(F\\subseteq Q\\) is the accept states and \\(\\delta\\) the transition function.",
    source: "Sipser Def 2.13"
  },
  {
    id: "ch2-pda-transition-type", chapter: 2, topic: "Pushdown automata", type: "mc",
    prompt: "For a (nondeterministic) PDA, the transition function has the form:",
    choices: [
      "\\(\\delta:Q\\times\\Sigma_\\varepsilon\\times\\Gamma_\\varepsilon\\to\\mathcal{P}(Q\\times\\Gamma_\\varepsilon)\\)",
      "\\(\\delta:Q\\times\\Sigma\\to Q\\)",
      "\\(\\delta:Q\\times\\Sigma_\\varepsilon\\to\\mathcal{P}(Q)\\)",
      "\\(\\delta:Q\\times\\Gamma\\to Q\\times\\Gamma\\)"
    ],
    answer: 0,
    explanation: "The current state, next input symbol (or \\(\\varepsilon\\)), and top stack symbol (or \\(\\varepsilon\\)) map to a *set* of (state, push-symbol) pairs — the power set \\(\\mathcal{P}\\) captures nondeterminism. \\(\\Sigma_\\varepsilon=\\Sigma\\cup\\{\\varepsilon\\}\\), \\(\\Gamma_\\varepsilon=\\Gamma\\cup\\{\\varepsilon\\}\\).",
    source: "Sipser Def 2.13"
  },
  {
    id: "ch2-pda-empty-stack-fib", chapter: 2, topic: "Pushdown automata", type: "fib",
    prompt: "Since a PDA has no built-in empty-stack test, it conventionally pushes a special bottom-of-stack marker; seeing it again means the stack is effectively empty. Type the one-character symbol Sipser uses for it.",
    accept: ["$", "\\$", "dollar", "dollar sign"],
    explanation: "Initially placing \\(\\$\\) on the stack and later detecting it simulates an empty-stack test, which the PDA model does not provide directly.",
    source: "Sipser Ex 2.14"
  },
  {
    id: "ch2-pda-nondet-stronger", chapter: 2, topic: "Pushdown automata", type: "tf",
    prompt: "Deterministic and nondeterministic pushdown automata recognize exactly the same class of languages.",
    answer: false,
    explanation: "False — and this is a key contrast with finite automata. Nondeterministic PDAs are strictly more powerful: e.g. \\(\\{ww^{\\mathcal{R}}\\}\\) is recognized by an NPDA but no DPDA. DFAs and NFAs, by contrast, are equivalent.",
    source: "Sipser §2.2 / §2.4"
  },
  {
    id: "ch2-pda-accept-multi", chapter: 2, topic: "Pushdown automata", type: "multi",
    prompt: "Which statements about pushdown automata are correct?",
    choices: [
      "A PDA may move on \\(\\varepsilon\\) input (without reading an input symbol)",
      "A PDA may move without popping a stack symbol (when the stack component is \\(\\varepsilon\\))",
      "A PDA can store an unbounded amount of information on its stack",
      "Every nonregular language recognized by a PDA requires the PDA to be deterministic"
    ],
    answers: [0, 1, 2],
    explanation: "\\(\\varepsilon\\) is allowed for both the input and stack components of \\(\\delta\\), and the stack is unbounded. The last choice is false: some PDA languages require *nondeterminism*, not determinism.",
    source: "Sipser Def 2.13 / §2.2"
  },

  // ---- Equivalence of CFGs and PDAs ----
  {
    id: "ch2-cfg-pda-equiv", chapter: 2, topic: "CFG/PDA equivalence", type: "tf",
    prompt: "A language is context-free if and only if some pushdown automaton recognizes it.",
    answer: true,
    explanation: "Theorem 2.20 establishes both directions: every CFG converts to an equivalent PDA (Lemma 2.21) and every PDA converts to an equivalent CFG (Lemma 2.27). CFGs and PDAs describe the same class.",
    source: "Sipser Thm 2.20"
  },
  {
    id: "ch2-cfg-to-pda-order", chapter: 2, topic: "CFG/PDA equivalence", type: "order",
    prompt: "Order the actions of the PDA \\(P\\) built from a CFG \\(G\\) (Lemma 2.21) as it tries to derive its input.",
    items: [
      "Push the marker \\(\\$\\) and the start variable \\(S\\) onto the stack",
      "If the top of stack is a variable \\(A\\), nondeterministically replace it with the right-hand side of some rule \\(A\\to w\\)",
      "If the top of stack is a terminal, pop it and match it against the next input symbol (reject this branch on mismatch)",
      "If the top of stack is \\(\\$\\), enter the accept state (accepting if all input has been read)"
    ],
    explanation: "The PDA simulates a leftmost derivation on its stack: initialize with \\(S\\$\\), expand variables nondeterministically, match terminals against the input, and accept when only \\(\\$\\) remains. Its nondeterminism guesses which rule to apply.",
    source: "Sipser Lem 2.21"
  },
  {
    id: "ch2-pda-to-cfg-variables", chapter: 2, topic: "CFG/PDA equivalence", type: "mc",
    prompt: "In converting a PDA \\(P\\) to a CFG (Lemma 2.27), the grammar has a variable \\(A_{pq}\\) for each pair of states \\(p,q\\). What does \\(A_{pq}\\) generate?",
    choices: [
      "all strings that take \\(P\\) from \\(p\\) with empty stack to \\(q\\) with empty stack",
      "all strings of length exactly the distance from \\(p\\) to \\(q\\)",
      "all strings that leave the stack nonempty at \\(q\\)",
      "all strings accepted by \\(P\\) starting in \\(q\\)"
    ],
    answer: 0,
    explanation: "\\(A_{pq}\\) is designed to derive exactly the input strings that drive \\(P\\) from \\(p\\) (empty stack) to \\(q\\) (empty stack); the start variable is \\(A_{q_0,q_{\\text{accept}}}\\).",
    source: "Sipser Lem 2.27"
  },

  // ---- Pumping lemma for CFLs ----
  {
    id: "ch2-pl-conditions", chapter: 2, topic: "Pumping lemma (CFL)", type: "multi",
    prompt: "By the pumping lemma for CFLs, a string \\(s\\in A\\) with \\(|s|\\ge p\\) can be written \\(s=uvxyz\\) so that:",
    choices: [
      "\\(uv^ixy^iz\\in A\\) for every \\(i\\ge 0\\)",
      "\\(|vy|>0\\)",
      "\\(|vxy|\\le p\\)",
      "\\(v\\) and \\(y\\) each lie entirely within the first \\(p\\) symbols of \\(s\\)"
    ],
    answers: [0, 1, 2],
    explanation: "The three conditions are: (1) \\(uv^ixy^iz\\in A\\) for all \\(i\\ge 0\\); (2) \\(|vy|>0\\) (\\(v,y\\) not both empty); (3) \\(|vxy|\\le p\\). There is no condition forcing \\(v,y\\) into the first \\(p\\) symbols.",
    source: "Sipser Thm 2.34"
  },
  {
    id: "ch2-pl-pigeonhole-fib", chapter: 2, topic: "Pumping lemma (CFL)", type: "fib",
    prompt: "The CFL pumping lemma's proof relies on a long enough string's parse tree being tall enough that some variable repeats on a root-to-leaf path. Which counting principle guarantees this repetition? (give its name)",
    accept: ["pigeonhole principle", "pigeonhole", "the pigeonhole principle"],
    explanation: "A tall enough parse tree has a path with more variable nodes than there are variables, so by the pigeonhole principle a variable \\(R\\) repeats; swapping the two \\(R\\)-subtrees is what allows pumping.",
    source: "Sipser Thm 2.34 (proof)"
  },
  {
    id: "ch2-pl-anbncn-string", chapter: 2, topic: "Pumping lemma (CFL)", type: "mc",
    prompt: "To prove \\(B=\\{a^nb^nc^n\\mid n\\ge 0\\}\\) is not context-free, which string \\(s\\) is the standard choice (with pumping length \\(p\\)), and what makes pumping fail?",
    choices: [
      "\\(s=a^pb^pc^p\\); since \\(|vxy|\\le p\\), the window \\(vxy\\) spans at most two symbol-blocks, so pumping unbalances the counts",
      "\\(s=a^p\\); pumping changes the number of \\(a\\)s",
      "\\(s=(abc)^p\\); pumping reorders the symbols",
      "\\(s=a^pb^p\\); pumping changes the number of \\(b\\)s"
    ],
    answer: 0,
    explanation: "With \\(s=a^pb^pc^p\\) and \\(|vxy|\\le p\\), the substring \\(vxy\\) cannot touch all three blocks at once, so \\(uv^2xy^2z\\) cannot keep the \\(a,b,c\\) counts equal — a contradiction.",
    source: "Sipser Ex 2.36"
  },
  {
    id: "ch2-pl-ww-string", chapter: 2, topic: "Pumping lemma (CFL)", type: "mc",
    prompt: "To show \\(D=\\{ww\\mid w\\in\\{0,1\\}^*\\}\\) is not context-free, which string works (the naive \\(0^p10^p1\\) does not)?",
    choices: [
      "\\(s=0^p1^p0^p1^p\\)",
      "\\(s=0^p1^p\\)",
      "\\(s=(01)^p\\)",
      "\\(s=0^{2p}\\)"
    ],
    answer: 0,
    explanation: "\\(s=0^p1^p0^p1^p\\) captures the essence of \\(ww\\). Using \\(|vxy|\\le p\\), \\(vxy\\) must straddle the midpoint; pumping down to \\(uxz\\) breaks the two-equal-halves structure, so \\(s\\) cannot be pumped.",
    source: "Sipser Ex 2.38"
  },
  {
    id: "ch2-pl-pump-down-tf", chapter: 2, topic: "Pumping lemma (CFL)", type: "tf",
    prompt: "For some languages, such as \\(C=\\{a^ib^jc^k\\mid 0\\le i\\le j\\le k\\}\\), proving non-context-freeness requires \"pumping down\" (taking \\(i=0\\), i.e. \\(uxz\\)), not just pumping up.",
    answer: true,
    explanation: "Because \\(C\\) tolerates unequal counts as long as they are nondecreasing, pumping up may stay in \\(C\\); pumping down to \\(uv^0xy^0z=uxz\\) is needed to force a violation (e.g. fewer \\(b\\)s or \\(c\\)s).",
    source: "Sipser Ex 2.37"
  },
  {
    id: "ch2-pl-direction-tf", chapter: 2, topic: "Pumping lemma (CFL)", type: "tf",
    prompt: "Exhibiting a string in a language \\(L\\) that can be pumped (stays in \\(L\\) for all \\(i\\)) proves that \\(L\\) is context-free.",
    answer: false,
    explanation: "False. The pumping lemma is a necessary condition, not sufficient: it can only be used (via contradiction) to show a language is *not* context-free. Pumpability of one string proves nothing positive.",
    source: "Sipser Thm 2.34"
  },
  {
    id: "ch2-pl-proof-order", chapter: 2, topic: "Pumping lemma (CFL)", type: "order",
    prompt: "Order the steps of a typical proof that a language \\(L\\) is not context-free using the pumping lemma.",
    items: [
      "Assume \\(L\\) is context-free, so the pumping lemma gives a pumping length \\(p\\)",
      "Choose a specific string \\(s\\in L\\) with \\(|s|\\ge p\\)",
      "Argue that for every valid split \\(s=uvxyz\\) (with \\(|vxy|\\le p,\\ |vy|>0\\)) some pumped \\(uv^ixy^iz\\notin L\\)",
      "Conclude the contradiction, so \\(L\\) is not context-free"
    ],
    explanation: "Like the regular pumping lemma but with the five-part split: assume CF and get \\(p\\); pick \\(s\\); show no split survives pumping (often using \\(|vxy|\\le p\\) and possibly pumping down); contradiction.",
    source: "Sipser Thm 2.34 / Ex 2.36–2.38"
  },

  // ---- Closure properties ----
  {
    id: "ch2-closure-union-concat-star-multi", chapter: 2, topic: "Closure properties", type: "multi",
    prompt: "Under which operations is the class of context-free languages closed?",
    choices: [
      "Union",
      "Concatenation",
      "Star (Kleene closure)",
      "Intersection"
    ],
    answers: [0, 1, 2],
    explanation: "CFLs are closed under union, concatenation, and star (easy grammar constructions). They are NOT closed under intersection — that is the classic exception.",
    source: "Sipser §2.1 / Prob 2.18"
  },
  {
    id: "ch2-closure-intersection-tf", chapter: 2, topic: "Closure properties", type: "tf",
    prompt: "The class of context-free languages is closed under intersection.",
    answer: false,
    explanation: "False. \\(\\{a^nb^nc^m\\mid m,n\\ge 0\\}\\) and \\(\\{a^mb^nc^n\\mid m,n\\ge 0\\}\\) are context-free, but their intersection is \\(\\{a^nb^nc^n\\}\\), which is not context-free. So CFLs are NOT closed under \\(\\cap\\).",
    source: "Sipser Prob 2.18 (and Ex 2.36)"
  },
  {
    id: "ch2-closure-intersect-regular", chapter: 2, topic: "Closure properties", type: "tf",
    prompt: "The intersection of a context-free language with a regular language is always context-free.",
    answer: true,
    explanation: "True. Running a PDA and a DFA in parallel (product construction on the finite control) yields a PDA, so CFL \\(\\cap\\) regular is context-free — even though CFL \\(\\cap\\) CFL need not be.",
    source: "Sipser §2.3 / Prob 2.18"
  },
  {
    id: "ch2-closure-why-not-complement-mc", chapter: 2, topic: "Closure properties", type: "mc",
    prompt: "Given that CFLs are closed under union but not under intersection, what does De Morgan's law let us conclude about closure under complement?",
    choices: [
      "CFLs cannot be closed under complement (else \\(\\cap\\) would follow from \\(\\cup\\))",
      "CFLs must be closed under complement",
      "Complement closure is independent of union and intersection closure",
      "CFLs are closed under complement only for finite languages"
    ],
    answer: 0,
    explanation: "\\(A\\cap B=\\overline{\\overline{A}\\cup\\overline{B}}\\). If CFLs were closed under complement and union, they would be closed under intersection — but they are not. Hence they cannot be closed under complement.",
    source: "Sipser §2.3"
  },

  // ---- Deterministic context-free languages / DPDAs ----
  {
    id: "ch2-dcfl-subset-tf", chapter: 2, topic: "Deterministic CFLs", type: "tf",
    prompt: "The deterministic context-free languages (DCFLs) are a strict subclass of the context-free languages.",
    answer: true,
    explanation: "Every DCFL is a CFL (a DPDA is a PDA), but some CFLs are not DCFLs — e.g. \\(\\{ww^{\\mathcal{R}}\\}\\) and \\(\\{a^ib^jc^k\\mid i=j\\text{ or }i=k\\}\\) need nondeterminism. So DCFL \\(\\subsetneq\\) CFL.",
    source: "Sipser §2.4 / Ex 2.40"
  },
  {
    id: "ch2-dcfl-complement-tf", chapter: 2, topic: "Deterministic CFLs", type: "tf",
    prompt: "The class of deterministic context-free languages is closed under complementation.",
    answer: true,
    explanation: "Theorem 2.42: by carefully swapping accept / non-accept reading states of a (normalized) DPDA, one recognizes the complement. This is unlike general CFLs, which are not closed under complement.",
    source: "Sipser Thm 2.42"
  },
  {
    id: "ch2-dpda-determinism-mc", chapter: 2, topic: "Deterministic CFLs", type: "mc",
    prompt: "What is the defining determinism condition on a DPDA's transition function \\(\\delta\\) (for each \\(q\\in Q\\), \\(a\\in\\Sigma\\), \\(x\\in\\Gamma\\))?",
    choices: [
      "exactly one of \\(\\delta(q,a,x),\\ \\delta(q,a,\\varepsilon),\\ \\delta(q,\\varepsilon,x),\\ \\delta(q,\\varepsilon,\\varepsilon)\\) is non-empty",
      "all four of those values are non-empty",
      "\\(\\delta(q,a,x)\\) always has exactly two elements",
      "\\(\\delta\\) never uses \\(\\varepsilon\\)-moves"
    ],
    answer: 0,
    explanation: "Definition 2.39 requires that among the four possibilities (read/\\(\\varepsilon\\) input crossed with pop/\\(\\varepsilon\\) stack) exactly one is non-empty, so at every configuration the DPDA has at most one legal move. \\(\\varepsilon\\)-moves are allowed, unlike in DFAs.",
    source: "Sipser Def 2.39"
  },
  {
    id: "ch2-dpda-endmarker-tf", chapter: 2, topic: "Deterministic CFLs", type: "tf",
    prompt: "Appending an endmarker \\(\\dashv\\) to inputs does not change the power of DPDAs: \\(A\\) is a DCFL if and only if \\(A\\dashv\\) is a DCFL.",
    answer: true,
    explanation: "Theorem 2.43 shows endmarkers do not change DPDA power, though they often make DPDAs easier to design because the machine can tell when the input ends. (Endmarkers ARE needed for the DPDA/DCFG equivalence, however.)",
    source: "Sipser Thm 2.43"
  },

  // ============================================================
  // ====  "What is …" definitions + "what does it generate?"  =
  // ============================================================
  {
    id: "ch2-concept-cfg-what", chapter: 2, topic: "CFG formal definition", type: "mc",
    prompt: "In plain terms, what is a **context-free grammar (CFG)**?",
    choices: [
      "A finite set of substitution rules — each replacing a single variable with a string of variables and terminals — that generate strings by repeated derivation from a start variable",
      "A finite-state machine with finitely many states and no extra memory",
      "A regular expression extended with an intersection operator",
      "A Turing machine restricted to move its head in only one direction"
    ],
    answer: 0,
    explanation: "A CFG generates a language: starting from the start variable, you repeatedly apply rules \\(A\\to(\\text{string of variables/terminals})\\) until only terminals remain. The left side of every rule is a single variable — that's what \"context-free\" means.",
    source: "Sipser Def 2.2"
  },
  {
    id: "ch2-concept-pda-what", chapter: 2, topic: "Pushdown automata", type: "mc",
    prompt: "In plain terms, what is a **pushdown automaton (PDA)**?",
    choices: [
      "A nondeterministic finite automaton augmented with a stack it can push to and pop from",
      "A finite automaton that may move its head in both directions",
      "A finite automaton with an unbounded read/write tape",
      "A grammar whose rules all have the form \\(A\\to aB\\)"
    ],
    answer: 0,
    explanation: "A PDA is an NFA plus a stack (LIFO memory). The stack — unbounded but accessible only at the top — is exactly what lets it count/match (e.g. \\(0^n1^n\\)). PDAs recognize precisely the context-free languages.",
    source: "Sipser Def 2.13"
  },
  {
    id: "ch2-concept-cfl-what", chapter: 2, topic: "Regular vs context-free", type: "mc",
    prompt: "What is a **context-free language (CFL)**?",
    choices: [
      "A language generated by some context-free grammar (equivalently, recognized by some pushdown automaton)",
      "A language recognized by some DFA",
      "Any language containing infinitely many strings",
      "A language closed under intersection and complement"
    ],
    answer: 0,
    explanation: "CFL = the class of languages a CFG can generate, equivalently a PDA can recognize (Thm 2.20). Every regular language is context-free, but not conversely; and CFLs are NOT closed under intersection or complement.",
    source: "Sipser Thm 2.20"
  },
  {
    id: "ch2-gen-0n1n", chapter: 2, topic: "Designing CFGs", type: "mc",
    prompt: "What language does the CFG \\(S\\to 0S1 \\mid \\varepsilon\\) generate?",
    choices: [
      "\\(\\{0^n1^n \\mid n\\ge 0\\}\\)",
      "\\(\\{0^n1^m \\mid n,m\\ge 0\\}\\)",
      "all strings of \\(0\\)'s followed by \\(1\\)'s",
      "\\(\\{(01)^n \\mid n\\ge 0\\}\\)"
    ],
    answer: 0,
    explanation: "Each use of \\(S\\to 0S1\\) adds one \\(0\\) on the left and one \\(1\\) on the right; \\(S\\to\\varepsilon\\) stops. So every derived string has the same number of \\(0\\)'s and \\(1\\)'s with all \\(0\\)'s first: \\(0^n1^n\\).",
    source: "Sipser §2.1 (Example 2.3)"
  },
  {
    id: "ch2-gen-balanced", chapter: 2, topic: "Designing CFGs", type: "mc",
    prompt: "What language does the CFG \\(S\\to (S) \\mid SS \\mid \\varepsilon\\) generate over \\(\\Sigma=\\{\\,(,)\\,\\}\\)?",
    choices: [
      "all strings of properly balanced parentheses",
      "\\(\\{\\,(^n)^n \\mid n\\ge 0\\,\\}\\) only",
      "all strings of parentheses of even length",
      "all strings over \\(\\{\\,(,)\\,\\}\\)"
    ],
    answer: 0,
    explanation: "\\(S\\to(S)\\) wraps a balanced string in a matched pair, \\(S\\to SS\\) concatenates two balanced strings, and \\(\\varepsilon\\) is empty — exactly the properly nested strings like \\(()(())\\). The \\((^n)^n\\)-only option misses \\(()()\\).",
    source: "Sipser §2.1"
  },
  {
    id: "ch2-gen-palindromes", chapter: 2, topic: "Designing CFGs", type: "mc",
    prompt: "What language does the CFG \\(S\\to 0S0 \\mid 1S1 \\mid 0 \\mid 1 \\mid \\varepsilon\\) generate over \\(\\Sigma=\\{0,1\\}\\)?",
    choices: [
      "all palindromes over \\(\\{0,1\\}\\) (strings equal to their reverse)",
      "\\(\\{ww \\mid w\\in\\{0,1\\}^*\\}\\)",
      "all strings of even length",
      "all strings with equally many \\(0\\)'s and \\(1\\)'s"
    ],
    answer: 0,
    explanation: "Rules \\(0S0\\) and \\(1S1\\) add matching symbols at both ends; the middle is \\(\\varepsilon\\) (even-length) or a lone \\(0\\)/\\(1\\) (odd-length). That builds exactly the strings that read the same forwards and backwards — the palindromes.",
    source: "Sipser §2.1"
  }
]);
