/* discussions3.js — a SECOND WAVE of real-world "discussion" builders, one for each
   under-served chapter (2, 3, 4, 5, 6, 8). Same conventions as discussions.js /
   discussions2.js: type:"discussion" with revealed-one-at-a-time mc/tf steps, each
   with an `explain`, then a whyMatters + realWorld + source per discussion. KaTeX in
   text uses \\( ... \\) (double backslash); SVG/diagram edge labels are plain Unicode. */
TOC.addQuestions([

  /* ===================== Ch 2 — nested structure is context-free ===================== */
  {
    id: "disc-ch2-html-nesting-not-regex", chapter: 2, topic: "Context-free languages", type: "discussion", rank: 24,
    prompt: "**\"Just parse the HTML with a regex.\"** Every few months someone tries — and it always breaks on nested tags like `<div><div>…</div></div>`. The reason is a theorem, not an opinion. Let's see why arbitrarily deep nesting is **context-free** but not **regular**.",
    svg: '<svg viewBox="0 0 480 170" xmlns="http://www.w3.org/2000/svg" font-family="Georgia, \'Times New Roman\', serif"><text x="240" y="20" text-anchor="middle" font-size="12" fill="var(--ink-soft)">matching an open tag to its close tag = matching brackets</text><g font-size="13" fill="var(--ink)" text-anchor="middle"><text x="60" y="70">&lt;div&gt;</text><text x="140" y="70">&lt;p&gt;</text><text x="240" y="70">text</text><text x="330" y="70">&lt;/p&gt;</text><text x="420" y="70">&lt;/div&gt;</text></g><g stroke="var(--brand)" stroke-width="1.6" fill="none"><path d="M 60 80 C 60 130, 420 130, 420 80"/><path d="M 140 80 C 140 108, 330 108, 330 80"/></g><g fill="var(--brand)" font-size="10.5" text-anchor="middle"><text x="240" y="150">each close must match the most recent still-open tag (LIFO)</text></g></svg>',
    steps: [
      { prompt: "Strip HTML down to just its tags and it looks like nested brackets: an open tag `<t>` must be closed by `</t>`, and closings pair with the **most recently** opened tag. What abstract language is this exactly like?", type: "mc",
        choices: ["Balanced parentheses \\(\\{\\,w \\mid w \\text{ is a balanced bracket string}\\,\\}\\) — a context-free language", "A finite language with a few dozen members", "The regular language \\((\\texttt{<t>}\\,\\texttt{</t>})^*\\)", "\\(\\Sigma^*\\) — literally every string"], answer: 0,
        explain: "Well-nested tags are exactly **balanced brackets**, generated by the CFG \\(S\\to \\langle t\\rangle\\,S\\,\\langle /t\\rangle \\mid SS \\mid \\varepsilon\\). Matching each close to the most-recent open is last-in-first-out — a **stack** discipline — so the language is **context-free**, not regular." },
      { prompt: "A regular expression is compiled to a **DFA** with a fixed, finite number of states. Why can no DFA (hence no true regex) recognize arbitrarily deep nesting like \\(\\langle\\rangle^n \\cdots \\langle/\\rangle^n\\)?", type: "mc",
        choices: ["To match \\(n\\) closes to \\(n\\) opens it must remember \\(n\\), but \\(n\\) is unbounded and the DFA has finitely many states", "DFAs cannot read the character `<`", "Regexes are too slow, though a DFA could in principle do it", "Nesting is fine for a DFA; the real problem is attributes"], answer: 0,
        explain: "Tracking nesting **depth** means counting opens minus closes without limit. A DFA has only finitely many states, so by the pumping lemma it cannot recognize \\(\\{\\langle\\rangle^n\\langle/\\rangle^n\\}\\) for all \\(n\\) — the same barrier that makes \\(0^n1^n\\) non-regular. You need a **stack** (a PDA)." },
      { prompt: "The same nesting shows up in biology: an RNA strand folds when a subsequence base-pairs with a **later, reversed** complementary subsequence (a stem-loop / hairpin), and these pairings **nest** without crossing. True or false: this nested base-pairing structure is naturally modeled by a **context-free** grammar.", type: "tf", answer: true,
        explain: "True. Non-crossing (nested) base pairs are exactly the bracket-matching pattern, so RNA secondary structure is modeled by CFGs — this is the basis of real **stochastic context-free grammar** folding predictors. (Only *crossing* pairs, called pseudoknots, escape context-free.)" },
      { prompt: "So the crisp takeaway about \"parse HTML/JSON with a regex\" is:", type: "mc",
        choices: ["Unbounded nesting needs a stack (a PDA / context-free parser); finite-memory regex fundamentally can't do it", "It works fine as long as the regex is long enough", "Regexes can do it but only in Perl", "Nesting is a regular-language problem after all"], answer: 0,
        explain: "Matching nested delimiters to arbitrary depth requires **unbounded memory in stack form** — the defining power of a **PDA / context-free** parser. A regex (finite memory) can scan tokens but cannot enforce balanced nesting, which is precisely why real parsers for HTML, JSON, and code are context-free, not regex-based." }
    ],
    explanation: "Arbitrarily deep nesting — HTML/XML tags, JSON braces, RNA stem-loops — is the **balanced-bracket** language: context-free (a CFG / PDA with a stack) but **not regular**. A DFA, and therefore a genuine regular expression, has only finite memory and cannot count nesting depth without bound.",
    whyMatters: "It draws the practical line between what a **regex** can do (tokenize, validate flat patterns) and what needs a real **parser** (anything with recursive, nested structure). Reaching for the wrong tool is a classic, theory-predictable bug.",
    realWorld: "**Every** compiler, `JSON.parse`, and XML/HTML library uses a stack-based (context-free) parser, never a regex, for nesting — and RNA-folding tools like `Infernal` literally use **stochastic context-free grammars**. The famous Stack Overflow answer \"you can't parse HTML with regex\" is this theorem in disguise.",
    source: "Sipser 2.1–2.2 (CFGs, PDAs ≡ CFGs); 1.4 (nonregularity of \\(0^n1^n\\))"
  },

  /* ===================== Ch 3 — surprising Turing-completeness ===================== */
  {
    id: "disc-ch3-game-of-life-turing-complete", chapter: 3, topic: "Church–Turing thesis", type: "discussion", rank: 26,
    prompt: "**Conway's Game of Life** is a grid of cells that live or die by three tiny rules, with no numbers, no memory, no program — just blinking dots. Astonishingly, it can run **any** computation your laptop can. Let's see why that's not hype, and what \"Turing-complete\" really claims.",
    svg: '<svg viewBox="0 0 300 200" xmlns="http://www.w3.org/2000/svg" font-family="Georgia, \'Times New Roman\', serif"><g stroke="var(--ink-soft)" stroke-width="0.8">\n<line x1="30" y1="30" x2="270" y2="30"/><line x1="30" y1="70" x2="270" y2="70"/><line x1="30" y1="110" x2="270" y2="110"/><line x1="30" y1="150" x2="270" y2="150"/>\n<line x1="30" y1="30" x2="30" y2="150"/><line x1="70" y1="30" x2="70" y2="150"/><line x1="110" y1="30" x2="110" y2="150"/><line x1="150" y1="30" x2="150" y2="150"/><line x1="190" y1="30" x2="190" y2="150"/><line x1="230" y1="30" x2="230" y2="150"/><line x1="270" y1="30" x2="270" y2="150"/></g><g fill="var(--brand)"><rect x="71" y="31" width="38" height="38"/><rect x="151" y="71" width="38" height="38"/><rect x="31" y="111" width="38" height="38"/><rect x="111" y="111" width="38" height="38"/><rect x="191" y="111" width="38" height="38"/></g><text x="150" y="178" text-anchor="middle" font-size="12" fill="var(--ink-soft)">a \'glider\': a moving signal built from live cells</text></svg>',
    steps: [
      { prompt: "A system is called **Turing-complete** when it can simulate a Turing machine — i.e. compute anything a TM can. In Game of Life, moving \"glider\" patterns act as signals, glider collisions act as logic gates, and stable patterns store bits. What does building those components let you conclude?", type: "mc",
        choices: ["Life can implement logic gates, memory, and wiring, so it can simulate any TM — it is Turing-complete", "Life can only make pretty patterns; computation is a coincidence", "Life is more powerful than a Turing machine", "Nothing follows unless you also add a CPU"], answer: 0,
        explain: "Computation needs just three ingredients: **signals**, **logic gates**, and **memory** — all three have been constructed in Life (gliders, glider-gun/eater collisions, stable storage). Wire them together and you can build a universal machine, so Life can compute **anything a TM can**: it is Turing-complete." },
      { prompt: "By the **Church–Turing thesis**, \"computable by any reasonable mechanical procedure\" = \"computable by a Turing machine.\" Given that, what's the significance of Life (or a spreadsheet, or the game-of-redstone) turning out to be Turing-complete?", type: "mc",
        choices: ["These wildly different systems all top out at exactly the same computational power — the TM's", "It proves the Church–Turing thesis is false", "It shows Life can solve the halting problem", "It means Life is faster than a real computer"], answer: 0,
        explain: "It's a vivid confirmation of the thesis: cellular automata, spreadsheets, λ-calculus, and your CPU are all **Turing-equivalent** — none computes more than a basic TM. \"Any reasonable model of computation = a Turing machine\" keeps being borne out by systems that were never designed to compute." },
      { prompt: "Being Turing-complete is a double-edged sword. Because Life can simulate an arbitrary TM, deciding whether a given Life pattern ever produces a certain cell **inherits** undecidability. True or false: there is no algorithm that, for every starting pattern, decides whether Life eventually reaches a given configuration.", type: "tf", answer: true,
        explain: "True. Turing-completeness cuts both ways: you gain universal power but also **inherit the halting problem**. Since a TM's halting can be encoded as a Life pattern reaching a state, a general \"will this pattern ever do X?\" decider would decide halting — impossible. Undecidability rides along with universality." },
      { prompt: "So the real lesson of \"look, my spreadsheet / Minecraft redstone / Game of Life is Turing-complete\" is:", type: "mc",
        choices: ["Universal computation emerges from astonishingly simple rules, and it always brings the same power and the same limits", "Simple systems are safe from undecidability", "Turing-completeness is rare and needs elaborate design", "Only silicon computers can be Turing-complete"], answer: 0,
        explain: "The Church–Turing thesis says there's essentially **one** notion of computation, and it shows up everywhere — from three-rule cellular automata to card games — always with the **same ceiling** (universal) and the **same floor** (halting/undecidability). Simplicity of the rules is no protection from either." }
    ],
    explanation: "Simulating a TM needs only **signals + logic gates + memory**, and Conway's Game of Life (like spreadsheets and Minecraft redstone) can build all three — so it is **Turing-complete**. By the **Church–Turing thesis** that means it computes exactly what any TM does: no more (it can't beat the halting problem) and no less.",
    whyMatters: "It makes the Church–Turing thesis concrete: \"any reasonable computation = a Turing machine\" isn't a definition imposed on the world, it's a pattern the world keeps matching, in systems nobody built to compute. And it warns that undecidability tags along with any universal system.",
    realWorld: "People have built working **CPUs and even Tetris inside Conway's Life**, Turing machines out of **Minecraft redstone**, and universal computers in the card game **Magic: The Gathering** and in spreadsheet formulas. Each is a party trick with a deep moral: universality is cheap, and it always carries the halting problem with it.",
    source: "Sipser 3.2–3.3 (Church–Turing thesis, equivalence of models)"
  },

  /* ===================== Ch 4 — more languages than machines ===================== */
  {
    id: "disc-ch4-more-languages-than-programs", chapter: 4, topic: "More languages than machines", type: "discussion", rank: 30,
    prompt: "**Here is a genuinely unsettling fact: almost every problem is unsolvable — not because we're not clever enough, but by sheer counting.** There are only so many programs you could ever write, yet vastly more problems to solve. Let's make \"vastly more\" precise with Cantor.",
    steps: [
      { prompt: "Every program (equivalently, every Turing machine) is a **finite** string of symbols. Listing all finite strings by length, then alphabetically, gives a first, second, third, … How big is the set of all possible programs?", type: "mc",
        choices: ["Countably infinite — they can be put in a numbered list \\(1,2,3,\\dots\\)", "Finite — there are only so many useful programs", "Uncountably infinite — bigger than the integers", "The same size as the real numbers"], answer: 0,
        explain: "Finite strings over a fixed alphabet can be enumerated (by length, then lexicographically), so there are only **countably many** programs — you can pin a natural-number index on each. This is the small side of the coming mismatch." },
      { prompt: "A **language** is any subset of \\(\\Sigma^*\\) (any set of strings), and a decision problem is just \"is \\(w\\) in language \\(L\\)?\". Cantor's diagonal argument shows the set of **all** languages over \\(\\Sigma\\) is:", type: "mc",
        choices: ["Uncountable — strictly more numerous than any list can hold", "Countable — same size as the set of programs", "Finite", "Exactly equal in size to \\(\\Sigma^*\\) itself"], answer: 0,
        explain: "The languages over \\(\\Sigma\\) are the **subsets** of the countably-infinite set \\(\\Sigma^*\\), i.e. the power set. By Cantor's theorem \\(|\\,\\mathcal P(\\Sigma^*)\\,|\\) is strictly larger than \\(|\\Sigma^*|\\) — it is **uncountable**. There are as many languages as there are real numbers." },
      { prompt: "Put the two facts side by side: **countably many** programs, but **uncountably many** languages. What is forced?", type: "mc",
        choices: ["Some (in fact almost all) languages have no recognizer at all — more problems than programs", "Every language still gets a program, just reuse them", "The extra languages are all finite and harmless", "It means there are uncountably many programs after all"], answer: 0,
        explain: "You cannot inject an **uncountable** set (languages) into a **countable** one (programs): there aren't enough programs to go around. So **most** languages are recognized by no machine — undecidability isn't exotic, it's the overwhelming default; the recognizable languages are a vanishingly thin slice." },
      { prompt: "True or false: this counting argument proves a specific everyday program is undecidable, like \\(A_{TM}\\).", type: "tf", answer: false,
        explain: "False — and this is the subtle part. Counting proves **existence** (undecidable languages must exist, in abundance) but names **none** of them; it's non-constructive. To show a *particular* natural problem like \\(A_{TM}\\) is undecidable you still need **diagonalization/reduction** (Thm 4.11). Counting says the monsters are everywhere; reductions catch a named one." }
    ],
    explanation: "There are only **countably many** programs (finite strings) but **uncountably many** languages (subsets of \\(\\Sigma^*\\), by Cantor). A countable supply cannot cover an uncountable demand, so **almost every** language is undecidable — most problems have no algorithm at all. The argument proves they exist in abundance without exhibiting a specific one.",
    whyMatters: "It reframes undecidability from \"a few weird edge cases\" to \"the generic situation.\" Solvable problems are the rare, precious exceptions — which is exactly why the whole theory of what *is* computable is worth building so carefully.",
    realWorld: "The same countable-vs-uncountable gap means **almost every real number is uncomputable** and almost every infinite bit-stream is incompressible/random: there simply aren't enough finite descriptions (programs) to name them all. Every file, model, or algorithm you'll ever build lives inside that thin countable sliver of \"describable\" things.",
    source: "Sipser 4.2 (Cor 4.18: some languages are not Turing-recognizable; Thm 4.17 diagonalization)"
  },

  /* ===================== Ch 5 — Rice's theorem / no perfect malware scanner ===================== */
  {
    id: "disc-ch5-rice-no-perfect-malware-scanner", chapter: 5, topic: "Rice's theorem", type: "discussion", rank: 30,
    prompt: "**A dream product: an App-Store gatekeeper that reads any submitted app's code and decides, perfectly, \"does this app ever exfiltrate your contacts?\"** No false alarms, no misses, works on every app. **Rice's theorem** says: give up — it cannot exist. Let's see why any such tool is doomed.",
    steps: [
      { prompt: "The scanner is judged on what the program **does** when it runs (its behavior / the language it computes: \"does it ever send your contacts to a server?\"), not on cosmetic details of the source text. In Rice's terms, this makes \"is-malware\" a property of the program's…", type: "mc",
        choices: ["Semantics — the function/behavior it computes", "Syntax — how many lines or which variable names it uses", "File size on disk", "Programming language it's written in"], answer: 0,
        explain: "Rice's theorem is about **semantic** properties — properties of the **behavior** (the recognized language / the function computed), not the surface text. \"Ever exfiltrates contacts?\" depends purely on what the program *does*, so it's a semantic property and Rice's theorem is in scope." },
      { prompt: "The property must also be **nontrivial**: some programs have it, some don't. Is \"ever exfiltrates your contacts\" nontrivial?", type: "mc",
        choices: ["Yes — a plain calculator app never does it, while a spyware app does, so the property splits programs into both camps", "No — every program has this property", "No — no program can ever have this property", "It's undefined for most programs"], answer: 0,
        explain: "Nontrivial means **neither** always-true nor always-false: at least one program exfiltrates and at least one doesn't. A calculator clearly never does; obvious spyware does. Both cases exist, so the property is nontrivial — the last condition Rice's theorem needs." },
      { prompt: "**Rice's theorem:** *every* nontrivial semantic property of programs is **undecidable**. Applying it to our scanner tells us:", type: "mc",
        choices: ["No algorithm can decide, for every possible app, whether it has the behavior — a perfect scanner is impossible", "It's decidable but merely slow", "It's decidable for apps under 1000 lines", "Only handwritten (not compiled) apps are undecidable"], answer: 0,
        explain: "Because \"exfiltrates contacts\" is **nontrivial** and **semantic**, Rice's theorem makes it **undecidable** outright: there is no algorithm that answers correctly for *every* app. No amount of engineering escapes it — the impossibility is mathematical, not a matter of resources." },
      { prompt: "So what do real security tools actually do, given Rice's wall? True or false: they must **approximate** — accepting false positives (flagging safe apps) and/or false negatives (missing bad ones) — because a perfect decider is impossible.", type: "tf", answer: true,
        explain: "True. Since perfection is impossible, every real scanner **approximates** and is deliberately unsound or incomplete: it over-approximates (flag anything suspicious → false alarms) or under-approximates (only flag known-bad patterns → misses novel malware), usually both. Signatures, heuristics, sandboxing, and manual review are all responses to Rice's theorem." }
    ],
    explanation: "\"Does this app ever exfiltrate contacts?\" is a **nontrivial semantic** property of a program's behavior, so **Rice's theorem** makes it **undecidable**: no algorithm decides it correctly for every app. A flawless malware scanner / auto-reviewer is therefore mathematically impossible, and real tools must approximate with false positives and negatives.",
    whyMatters: "It sets a hard ceiling on **every** automated program-analysis tool — antivirus, App-Store review, linters, verifiers, type checkers. Knowing the perfect tool can't exist tells engineers to aim for good, tunable approximations rather than a mythical exact one.",
    realWorld: "Antivirus engines rely on **signatures + heuristics + sandboxing** and still miss zero-days; App Store / Play Store use automated scans plus **human review**; compilers' static analyzers warn conservatively (\"this might be null\"). All of them are living with Rice's theorem — trading false alarms against missed threats because perfection is provably unreachable.",
    source: "Sipser 5.4 (Rice's theorem; undecidability of semantic properties)"
  },

  /* ===================== Ch 6 — no universal lossless compressor ===================== */
  {
    id: "disc-ch6-no-universal-compressor", chapter: 6, topic: "Descriptive complexity", type: "discussion", rank: 28,
    prompt: "**Someone pitches you \"ZipMax\": a lossless compressor that shrinks *any* file by at least one bit.** Feed it anything, get something strictly smaller, and you can always decompress back exactly. It sounds plausible — and it's impossible. A one-line counting argument kills it. Let's build that argument.",
    steps: [
      { prompt: "The **Kolmogorov complexity** \\(K(x)\\) of a string \\(x\\) is the length of the **shortest program** that outputs \\(x\\). A string is **incompressible** when \\(K(x)\\) is about \\(|x|\\) — no program shorter than \\(x\\) itself produces it. Intuitively, incompressible strings are the ones that…", type: "mc",
        choices: ["Have no exploitable pattern — the string basically *is* its own shortest description", "Are the easiest to compress", "Are always very short", "Contain only zeros"], answer: 0,
        explain: "\\(K(x)\\) measures a string's true information content as \"shortest generating program.\" If nothing shorter than \\(x\\) generates it, \\(x\\) has **no pattern to exploit** — it's **incompressible** and essentially random. All-zero strings are the opposite: a tiny loop prints them, so \\(K\\) is small." },
      { prompt: "Now the pigeonhole/counting heart of it. A lossless compressor is a **one-to-one** map on files (different inputs must give different outputs, or you couldn't decompress). How many binary strings are there of length **exactly** \\(n\\), versus of length **strictly less than** \\(n\\)?", type: "mc",
        choices: ["\\(2^n\\) strings of length \\(n\\), but only \\(2^n-1\\) strings of length \\(<n\\)", "The same number of each", "More strings of length \\(<n\\) than of length \\(n\\)", "Infinitely many of each, so it doesn't matter"], answer: 0,
        explain: "There are \\(2^n\\) strings of length \\(n\\), but only \\(1+2+4+\\cdots+2^{n-1}=2^n-1\\) strings of length \\(<n\\) **combined**. So the \"shorter than \\(n\\)\" pigeonholes number **one fewer** than the length-\\(n\\) inputs you'd need to stuff into them." },
      { prompt: "You want to map all \\(2^n\\) length-\\(n\\) files, one-to-one, into strictly shorter outputs (length \\(<n\\)). Why is that impossible?", type: "mc",
        choices: ["\\(2^n\\) inputs can't injectively fit into \\(2^n-1\\) shorter slots — by pigeonhole two inputs must collide, breaking decompression", "It's possible if the compressor is clever enough", "You just need outputs of length \\(n\\), which exist", "Decompression doesn't require the map to be one-to-one"], answer: 0,
        explain: "**Pigeonhole:** \\(2^n\\) items cannot be placed injectively into \\(2^n-1\\) boxes — some two distinct files map to the **same** compressed string, so the decompressor can't recover both. Hence **no** lossless scheme can shrink *every* input; at least one string of each length must stay the same size or grow." },
      { prompt: "So what's the honest statement about real compressors like ZIP or PNG? True or false: any lossless compressor that shrinks some inputs must **enlarge (or leave unchanged) others**, and it only wins in practice because real data is patterned, not random.", type: "tf", answer: true,
        explain: "True. Counting forces a trade-off: shrinking some files means **expanding** others (equivalently, incompressible/random files can't be shrunk at all). ZIP wins because everyday data — text, images, logs — is far from random and has structure to exploit; feed it already-compressed or truly random data and it barely helps or slightly grows the file." }
    ],
    explanation: "By **Kolmogorov complexity**, most strings are **incompressible** (random-looking), and by a **pigeonhole** count there are \\(2^n\\) length-\\(n\\) files but only \\(2^n-1\\) shorter ones — so no lossless compressor can be injective while shrinking *every* input. A \"shrinks-everything\" compressor is therefore impossible; real ones only exploit the patterns in non-random data.",
    whyMatters: "It's the rigorous reason \"universal compression\" scams keep failing, and it pins down what compression *is*: removing redundancy/pattern. Truly random data has none, so its Kolmogorov complexity — its real information content — can't be reduced.",
    realWorld: "Zipping an already-zipped or encrypted file usually makes it **slightly larger**, exactly as the counting predicts. It's also why encrypted traffic (which looks random) barely compresses, and it underpins the theory of randomness and lower bounds — \\(K(x)\\) is the ultimate limit no ZIP, PNG, or FLAC can beat.",
    source: "Sipser 6.4 (Kolmogorov complexity; incompressible strings, Thm 6.27–6.28)"
  },

  /* ===================== Ch 8 — L and NL / PATH in a maze ===================== */
  {
    id: "disc-ch8-maze-path-logspace-nl", chapter: 8, topic: "L and NL", type: "discussion", rank: 30,
    prompt: "**You're dropped into a gigantic maze — thousands of junctions — with only a tiny sticky note to write on.** You can't map the whole thing; the note holds just a couple of junction numbers. Can you still find your way from start to exit? This is the **PATH** problem, and it's the poster child for **logarithmic space**.",
    grid: { title: "the maze is just a graph: junctions = nodes, corridors = edges",
      cells: [
        ["S", "•", "•", null],
        [null, null, "•", "•"],
        ["•", "•", "•", null],
        ["•", null, "•", "T"]
      ],
      note: "PATH: is there a route of edges from S to T?" },
    steps: [
      { prompt: "Model the maze as a graph: junctions are **nodes**, corridors are **edges**. \"Is there a route from start \\(s\\) to exit \\(t\\)?\" is exactly the problem **PATH** \\(=\\{\\langle G,s,t\\rangle \\mid G \\text{ has a directed path } s\\to t\\}\\). The obvious BFS/DFS solves it, but what does BFS need to store?", type: "mc",
        choices: ["A queue plus a \"visited\" mark for potentially *every* node — memory that grows with the graph", "Just two node numbers, always", "Nothing — it's constant memory", "The entire list of all paths in the graph"], answer: 0,
        explain: "Textbook BFS/DFS keeps a **visited set** (and a queue/stack) that can hold a large fraction of the graph's nodes — that's **linear** space. Fast, but memory-hungry: it's off-limits if all you have is a sticky note (logarithmic space). We need a thriftier method." },
      { prompt: "Space is measured on a **read-only** input (the maze) plus a small **work tape** (your sticky note). Writing down one junction's number among \\(n\\) junctions costs about \\(\\log_2 n\\) bits. If your algorithm only ever remembers a **constant number** of junction numbers at once, how much work-tape space is that?", type: "mc",
        choices: ["\\(O(\\log n)\\) — logarithmic space (the class L / NL)", "\\(O(n)\\) — linear space", "\\(O(1)\\) — truly constant, independent of \\(n\\)", "\\(O(n^2)\\) — quadratic space"], answer: 0,
        explain: "A single node index needs \\(\\lceil\\log_2 n\\rceil\\) bits; storing a **fixed** number of them is \\(O(\\log n)\\) total — **logarithmic** in the input size. Problems solvable this way (deterministically) form **L**; with nondeterministic guessing, **NL**. The input itself doesn't count toward space, only your sticky note does." },
      { prompt: "A **nondeterministic** log-space machine can solve PATH by *guessing* the route one step at a time: keep only the **current** junction and a **step counter**, at each step guess a neighbor to walk to, and accept if you reach \\(t\\) within \\(n\\) steps. Why does this fit in \\(O(\\log n)\\) space?", type: "mc",
        choices: ["It stores only the current node and a counter (each \\(O(\\log n)\\)) — never the whole path or a visited set", "It writes down the entire guessed path", "It marks every visited node like BFS", "It needs no memory because it's nondeterministic"], answer: 0,
        explain: "The trick is to **not** remember where you've been: hold just the **current** junction and a counter of steps taken (bounded by \\(n\\), so \\(O(\\log n)\\) bits). Guess the next corridor, overwrite the current node, increment the counter, accept on reaching \\(t\\). This puts **PATH in NL** — in fact PATH is **NL-complete**." },
      { prompt: "So how do L and NL relate for PATH? We know \\(L\\subseteq NL\\), and PATH is NL-complete. True or false: whether **L = NL** — i.e. whether *deterministic* log space is as powerful as nondeterministic — is a famous **open** problem.", type: "tf", answer: true,
        explain: "True. \\(L\\subseteq NL\\subseteq P\\) all hold, and PATH's nondeterministic \\(O(\\log n)\\) solution puts it in NL. Whether a **deterministic** log-space machine can match it (making \\(L=NL\\)) is **open** — a small-space cousin of P vs NP. (Savitch gives \\(NL\\subseteq \\mathrm{SPACE}(\\log^2 n)\\), and Immerman–Szelepcsényi shows NL is closed under complement — but L vs NL stays unresolved.)" }
    ],
    explanation: "Finding a route in a maze is **PATH** (directed \\(s\\)-\\(t\\) reachability). A nondeterministic machine solves it in **logarithmic space** — a \"sticky note\" holding only the current node and a step counter — which makes PATH **NL-complete**. Deterministic log space is **L**; whether **L = NL** is a major open question.",
    whyMatters: "Log space is the natural model for computing on data far too big to fit in memory — you get \\(O(\\log n)\\) working notes over a huge read-only input. PATH/reachability is the fundamental problem there, and L-vs-NL is the space-world echo of P-vs-NP.",
    realWorld: "**GPS routing, network path-finding, and traceroute** are reachability at heart; graph engines that stream enormous graphs from disk lean on small-work-space reachability. The theory says the *existence* of a route is checkable with astonishingly little scratch memory — you don't have to hold the whole map in your head to know a path exists.",
    source: "Sipser 8.4–8.5 (L, NL; PATH is NL-complete, Thm 8.25; Savitch, Immerman–Szelepcsényi)"
  }

]);
