/* "Discussion builder" questions — a real-world scenario plus a guided series
   of auto-graded sub-questions, revealed one at a time with teaching after each,
   then a "why this matters" + a real example. type: "discussion".
   Each step: { prompt, type:"mc"|"tf", choices?, answer, explain, diagram?/svg? }.
   Spread across the whole spectrum so intuition is built everywhere. */
TOC.addQuestions([

  /* ===================== Ch 1 — finite memory ===================== */
  {
    id: "disc-ch1-vending-finite-memory", chapter: 1, topic: "Finite automata", type: "discussion", rank: 18,
    prompt: "**A soda machine** wants 30¢, taking only dimes. It tracks how much you've put in and dispenses at 30¢. Let's see what kind of \"computer\" that is — and where its powers run out.",
    diagram: { width: 470, height: 120, states: [
      { id: "q0", x: 55, y: 60, start: true, label: "0" },
      { id: "q1", x: 170, y: 60, label: "10" },
      { id: "q2", x: 285, y: 60, label: "20" },
      { id: "q3", x: 405, y: 60, accept: true, label: "30" }
    ], edges: [
      { from: "q0", to: "q1", label: "10¢" },
      { from: "q1", to: "q2", label: "10¢" },
      { from: "q2", to: "q3", label: "10¢" },
      { from: "q3", to: "q3", label: "10¢", loop: "up" }
    ] },
    steps: [
      { prompt: "The machine only needs to remember the running total (0, 10, 20, or 30¢) — never the exact sequence of coins. How many distinct \"states\" of memory does it need?", type: "mc",
        choices: ["A fixed, finite number (here, 4)", "One for every coin ever inserted", "Infinitely many — it must recall the whole history"], answer: 0,
        explain: "It only cares **which total** it's at, not how it got there. A fixed, finite set of states is exactly a **DFA** (deterministic finite automaton) — a machine with bounded memory." },
      { prompt: "Now suppose we wanted a machine that accepts \\(\\{0^n1^n \\mid n\\ge 0\\}\\) — the same number of 0s then 1s, for **any** \\(n\\). Can a DFA do this?", type: "tf", answer: false,
        explain: "No. To match the counts it would have to **remember \\(n\\)**, but \\(n\\) is unbounded and a DFA has only finitely many states. This is the classic **non-regular** language (proved via the pumping lemma)." },
      { prompt: "So what's the dividing line a finite-state machine can't cross?", type: "mc",
        choices: ["Counting/matching an unbounded quantity", "Reading long inputs", "Having many letters in the alphabet"], answer: 0,
        explain: "Long inputs and big alphabets are fine. What kills a DFA is needing **unbounded counting/memory** — that's precisely what separates regular from non-regular languages." }
    ],
    explanation: "A DFA is a computer with a **fixed, finite memory**: it can track a bounded amount of state but cannot count without limit. That single limitation is the boundary of the regular languages.",
    whyMatters: "\"Finite memory\" isn't a toy idea — it's the exact power of the pattern-matchers built into every text editor, search bar, and programming language. Knowing what a DFA *can't* do tells you when you need something stronger.",
    realWorld: "**Regular expressions** (regex) are DFAs in disguise. That's why a regex can validate a phone number or split words, but **cannot** match balanced/nested parentheses to arbitrary depth — the famous \"you can't parse HTML with regex\" — because that needs unbounded counting.",
    source: "Sipser 1.4 (pumping lemma / nonregularity)"
  },

  /* ===================== Ch 2 — context-free / a stack ===================== */
  {
    id: "disc-ch2-brackets-stack", chapter: 2, topic: "Context-free languages", type: "discussion", rank: 20,
    prompt: "**Checking code for balanced brackets** — like `([{}])` — is something every editor does. A plain finite-state machine can't (it's unbounded nesting). What's the smallest extra gadget that makes it possible?",
    steps: [
      { prompt: "To check that every `(` has a matching `)` (nested arbitrarily deep), what memory structure naturally fits — you push on an open and pop on a close?", type: "mc",
        choices: ["A stack (last-in, first-out)", "A queue (first-in, first-out)", "A single counter that only goes up"], answer: 0,
        explain: "A **stack** is perfect: push when you see `(`, pop when you see `)`. If the stack is empty at the end and never popped-when-empty, the brackets balance. A finite control **plus a stack** is a **pushdown automaton (PDA)**." },
      { prompt: "Languages a PDA can recognize are exactly the languages generated by which kind of grammar?", type: "mc",
        choices: ["Context-free grammars (CFGs)", "Regular expressions", "There is no grammar for them"], answer: 0,
        explain: "PDAs and **CFGs** describe the same class — the **context-free languages**. The grammar rule \\(S\\to (S) \\mid SS \\mid \\varepsilon\\) generates exactly the balanced strings the stack checks." },
      { prompt: "True or false: a single counter (not a full stack) is enough to check `([{}])`-style brackets where the *type* of bracket must also match.", type: "tf", answer: false,
        explain: "A bare counter tracks **depth** but not **which** bracket is open, so it would accept `(]`. You need the stack to remember the *kind* of each open bracket — that's the extra power of context-free over regular." }
    ],
    explanation: "Add one **stack** to a finite-state machine and you get a **PDA** — the machine model for **context-free languages**. The stack is exactly what lets you match nested structure that a DFA cannot.",
    whyMatters: "Nested structure is everywhere in computing, and recognizing it is the job of a *parser*. CFGs are the formal backbone of essentially every programming-language grammar.",
    realWorld: "**Compilers** parse your source code with context-free grammars; **JSON/XML/HTML** parsers track nesting with a stack; even arithmetic like `3*(4+5)` is parsed this way. When a linter says \"unbalanced brace,\" a PDA-style stack check just failed.",
    source: "Sipser 2.2 (PDAs ≡ CFGs)"
  },

  /* ===================== Ch 3 — the universal machine ===================== */
  {
    id: "disc-ch3-tape-scratch-paper", chapter: 3, topic: "Turing machines", type: "discussion", rank: 20,
    prompt: "**What makes a Turing machine able to compute *anything* computable?** It's a finite-state controller with one new thing: an unlimited tape it can read and write. Let's see why that one addition is everything.",
    steps: [
      { prompt: "The key upgrade from a DFA to a Turing machine is the tape. What does the (unbounded, read/write) tape give the machine?", type: "mc",
        choices: ["Unlimited scratch memory it can revisit and rewrite", "Faster reading of the input", "The ability to use more states"], answer: 0,
        explain: "The tape is **unlimited, rewritable scratch paper**. Unlike a DFA's fixed memory or a PDA's restricted stack, the TM can store, revisit, and overwrite anything — which is what lets it count, simulate, and compute without limit." },
      { prompt: "The **Church–Turing thesis** claims: any function that can be computed by *any* reasonable mechanical procedure can be computed by a Turing machine.", type: "tf", answer: true,
        explain: "Yes — this is the thesis that pins down \"computable.\" Every model anyone has proposed (multi-tape TMs, RAM machines, λ-calculus, your laptop) computes **exactly** the same set of functions as the basic TM." },
      { prompt: "A two-tape TM, or one that can move its head in clever ways — is it *more powerful* (computes more languages) than a basic one-tape TM?", type: "tf", answer: false,
        explain: "No. These variants are **equivalent in power** — each can be simulated by the basic model (sometimes slower, but computing the same languages). Robustness across variants is exactly why the TM is the accepted definition of computation." }
    ],
    explanation: "A Turing machine = finite control + **unlimited rewritable memory**. By the **Church–Turing thesis**, that captures *all* of computation; every reasonable variant computes the same things.",
    whyMatters: "This is the definition of \"computable\" itself. It's also why a result proved about Turing machines (like undecidability) applies to **every** programming language and computer ever built.",
    realWorld: "Your phone, your laptop, Python, and a 1970s mainframe are all **Turing-equivalent** — they differ in speed and convenience, not in *what* they can ultimately compute. \"Turing-complete\" (said of languages, spreadsheets, even some game engines) means exactly this.",
    source: "Sipser 3.1–3.3 (TM variants, Church–Turing thesis)"
  },

  /* ===================== Ch 4 — decidable vs recognizable ===================== */
  {
    id: "disc-ch4-decidable-vs-recognizable", chapter: 4, topic: "Decidability", type: "discussion", rank: 30,
    prompt: "**Imagine an over-eager assistant** who, asked \"is X in the club?\", *always* shouts \"YES!\" the moment it's true — but on a non-member sometimes just keeps searching forever, never answering. Useful? Sort of. Reliable? Let's pin down exactly what's going on.",
    steps: [
      { prompt: "This assistant confirms every true \"yes\" but may loop forever on a \"no.\" In computability terms, the language is…", type: "mc",
        choices: ["Turing-recognizable (but maybe not decidable)", "Decidable", "Not even recognizable"], answer: 0,
        explain: "**Recognizable** = a machine that accepts (halts \"yes\") on every member, but may **loop forever** on non-members. **Decidable** is the stronger property: it *always* halts with yes **or** no." },
      { prompt: "\"Just add a timeout — if it runs too long, answer no.\" Why doesn't that turn recognition into decision?", type: "mc",
        choices: ["You can't tell \"still working\" from \"will run forever\"", "Timeouts are too slow", "It would use too much memory"], answer: 0,
        explain: "There's no safe cutoff: a computation taking a long time is **indistinguishable** from one that never halts. Any fixed timeout will wrongly reject some real members. That gap is the whole difference." },
      { prompt: "\\(A_{TM} = \\{\\langle M, w\\rangle \\mid M \\text{ accepts } w\\}\\) is the classic example: recognizable (simulate \\(M\\) on \\(w\\)) but **undecidable**.", type: "tf", answer: true,
        explain: "Exactly. Simulating \\(M\\) confirms every real acceptance, so \\(A_{TM}\\) is recognizable — but if \\(M\\) loops on \\(w\\), the simulation loops too, and (by diagonalization) **no** machine can always decide it." }
    ],
    explanation: "**Recognizable**: confirms every yes, may loop on no. **Decidable**: always halts with a definite yes/no. The gap is the possibility of an infinite loop — and \\(A_{TM}\\) lives exactly in that gap.",
    whyMatters: "This is the bedrock limit of what software can *guarantee* to check. Whole categories of \"does this program ever…?\" questions are recognizable-but-not-decidable, so no tool can answer them perfectly on every input.",
    realWorld: "There is **no** perfect program that decides whether an arbitrary program halts (the halting problem). That's why static analyzers, type checkers, antivirus, and verifiers must accept **false alarms or missed cases** — they're forced to approximate an undecidable question.",
    source: "Sipser Thm 4.11 (A_TM undecidable); 4.22"
  },

  /* ===================== Ch 5 — reductions ===================== */
  {
    id: "disc-ch5-reduction-no-harder", chapter: 5, topic: "Reducibility", type: "discussion", rank: 30,
    prompt: "**\"This is just that other problem in disguise.\"** That sentence is the single most powerful move in this whole course. Formally it's a **reduction** \\(A \\le_m B\\): a computable translator turning every \"is \\(w\\) in \\(A\\)?\" into an equivalent \"is \\(f(w)\\) in \\(B\\)?\". Let's get the logic — and the direction — exactly right.",
    steps: [
      { prompt: "If \\(A \\le_m B\\) (A translates into B) and **B is decidable**, what about A?", type: "mc",
        choices: ["A is decidable too — translate, then run B's decider", "A is undecidable", "Nothing follows"], answer: 0,
        explain: "**Easiness flows down** the reduction: a decider for the target B becomes a decider for the source A (translate the input with \\(f\\), then ask B). \\(A\\le_m B\\) means \"A is no harder than B.\"" },
      { prompt: "To prove **your** problem \\(P\\) is undecidable, which reduction do you build?", type: "mc",
        choices: ["Known-undecidable \\(\\le_m P\\)  (e.g. \\(A_{TM}\\le_m P\\))", "\\(P \\le_m\\) known-undecidable", "\\(P \\le_m\\) something decidable"], answer: 0,
        explain: "Reduce a **known monster INTO your problem**: \\(A_{TM}\\le_m P\\) says \"if you could decide \\(P\\), you could decide \\(A_{TM}\\)\" — impossible. The known-hard problem goes on the **left**." },
      { prompt: "True or false: \\(A \\le_m B\\) requires the translator \\(f\\) to be a one-to-one (injective) function.", type: "tf", answer: false,
        explain: "No — \\(f\\) just needs to be **computable** and **answer-preserving** (\\(w\\in A \\Leftrightarrow f(w)\\in B\\)). It can map many inputs to one output (\"many-one\"). Real reductions are usually very non-injective." }
    ],
    explanation: "A reduction \\(A\\le_m B\\) is a **pipe** that carries decidability/recognizability from B down to A. Direction is everything: to prove hardness, reduce a known-hard problem **into** yours.",
    whyMatters: "Reductions are how the entire map of \"what's solvable\" gets drawn — undecidability and NP-completeness are both proved by reduction. The same move (\"solve X by turning it into Y\") is also the everyday engineer's trick.",
    realWorld: "Industry **SAT/SMT solvers** and **linear-programming** packages are so good that people *reduce* scheduling, verification, and routing problems *to* them rather than writing new solvers. \"Express it as SAT\" is reduction in daily practice.",
    source: "Sipser 5.3 (mapping reducibility, Thm 5.22 / 5.28)"
  },

  /* ===================== Ch 7 — P vs NP ===================== */
  {
    id: "disc-ch7-p-vs-np-sudoku", chapter: 7, topic: "P vs NP", type: "discussion", rank: 30,
    prompt: "**Finishing a Sudoku is hard; checking a finished one is trivial.** That gap — *finding* a solution vs. *verifying* one — is the most famous open question in computer science. Let's build it from the ground up.",
    svg: '<svg viewBox="0 0 380 150" xmlns="http://www.w3.org/2000/svg" font-family="Georgia, \'Times New Roman\', serif"><rect x="8" y="8" width="364" height="134" rx="10" fill="none" stroke="var(--ink-soft)" stroke-width="1.5"/><text x="16" y="24" font-size="12" fill="var(--ink-soft)">EXPTIME</text><rect x="28" y="30" width="324" height="104" rx="9" fill="none" stroke="var(--ink-soft)" stroke-width="1.5"/><text x="36" y="46" font-size="12" fill="var(--ink-soft)">PSPACE</text><rect x="54" y="52" width="272" height="74" rx="8" fill="none" stroke="var(--brand)" stroke-width="1.5"/><text x="62" y="68" font-size="12" fill="var(--brand)">NP</text><rect x="84" y="74" width="212" height="44" rx="7" fill="var(--brand-soft)" stroke="var(--brand)" stroke-width="1.5"/><text x="190" y="101" text-anchor="middle" font-size="13" font-weight="700" fill="var(--brand)">P</text></svg>',
    steps: [
      { prompt: "Given a *completed* Sudoku grid, you can verify it's valid quickly (check rows, columns, boxes). \"Quick to **check** a proposed answer\" is the defining property of which class?", type: "mc",
        choices: ["NP", "P", "EXPTIME"], answer: 0,
        explain: "**NP** = problems where a proposed solution (a \"certificate\") can be **verified in polynomial time**. Sudoku, satisfying a formula, finding a route under budget — all easy to *check*." },
      { prompt: "**P** is the class of problems you can *solve* quickly from scratch. Why is it immediate that \\(P \\subseteq NP\\)?", type: "mc",
        choices: ["If you can solve it fast, you can check an answer fast (just solve it)", "Because P and NP are the same by definition", "It isn't — that containment is unknown"], answer: 0,
        explain: "Solving-fast trivially gives checking-fast: ignore the proposed answer, solve it yourself, compare. So \\(P\\subseteq NP\\) is **known**. The open question is whether the reverse holds." },
      { prompt: "The million-dollar question \"\\(P = NP\\)?\" is really asking…", type: "mc",
        choices: ["Is finding a solution as easy as checking one?", "Can computers solve any problem?", "Is NP bigger than PSPACE?"], answer: 0,
        explain: "Exactly: does every quickly-**checkable** problem also have a quickly-**findable** solution? Almost everyone believes **no** (\\(P\\ne NP\\)), but no one has proved it. \\(P\\subseteq NP\\subseteq PSPACE\\subseteq EXPTIME\\) (see the map)." }
    ],
    explanation: "**P** = solvable fast; **NP** = a given answer is *checkable* fast. \\(P\\subseteq NP\\) is known; whether they're equal is the famous open problem — is *finding* as easy as *checking*?",
    whyMatters: "If \\(P=NP\\), thousands of \"intractable\" optimization and search problems would suddenly become efficient — and most modern cryptography would collapse. The presumed gap \\(P\\ne NP\\) is what keeps your data safe.",
    realWorld: "**Public-key cryptography** (RSA, the lock on https) rests on certain problems being easy to *check* but hard to *solve*. Logistics, chip design, and protein folding are full of NP problems we attack only with heuristics — because no fast exact algorithm is known.",
    source: "Sipser 7.3–7.4 (P, NP, verifiers)"
  },

  /* ===================== Ch 7 — NP-completeness, the lever ===================== */
  {
    id: "disc-ch7-np-complete-lever", chapter: 7, topic: "NP-completeness", type: "discussion", rank: 35,
    prompt: "**There's a special club of \"hardest\" problems in NP** — the NP-complete ones — and they're all secretly the *same* problem. Crack one efficiently and you crack them all. Let's see how that lever works.",
    steps: [
      { prompt: "A problem \\(B\\) is **NP-complete** when it's in NP and *every* problem in NP reduces to it (in polynomial time). Cook–Levin proved the first such problem is…", type: "mc",
        choices: ["SAT (Boolean satisfiability)", "Sorting", "PATH (graph reachability)"], answer: 0,
        explain: "**SAT** was the first proven NP-complete problem (Cook–Levin). Every NP problem's verifier can be encoded as a Boolean formula, so all of NP funnels into SAT." },
      { prompt: "Suppose tomorrow someone finds a polynomial-time algorithm for **one** NP-complete problem. What happens?", type: "mc",
        choices: ["All of NP collapses into P — so \\(P = NP\\)", "Only that one problem becomes easy", "Nothing provable follows"], answer: 0,
        explain: "Because *every* NP problem reduces to it, a fast algorithm for one NP-complete problem solves them **all** fast — that would prove \\(P=NP\\). This is the lever: they stand or fall together." },
      { prompt: "To prove a *new* problem \\(X\\) is NP-complete, you show \\(X\\in NP\\) and then reduce a known NP-complete problem **to** \\(X\\). (Which direction is the hardness reduction?)", type: "mc",
        choices: ["known-NP-complete \\(\\le_p X\\)", "\\(X \\le_p\\) known-NP-complete", "Either direction works"], answer: 0,
        explain: "Same direction logic as undecidability: put the **known-hard** problem on the **left** (\\(\\text{3SAT}\\le_p X\\)) to show \\(X\\) is *at least as hard* as everything in NP." }
    ],
    explanation: "**NP-complete** = in NP, and everything in NP reduces to it. They're the hardest problems in NP and are all polynomial-time inter-reducible — one fast solution would mean \\(P=NP\\).",
    whyMatters: "NP-completeness is the working programmer's \"this is probably intractable\" stamp. Recognizing that your problem is NP-complete tells you to stop hunting for a perfect fast algorithm and reach for approximations or heuristics instead.",
    realWorld: "The **traveling salesman**, **scheduling**, **bin-packing**, and **circuit design** problems are NP-complete. Companies don't solve them exactly at scale — they use approximation algorithms, SAT solvers, and heuristics, precisely because of NP-completeness.",
    source: "Sipser 7.4–7.5 (Cook–Levin, NP-completeness)"
  },

  /* ===================== Ch 8 — chess vs tic-tac-toe (PSPACE vs EXPTIME) ===================== */
  {
    id: "disc-ch8-chess-vs-tictactoe", chapter: 8, topic: "PSPACE vs EXPTIME", type: "discussion", rank: 35,
    prompt: "**Why is chess \"harder\" than tic-tac-toe** — not just for humans, but in a precise, mathematical sense? Both are two-player games where you ask \"can the first player force a win?\" The answer is all about how *deep* the game tree gets.",
    svg: '<svg viewBox="0 0 480 210" xmlns="http://www.w3.org/2000/svg" font-family="Georgia, \'Times New Roman\', serif"><text x="130" y="18" text-anchor="middle" font-size="13" font-weight="700" fill="var(--ink)">Tic-Tac-Toe</text><text x="350" y="18" text-anchor="middle" font-size="13" font-weight="700" fill="var(--ink)">Chess (n×n)</text><g stroke="var(--ink-soft)" stroke-width="1.4"><line x1="130" y1="42" x2="95" y2="80"/><line x1="130" y1="42" x2="165" y2="80"/><line x1="95" y1="92" x2="72" y2="126"/><line x1="95" y1="92" x2="118" y2="126"/><line x1="165" y1="92" x2="142" y2="126"/><line x1="165" y1="92" x2="188" y2="126"/></g><g fill="var(--brand-soft)" stroke="var(--brand)" stroke-width="1.5"><circle cx="130" cy="36" r="8"/><circle cx="95" cy="86" r="8"/><circle cx="165" cy="86" r="8"/><circle cx="72" cy="132" r="8"/><circle cx="118" cy="132" r="8"/><circle cx="142" cy="132" r="8"/><circle cx="188" cy="132" r="8"/></g><text x="130" y="162" text-anchor="middle" font-size="11" fill="var(--ink-soft)">ends by move 9 — shallow</text><text x="130" y="180" text-anchor="middle" font-size="11.5" font-weight="700" fill="var(--good)">bounded depth → PSPACE</text><g stroke="var(--ink-soft)" stroke-width="1.4"><line x1="350" y1="42" x2="315" y2="80"/><line x1="350" y1="42" x2="385" y2="80"/><line x1="315" y1="92" x2="300" y2="126"/><line x1="315" y1="92" x2="338" y2="126"/><line x1="385" y1="92" x2="362" y2="126"/><line x1="385" y1="92" x2="408" y2="126"/></g><g stroke="var(--ink-soft)" stroke-width="1.4" stroke-dasharray="3 3"><line x1="300" y1="140" x2="300" y2="160"/><line x1="338" y1="140" x2="338" y2="160"/><line x1="362" y1="140" x2="362" y2="160"/><line x1="408" y1="140" x2="408" y2="160"/></g><g fill="var(--brand-soft)" stroke="var(--brand)" stroke-width="1.5"><circle cx="350" cy="36" r="8"/><circle cx="315" cy="86" r="8"/><circle cx="385" cy="86" r="8"/><circle cx="300" cy="132" r="8"/><circle cx="338" cy="132" r="8"/><circle cx="362" cy="132" r="8"/><circle cx="408" cy="132" r="8"/></g><text x="350" y="174" text-anchor="middle" font-size="14" fill="var(--ink-soft)">⋮ moves repeat</text><text x="350" y="192" text-anchor="middle" font-size="11.5" font-weight="700" fill="var(--bad)">unbounded depth → EXPTIME</text></svg>',
    steps: [
      { prompt: "Tic-tac-toe ends in at most 9 moves — every move fills a square and can't be undone. The game tree is **exponentially wide but only ~9 deep**. Why does shallow depth keep \"who wins?\" in **PSPACE**?", type: "mc",
        choices: ["You explore the huge tree depth-first, storing only one path at a time", "The tree has few nodes total", "Because tic-tac-toe always ends in a draw"], answer: 0,
        explain: "PSPACE's trick: walk the exponential game tree **depth-first**, holding only the current **root-to-leaf path** in memory. Path length = depth, so **poly depth → poly space** (even though the tree is enormous and it takes exp *time*)." },
      { prompt: "Chess moves are **reversible** — pieces shuffle back and forth, positions can repeat — so being 40 moves in tells you nothing about how much game is left. What does that do to the game tree's depth?", type: "mc",
        choices: ["Depth can be exponential (games run exponentially long)", "Depth stays small", "Depth becomes exactly 9"], answer: 0,
        explain: "With repetition, play can wander through exponentially many positions before ending. The path you must store is now **exponentially long** — so the shallow-stack PSPACE trick breaks." },
      { prompt: "So which classes do these two land in?", type: "mc",
        choices: ["Bounded games → PSPACE; unbounded (reversible) games → EXPTIME", "Both are PSPACE", "Both are in P"], answer: 0,
        explain: "Generalized games that **must end soon** (like \\(n\\times n\\) tic-tac-toe, or generalized geography) are **PSPACE**; games that can run **exponentially long** (generalized chess, checkers, Go) are **EXPTIME-complete** — provably harder. The deciding factor is whether every move makes irreversible progress." },
      { prompt: "True or false: \"who wins?\" for a bounded two-player game is captured by a quantified formula \\(\\exists(\\text{my move})\\,\\forall(\\text{your move})\\,\\exists\\cdots\\) being true — exactly the **TQBF** problem.", type: "tf", answer: true,
        explain: "Yes! The \\(\\exists\\) are *your* moves, the \\(\\forall\\) are the *opponent's*, and the formula is true iff you have a forced win. That's why **TQBF is PSPACE-complete** and why bounded games are the very picture of PSPACE." }
    ],
    explanation: "A bounded game (every move makes irreversible progress) has a **shallow** tree → solvable in **polynomial space** (depth-first, one path at a time) → **PSPACE**. A reversible game can run exponentially long → **exponentially deep** tree → **EXPTIME**. Depth, not size, is what you must hold in memory.",
    whyMatters: "This is the precise reason \"solve this game perfectly\" ranges from merely-hard to astronomically-hard, and it's the same depth-vs-memory idea behind why TQBF sits at the center of PSPACE.",
    realWorld: "Generalized **chess, checkers, and Go** are EXPTIME-complete — provably beyond efficient exact solution — which is exactly why world-class engines (and AlphaZero) rely on **search + learned heuristics** rather than solving the game outright.",
    source: "Sipser 8.3 (TQBF, GG); Fraenkel–Lichtenstein (n×n chess is EXPTIME-complete)"
  }

]);
