/* Chapter 2 — Context-Free Languages: extra distractors (each unambiguously
   WRONG for its question). Keyed by question id. The app samples a varying
   subset of wrong options each render so you can't answer by position or
   remembered shape. mc → 3–5 extra; multi → 2–4 extra. */
TOC.addPools({
  // ---- CFG formal definition ----
  "ch2-cfg-4tuple": [
    "the start variable",
    "a string of variables and terminals called the yield",
    "the stack alphabet",
    "a mapping from each variable to a single terminal"
  ],
  "ch2-cfg-language-def": [
    "\\(\\{w\\in(V\\cup\\Sigma)^*\\mid S\\stackrel{*}{\\Rightarrow}w\\}\\)",
    "\\(\\{w\\in\\Sigma^*\\mid w\\Rightarrow S\\}\\)",
    "the set of all strings derivable from any variable in \\(V\\)",
    "\\(\\{w\\in V^*\\mid S\\stackrel{*}{\\Rightarrow}w\\}\\)"
  ],

  // ---- Derivations, leftmost derivations, parse trees, yield ----
  "ch2-leftmost-derivation": [
    "at every step the rightmost remaining variable is the one replaced",
    "every variable is replaced at most once",
    "each step replaces every variable currently in the string",
    "the derivation uses the fewest possible steps"
  ],
  "ch2-derivation-multi": [
    "Every string in \\(L(G)\\) has a unique parse tree",
    "\\(uAv\\Rightarrow uwv\\) requires \\(w\\) to be a string of terminals",
    "Reordering the rules within the grammar changes \\(L(G)\\)"
  ],

  // ---- Designing CFGs ----
  "ch2-design-anbn": [
    "\\(S\\to 0S\\mid 1S\\mid\\varepsilon\\)",
    "\\(S\\to 00S11\\mid\\varepsilon\\)",
    "\\(S\\to 0S1\\mid 1S0\\mid\\varepsilon\\)",
    "\\(S\\to SS\\mid 01\\mid\\varepsilon\\)"
  ],
  "ch2-design-union": [
    "an \\(\\varepsilon\\)-rule \\(S_1\\to\\varepsilon\\) and \\(S_2\\to\\varepsilon\\)",
    "a new start variable \\(S\\) with the rule \\(S\\to S_1 S_2\\)",
    "a new start variable \\(S\\) with the rule \\(S\\to S_1\\$S_2\\)",
    "the rule \\(S_2\\to S_1\\)"
  ],
  "ch2-design-dfa-to-cfg-multi": [
    "\\(R_i\\to a\\) whenever \\(\\delta(q_i,a)\\) is an accept state",
    "the start variable is \\(R_j\\) for any accept state \\(q_j\\)",
    "\\(R_i\\to\\varepsilon\\) for the start state \\(q_0\\)"
  ],

  // ---- Regular vs context-free ----
  "ch2-regular-cfl-proper": [
    "every context-free language is regular, but not conversely",
    "the regular and context-free languages partition \\(\\Sigma^*\\)",
    "the context-free languages are a proper subset of the finite languages"
  ],
  "ch2-regular-cfl-why-multi": [
    "Every PDA can be converted into an equivalent finite automaton",
    "\\(\\{0^n1^n\\mid n\\ge 0\\}\\) is regular but not context-free",
    "The pumping lemma for regular languages also applies, unchanged, to every CFL"
  ],

  // ---- Ambiguity ----
  "ch2-ambiguous-def": [
    "some string has two or more different rightmost derivations that yield the same parse tree",
    "the grammar contains a unit rule \\(A\\to B\\)",
    "two different strings share the same parse tree",
    "the grammar is left-recursive"
  ],
  "ch2-inherently-ambiguous": [
    "some string in it has exactly one parse tree",
    "it is generated by a grammar that is not in Chomsky normal form",
    "it is context-free but not deterministic context-free",
    "no pushdown automaton recognizes it"
  ],

  // ---- Chomsky normal form ----
  "ch2-cnf-rule-forms": [
    "\\(A\\to a\\) and \\(A\\to Ba\\) only",
    "\\(A\\to BC\\), \\(A\\to a\\), and unit rules \\(A\\to B\\)",
    "\\(A\\to aBc\\) where the middle symbol is a variable",
    "\\(A\\to BCD\\) and \\(A\\to a\\)"
  ],

  // ---- Pushdown automata ----
  "ch2-pda-6tuple": [
    "the bottom-of-stack marker",
    "the set of all stack configurations",
    "the start state",
    "the set of variables"
  ],
  "ch2-pda-transition-type": [
    "\\(\\delta:Q\\times\\Sigma_\\varepsilon\\times\\Gamma_\\varepsilon\\to Q\\times\\Gamma_\\varepsilon\\)",
    "\\(\\delta:Q\\times\\Sigma\\times\\Gamma\\to\\mathcal{P}(Q)\\)",
    "\\(\\delta:Q\\times\\Sigma_\\varepsilon\\to\\mathcal{P}(Q\\times\\Gamma)\\)",
    "\\(\\delta:Q\\times\\Gamma_\\varepsilon\\to\\mathcal{P}(Q\\times\\Sigma_\\varepsilon)\\)"
  ],
  "ch2-pda-accept-multi": [
    "A PDA accepts only by emptying its stack, never by entering an accept state",
    "A PDA can read or overwrite a symbol at an arbitrary depth in its stack",
    "Determinism makes a PDA recognize strictly more languages than nondeterminism"
  ],

  // ---- CFG/PDA equivalence ----
  "ch2-pda-to-cfg-variables": [
    "all strings that take \\(P\\) from \\(p\\) to \\(q\\) while leaving the stack nonempty throughout",
    "all strings that take \\(P\\) from the start state to \\(q\\) with empty stack",
    "all strings of stack symbols pushed by \\(P\\) between \\(p\\) and \\(q\\)",
    "all strings that take \\(P\\) from \\(p\\) (empty stack) to \\(q\\) with the marker \\(\\$\\) still on the stack"
  ],

  // ---- Pumping lemma for CFLs ----
  "ch2-pl-conditions": [
    "\\(|vxy|\\ge p\\)",
    "\\(v=y\\)",
    "\\(uv^ixy^iz\\in A\\) for exactly one value of \\(i\\)",
    "\\(x=\\varepsilon\\)"
  ],
  "ch2-pl-anbncn-string": [
    "\\(s=c^pb^pa^p\\); pumping reverses the order of the blocks",
    "\\(s=a^pb^pc^p\\); since \\(|vxy|\\ge p\\), the window \\(vxy\\) must cover all three blocks at once",
    "\\(s=b^pc^p\\); pumping changes only the number of \\(b\\)s",
    "\\(s=a^pb^p\\); the substring \\(vxy\\) lands entirely in the \\(a\\) block"
  ],
  "ch2-pl-ww-string": [
    "\\(s=0^p1^{2p}0^p\\)",
    "\\(s=1^p0^p\\)",
    "\\(s=0^p1^p0^p\\)",
    "\\(s=(0011)^p\\)"
  ],

  // ---- Closure properties ----
  "ch2-closure-union-concat-star-multi": [
    "Complementation",
    "Intersection with another context-free language",
    "Set difference \\(A\\setminus B\\) of two CFLs"
  ],
  "ch2-closure-why-not-complement-mc": [
    "CFLs must be closed under complement, since they are closed under union",
    "CFLs are closed under complement because they are closed under intersection with a regular language",
    "Complement closure follows directly from closure under star",
    "Complement closure is equivalent to closure under concatenation"
  ],

  // ---- Deterministic CFLs / DPDAs ----
  "ch2-dpda-determinism-mc": [
    "at least one of \\(\\delta(q,a,x),\\ \\delta(q,a,\\varepsilon),\\ \\delta(q,\\varepsilon,x),\\ \\delta(q,\\varepsilon,\\varepsilon)\\) is non-empty",
    "\\(\\delta(q,a,\\varepsilon)\\) is empty for every \\(q\\) and \\(a\\)",
    "\\(\\delta(q,a,x)\\) maps to a set of at most two (state, push) pairs",
    "the stack alphabet equals the input alphabet"
  ]
});

TOC.addPools({
  "ch2-concept-cfg-what": [
    "A machine with a stack that recognizes strings",
    "A regular expression extended with a complementation operator",
    "A finite list of all the strings in the language"
  ],
  "ch2-concept-pda-what": [
    "A deterministic finite automaton with two stacks",
    "A finite automaton whose memory is a queue instead of a stack",
    "A context-free grammar written in Chomsky normal form"
  ],
  "ch2-concept-cfl-what": [
    "A language recognized by some linear bounded automaton",
    "Any language that is not regular",
    "A language closed under complement"
  ],
  "ch2-gen-0n1n": [
    "\\(\\{0^n 1^{2n} \\mid n\\ge 0\\}\\)",
    "\\(\\{w \\mid w\\text{ has equally many }0\\text{s and }1\\text{s}\\}\\)",
    "\\(\\{1^n 0^n \\mid n\\ge 0\\}\\)"
  ],
  "ch2-gen-balanced": [
    "\\(\\{\\,(^n)^m \\mid n,m\\ge 0\\,\\}\\)",
    "strings with equally many \\((\\) and \\()\\) in any order",
    "all nonempty strings of parentheses"
  ],
  "ch2-gen-palindromes": [
    "even-length strings only",
    "\\(\\{ww^{R} \\mid w\\in\\{0,1\\}^*\\}\\)",
    "strings containing at least one \\(0\\) and at least one \\(1\\)"
  ]
});
