/* Chapter 0 — deeper concept explainers. Keyed "0::<topic>" to match question topics. */
TOC.addConcepts({
  "0::Sets": {
    title: "Sets",
    body: "**What it is.** A set is an unordered collection of distinct objects. Order and repetition don't matter: \\(\\{1,2\\}=\\{2,1\\}=\\{1,1,2\\}\\). Membership is the only question a set answers: is \\(x\\in A\\) or not.\n\n**Key operations.** Union \\(A\\cup B\\) (in either), intersection \\(A\\cap B\\) (in both), difference \\(A\\setminus B\\), complement \\(\\overline{A}\\) (everything in the universe not in \\(A\\)). Subset: \\(A\\subseteq B\\) means every element of \\(A\\) is in \\(B\\) — this is NOT symmetric.\n\n**Power set.** \\(\\mathcal{P}(A)\\) is the set of all subsets of \\(A\\). If \\(|A|=n\\) then \\(|\\mathcal{P}(A)|=2^n\\), because each element is independently in or out of a given subset.\n\n**Pitfalls.** \\(\\emptyset\\) (empty set) is a subset of every set, vacuously. Don't confuse \\(\\in\\) (element of) with \\(\\subseteq\\) (subset of): \\(1\\in\\{1,2\\}\\) but \\(\\{1\\}\\subseteq\\{1,2\\}\\)."
  },
  "0::Sequences & tuples": {
    title: "Sequences and tuples",
    body: "**What it is.** A sequence is an ordered list; a finite sequence is a tuple. Unlike sets, **order matters and repetition is allowed**: \\((1,2)\\neq(2,1)\\), and \\((1,1,2)\\) is a perfectly good 3-tuple.\n\n**Cartesian product.** \\(A\\times B=\\{(a,b)\\mid a\\in A,\\ b\\in B\\}\\) — all ordered pairs with first coordinate from \\(A\\), second from \\(B\\). Its size is \\(|A|\\cdot|B|\\). More generally \\(A^k=A\\times A\\times\\cdots\\times A\\) (\\(k\\) times) is the set of \\(k\\)-tuples over \\(A\\).\n\n**Why it matters here.** Transition functions of automata are defined on Cartesian products, e.g. a DFA's \\(\\delta:Q\\times\\Sigma\\to Q\\) takes a (state, symbol) pair."
  },
  "0::Functions & relations": {
    title: "Functions and relations",
    body: "**Function.** \\(f:A\\to B\\) assigns to each \\(a\\in A\\) exactly one \\(f(a)\\in B\\). \\(A\\) is the domain, \\(B\\) the codomain, and the range is the set of values actually hit (range \\(\\subseteq B\\)).\n\n**Special kinds.** *Injective* (one-to-one): distinct inputs give distinct outputs. *Surjective* (onto): every element of \\(B\\) is some \\(f(a)\\) — i.e. range \\(=B\\). *Bijective*: both; this is exactly when a two-way correspondence exists (used to define equal cardinality).\n\n**Relations.** A binary relation \\(R\\) on \\(A\\) is a subset of \\(A\\times A\\). An **equivalence relation** is reflexive (\\(aRa\\)), symmetric (\\(aRb\\Rightarrow bRa\\)), and transitive (\\(aRb\\wedge bRc\\Rightarrow aRc\\)); it partitions \\(A\\) into equivalence classes.\n\n**Pitfall.** \"Onto\" is about the codomain being fully covered; \"one-to-one\" is about no collisions. They are independent properties."
  },
  "0::Graphs": {
    title: "Graphs",
    body: "**What it is.** A graph \\(G=(V,E)\\) is a set of nodes (vertices) \\(V\\) and edges \\(E\\). In an *undirected* graph edges are unordered pairs; in a *directed* graph (digraph) they are ordered (arrows).\n\n**Degree.** The degree of a node is the number of edges touching it (a self-loop counts 2). **Handshaking lemma:** \\(\\sum_{v} \\deg(v)=2|E|\\), since each edge contributes to two endpoints — so the number of odd-degree nodes is even.\n\n**Useful shapes.** A *path* is a sequence of nodes connected by edges; a *cycle* is a path returning to its start; *connected* means a path exists between every pair. A **tree** is a connected acyclic graph and has exactly \\(|V|-1\\) edges.\n\n**Why it matters here.** Graph reachability (PATH) is the canonical example in P / NL, and graph problems (CLIQUE, VERTEX-COVER, HAMPATH) drive the NP-completeness theory."
  },
  "0::Strings & languages": {
    title: "Strings and languages",
    body: "**Alphabet & strings.** An alphabet \\(\\Sigma\\) is a finite set of symbols. A string over \\(\\Sigma\\) is a finite sequence of its symbols; \\(|w|\\) is its length. The empty string is \\(\\varepsilon\\), with \\(|\\varepsilon|=0\\).\n\n**Star.** \\(\\Sigma^*\\) is the set of ALL finite strings over \\(\\Sigma\\), including \\(\\varepsilon\\). (\\(\\Sigma^+\\) is the same but excludes \\(\\varepsilon\\).) Over a binary alphabet there are exactly \\(2^n\\) strings of length \\(n\\).\n\n**Language.** A language is any set of strings: \\(L\\subseteq\\Sigma^*\\). It may be finite or infinite; \\(\\emptyset\\) and \\(\\Sigma^*\\) are both languages. Everything in this course — regular, context-free, decidable — is a way of describing certain languages.\n\n**Operations.** Concatenation \\(xy\\), and on languages: union, concatenation \\(AB=\\{xy\\mid x\\in A, y\\in B\\}\\), and star \\(A^*\\) (zero or more pieces from \\(A\\), so \\(\\varepsilon\\in A^*\\) always)."
  },
  "0::Boolean logic": {
    title: "Boolean logic",
    body: "**Connectives.** \\(\\wedge\\) (and), \\(\\vee\\) (or), \\(\\neg\\) (not), \\(\\oplus\\) (xor, true when operands differ), \\(\\Rightarrow\\) (implies), \\(\\Leftrightarrow\\) (iff).\n\n**Implication.** \\(P\\Rightarrow Q\\) is false ONLY when \\(P\\) is true and \\(Q\\) is false; whenever \\(P\\) is false it is vacuously true. Equivalently \\(P\\Rightarrow Q \\equiv \\neg P\\vee Q\\).\n\n**De Morgan's laws.** \\(\\overline{P\\wedge Q}=\\overline{P}\\vee\\overline{Q}\\) and \\(\\overline{P\\vee Q}=\\overline{P}\\wedge\\overline{Q}\\): pushing a negation inward flips the connective.\n\n**Why it matters here.** Boolean formulas are the objects of SAT / 3SAT (the first NP-complete problems) and of TQBF (PSPACE-complete); the Cook–Levin tableau is built entirely from these connectives."
  },
  "0::Proof techniques": {
    title: "Proof techniques",
    body: "**By construction.** To prove something exists, build it (or give a procedure that builds it) — e.g. exhibit a DFA recognizing a language.\n\n**By contradiction.** Assume the statement is false, then derive an impossibility. The pumping-lemma non-regularity proofs and the diagonalization that \\(A_{TM}\\) is undecidable are both contradictions.\n\n**By induction.** To prove \\(P(n)\\) for all \\(n\\): prove a base case \\(P(0)\\) (or \\(P(1)\\)); assume \\(P(k)\\) (the inductive hypothesis); prove \\(P(k+1)\\); conclude for all \\(n\\). Ideal for statements quantified over the naturals.\n\n**Pigeonhole.** If \\(n\\) items go into \\(m<n\\) boxes, some box gets \\(\\ge 2\\). This underlies \"a long enough run must repeat a state,\" which is exactly the engine of both pumping lemmas.\n\n**Tip.** Match the technique to the statement's shape: \"for all \\(n\\)\" → induction; \"there is no…\" → contradiction; \"there exists…\" → construction."
  }
});
