/* Chapter 1 — Regular Languages (Sipser 1.1–1.4): deeper concept explainers.
   Keyed "1::<topic>" to match the topics used by js/questions/ch1.js. */
TOC.addConcepts({
  "1::DFA definition": {
    title: "DFA: the formal 5-tuple",
    body: "**What it is.** A deterministic finite automaton is a 5-tuple \\((Q,\\Sigma,\\delta,q_0,F)\\): a finite set of states \\(Q\\), an input alphabet \\(\\Sigma\\), a transition function \\(\\delta:Q\\times\\Sigma\\to Q\\), a start state \\(q_0\\in Q\\), and a set of accept states \\(F\\subseteq Q\\) (Def 1.5).\n\n**Why \"deterministic.\"** Because \\(\\delta\\) is a total function, every state has exactly one outgoing arrow for each symbol of \\(\\Sigma\\) — never zero, never two, and never an \\(\\varepsilon\\)-arrow. Given a state and a symbol, the next state is forced, so the entire run on a string is uniquely determined.\n\n**Pitfall.** Order the components correctly and keep the set inclusions straight: \\(q_0\\) is a single state (\\(q_0\\in Q\\)) while \\(F\\) is a SET of states (\\(F\\subseteq Q\\)). \\(F\\) may be empty (the machine accepts nothing) or all of \\(Q\\) (it accepts everything in \\(\\Sigma^*\\)).\n\n**Example.** Over \\(\\Sigma=\\{0,1\\}\\), \\(Q=\\{q_0,q_1\\}\\), \\(F=\\{q_1\\}\\), with \\(\\delta\\) sending you to \\(q_1\\) on \\(1\\) and back to \\(q_0\\) on \\(0\\), recognizes strings ending in \\(1\\)."
  },
  "1::DFA": {
    title: "DFA: signature and acceptance",
    body: "**Signature.** The transition function of a DFA has type \\(\\delta:Q\\times\\Sigma\\to Q\\): a (state, input symbol) pair maps to exactly one next state. This is the form to recognize on sight — the powerset form \\(Q\\times\\Sigma_\\varepsilon\\to\\mathcal{P}(Q)\\) is an NFA, and \\(Q\\times\\Gamma\\to Q\\times\\{L,R\\}\\) is a Turing machine.\n\n**Acceptance.** \\(M\\) accepts \\(w=w_1\\cdots w_n\\) iff there is a sequence of states \\(r_0,\\dots,r_n\\) with \\(r_0=q_0\\), \\(r_{i+1}=\\delta(r_i,w_{i+1})\\) for each \\(i\\), and \\(r_n\\in F\\). Only the FINAL state matters; passing through an accept state midway does not count.\n\n**Pitfall.** Determinism plus totality means there are no missing edges and no choices. If a diagram seems to leave a symbol undefined at some state, a hidden \"dead\" (trap) state is implied to keep \\(\\delta\\) total.\n\n**Why it matters.** The language \\(L(M)=\\{w\\mid M\\text{ accepts }w\\}\\) of a DFA is exactly a regular language (Def 1.16), so DFAs are one of the standard yardsticks for regularity."
  },
  "1::DFA computation": {
    title: "How a DFA computes",
    body: "**What it is.** Computation is the deterministic walk a DFA takes through its states while reading the input left to right. Formally \\(M\\) accepts \\(w=w_1\\cdots w_n\\) when states \\(r_0,\\dots,r_n\\) exist with \\(r_0=q_0\\), \\(\\delta(r_i,w_{i+1})=r_{i+1}\\), and \\(r_n\\in F\\) (§1.1).\n\n**Key facts.** Three conditions matter: start in \\(q_0\\), follow \\(\\delta\\) at every step, and end in \\(F\\). Intermediate states are unrestricted — the machine may pass through non-accepting and accepting states freely; only \\(r_n\\) is tested. The empty string \\(\\varepsilon\\) is accepted iff \\(q_0\\in F\\), since the machine reads nothing and stays put.\n\n**Pitfall.** \"Visited an accept state at some point\" is NOT acceptance for a DFA; acceptance is decided solely by the state reached after the last symbol.\n\n**Example.** A parity DFA for \"even number of \\(1\\)s\" toggles between \\(q_{\\text{even}}\\) and \\(q_{\\text{odd}}\\) on each \\(1\\); on \\(0110\\) it ends back at \\(q_{\\text{even}}\\in F\\), so it accepts."
  },
  "1::Designing DFAs": {
    title: "Designing DFAs",
    body: "**The core idea.** Ask: what is the minimal finite amount of information I must remember about the input so far to decide acceptance? Each distinct answer becomes one state. Because a DFA has finite memory, this only works when finitely many \"situations\" suffice.\n\n**Common patterns.** For \"contains pattern \\(P\\) as a substring,\" track how much of \\(P\\) you have matched so far (a prefix-matching automaton). For \"ends in \\(P\\)\" or \"divisible by \\(k\\),\" remember the relevant suffix or the running remainder mod \\(k\\).\n\n**Pitfall.** Do not try to remember the whole input or an unbounded count — that needs infinitely many states and signals a likely nonregular language. Keep the state set finite and make sure \\(\\delta\\) is defined for every state/symbol pair.\n\n**Example.** For \\(\\{w\\mid w\\text{ contains }001\\}\\), the states are \"seen nothing,\" \"seen \\(0\\),\" \"seen \\(00\\),\" and \"seen \\(001\\)\" (an accepting trap) — four states tracking progress through the pattern (Ex 1.21)."
  },
  "1::Regular languages": {
    title: "Regular languages",
    body: "**Definition.** A language \\(A\\) is regular iff some finite automaton recognizes it: \\(A=L(M)\\) for a DFA (equivalently an NFA) \\(M\\) (Def 1.16). \"Recognizes\" means \\(M\\) accepts exactly the strings in \\(A\\) and rejects all others.\n\n**Equivalent characterizations.** By Kleene's theorem the regular languages are exactly the languages describable by a regular expression (Thm 1.54), and by NFA/DFA equivalence it makes no difference whether you use a deterministic or nondeterministic machine (Thm 1.39). So \"recognized by a DFA,\" \"recognized by an NFA,\" and \"described by a regular expression\" all define the same class.\n\n**Pitfall.** Regularity is about the existence of SOME finite automaton; a clumsy machine failing is no evidence. To prove a language nonregular you need the pumping lemma or a closure argument, not just \"I couldn't build a DFA.\"\n\n**Example.** \\(\\{w\\mid w\\text{ ends in }01\\}\\) is regular (a small DFA works), whereas \\(\\{0^n1^n\\mid n\\ge0\\}\\) is not."
  },
  "1::NFA definition": {
    title: "NFA: the formal definition",
    body: "**What it is.** A nondeterministic finite automaton is a 5-tuple \\((Q,\\Sigma,\\delta,q_0,F)\\) where the transition function has type \\(\\delta:Q\\times\\Sigma_\\varepsilon\\to\\mathcal{P}(Q)\\), with \\(\\Sigma_\\varepsilon=\\Sigma\\cup\\{\\varepsilon\\}\\) (Def 1.37). It returns a SET of next states, and the value \\(\\emptyset\\) means \"no available move.\"\n\n**What nondeterminism adds.** A state may have zero, one, or several arrows for the same symbol, and may have \\(\\varepsilon\\)-arrows that change state without consuming input — all three are forbidden in a DFA. Having multiple accept states is NOT special; DFAs allow that too.\n\n**Why the powerset codomain.** \\(\\mathcal{P}(Q)\\) is exactly what lets one \"input\" yield many possible outcomes, capturing the branching of nondeterministic computation.\n\n**Pitfall.** A missing arrow in an NFA is fine (that branch just dies); the machine still accepts if some OTHER branch succeeds. Do not \"complete\" an NFA the way you would a DFA."
  },
  "1::NFA": {
    title: "NFA: signature and acceptance",
    body: "**Signature.** An NFA's transition function is \\(\\delta:Q\\times\\Sigma_\\varepsilon\\to\\mathcal{P}(Q)\\), where \\(\\Sigma_\\varepsilon=\\Sigma\\cup\\{\\varepsilon\\}\\) (Def 1.37). The powerset codomain encodes \"zero, one, or many\" next states, and the \\(\\varepsilon\\) entry allows spontaneous moves.\n\n**Acceptance is existential.** \\(N\\) accepts \\(w\\) iff AT LEAST ONE branch of its computation ends in an accept state. Picture the run as a tree of possibilities; one accepting leaf suffices, and \\(w\\) is rejected only when every branch fails. (Requiring all branches to accept is a different model, the all-NFA of Problem 1.38.)\n\n**Relation to DFAs.** Every DFA is already an NFA (each \\(\\delta(q,a)\\) is a singleton and there are no \\(\\varepsilon\\)-moves), so NFAs are at least as expressive — and by the subset construction no more so.\n\n**Pitfall.** \"Some branch accepts\" — not a majority, not all. Think of nondeterminism as lucky guessing that always works out when any successful path exists."
  },
  "1::NFA computation": {
    title: "How an NFA computes",
    body: "**What it is.** On each symbol an NFA may follow several arrows at once and may take \\(\\varepsilon\\)-moves for free, so its computation is a tree (or a set of simultaneously live states) rather than a single path.\n\n**Acceptance.** The criterion is existential: the input is accepted iff SOME branch is in an accept state when the input is exhausted (Def 1.37). Equivalently, track the set of all states reachable so far; accept iff that set finally contains an accept state. This \"set of live states\" view is precisely what the subset construction makes deterministic.\n\n**Pitfall.** Do not require every branch to accept, and do not stop at the first accept state mid-string — only the configuration after the LAST symbol is tested. A dead branch (no available arrow) simply drops out and never causes rejection on its own.\n\n**Example.** An NFA guessing \"a \\(1\\) sits three from the end\" keeps branches alive for each candidate position; whichever guess is right yields the accepting branch."
  },
  "1::NFA examples": {
    title: "NFAs and succinctness",
    body: "**Why use NFAs.** Nondeterminism lets a machine \"guess\" and verify later, often yielding far smaller or clearer machines than the equivalent DFA. A classic case is \\(A=\\{w\\in\\{0,1\\}^*\\mid w\\text{ has a }1\\text{ in the third position from the end}\\}\\).\n\n**The succinctness gap.** A 4-state NFA recognizes \\(A\\) by guessing where the third-from-last symbol is and checking the remaining two. But the smallest DFA must remember the last three symbols seen, so it needs \\(2^3=8\\) states (Ex 1.30). More generally, \"a \\(1\\) in the \\(k\\)-th position from the end\" gives a \\((k{+}1)\\)-state NFA but forces \\(2^k\\) DFA states.\n\n**Pitfall.** This is a size difference, not a power difference: by Thm 1.39 the NFA and DFA recognize the SAME language. Nondeterminism buys conciseness, never new languages, for finite automata.\n\n**Example.** For \\(A\\) above, the NFA stays in a start loop, then nondeterministically commits and reads two more symbols to reach an accept state."
  },
  "1::NFA vs DFA power": {
    title: "NFAs and DFAs have equal power",
    body: "**The fact.** NFAs and DFAs recognize exactly the same class of languages — the regular languages. Every NFA has an equivalent DFA (Thm 1.39), and every DFA is trivially an NFA, so neither model can recognize anything the other cannot.\n\n**Why.** The subset construction simulates an NFA deterministically by letting a DFA state be the SET of NFA states currently reachable. Tracking all branches at once removes the need to \"guess,\" converting existential acceptance into an ordinary deterministic run.\n\n**Pitfall.** A very common misconception is that nondeterminism adds power for finite automata. It does not — it only adds convenience and succinctness (an NFA can be exponentially smaller). The power/convenience distinction is exactly what separates this from the open P vs NP question for Turing machines.\n\n**Example.** The NFA for \"third symbol from the end is \\(1\\)\" has \\(4\\) states; its equivalent DFA needs \\(2^3=8\\). Same language, different size."
  },
  "1::Subset construction": {
    title: "Subset (powerset) construction",
    body: "**What it does.** It converts an NFA \\(N=(Q,\\Sigma,\\delta,q_0,F)\\) into an equivalent DFA \\(M\\) whose states are the SUBSETS of \\(Q\\); each DFA state records exactly which NFA states are currently reachable (Thm 1.39). Hence \\(M\\) has up to \\(2^{|Q|}\\) states.\n\n**The recipe.** Take states \\(\\mathcal{P}(Q)\\); start state \\(E(\\{q_0\\})\\), the \\(\\varepsilon\\)-closure of \\(q_0\\); transition \\(\\delta'(R,a)=\\{\\,q\\mid q\\in E(\\delta(r,a))\\text{ for some }r\\in R\\,\\}\\) (follow \\(a\\) from every state in \\(R\\), then close under \\(\\varepsilon\\)); and accept any subset \\(R\\) that contains an accept state of \\(N\\).\n\n**Pitfall.** Do not forget the \\(\\varepsilon\\)-closure \\(E(\\cdot)\\) at the start and after each symbol; omitting it gives a wrong DFA. Note the empty set \\(\\emptyset\\) is a legitimate (dead) DFA state.\n\n**Worst case.** The \\(2^{|Q|}\\) blow-up is unavoidable for some languages (e.g. \"a \\(1\\) in the \\(k\\)-th position from the end\"), so you cannot always do better (Problem 1.61)."
  },
  "1::Regular operations": {
    title: "The regular operations",
    body: "**Definition.** Sipser singles out three operations on languages as the \"regular operations\" (Def 1.23): union \\(A\\cup B=\\{x\\mid x\\in A\\text{ or }x\\in B\\}\\), concatenation \\(A\\circ B=\\{xy\\mid x\\in A\\text{ and }y\\in B\\}\\), and star \\(A^*=\\{x_1\\cdots x_k\\mid k\\ge0,\\ x_i\\in A\\}\\).\n\n**Key facts.** These three are exactly the operations used to build regular expressions, and the regular languages are closed under all of them (Thm 1.25, 1.45, 1.47). Star always includes \\(\\varepsilon\\) (the \\(k=0\\) case), so \\(\\varepsilon\\in A^*\\) for every \\(A\\).\n\n**Pitfall.** Intersection and complement are NOT on this list, even though the regular languages happen to be closed under them as well. And do not confuse \\(A\\circ B\\) (one piece from each) with \\(A^*\\) (any number of pieces from \\(A\\)).\n\n**Example.** With \\(A=\\{a\\}\\), \\(B=\\{b\\}\\): \\(A\\cup B=\\{a,b\\}\\), \\(A\\circ B=\\{ab\\}\\), and \\(A^*=\\{\\varepsilon,a,aa,\\dots\\}\\)."
  },
  "1::Closure properties": {
    title: "Closure properties of regular languages",
    body: "**What it means.** A class is \"closed\" under an operation if applying that operation to members yields a member. The regular languages are closed under union, concatenation, and star (Thm 1.25, 1.45–1.47), and also under intersection, complement, and reverse (Thm 1.25 footnote; Prob 1.31, Ex 1.14).\n\n**How they are proved.** Union/concatenation/star are easiest via NFAs: e.g. for union, add a fresh start state with \\(\\varepsilon\\)-arrows to the two machines (Thm 1.45). Intersection uses the PRODUCT construction — run both DFAs on state pairs \\((r_1,r_2)\\) and accept when both accept, i.e. \\(F=F_1\\times F_2\\). Complement is just swapping accept and non-accept states OF A DFA.\n\n**Pitfall.** Swapping accept/non-accept states works for DFAs but NOT for NFAs: a string can have both an accepting and a rejecting branch, so the swap may still accept it (Ex 1.14b). Complement closure must be argued on a DFA.\n\n**Example.** \\(F=F_1\\times F_2\\) gives \\(A_1\\cap A_2\\); choosing accept when EITHER accepts would instead give \\(A_1\\cup A_2\\)."
  },
  "1::Regular expressions": {
    title: "Regular expressions",
    body: "**Definition.** A regular expression over \\(\\Sigma\\) is built inductively (Def 1.52). The atomic (base) cases are a single symbol \\(a\\in\\Sigma\\), the empty string \\(\\varepsilon\\), and the empty language \\(\\emptyset\\); compound expressions are formed by union \\(R_1\\cup R_2\\), concatenation \\(R_1\\circ R_2\\), and star \\(R_1^*\\). Note \\(\\Sigma^*\\) is a COMPOUND expression, not a base case.\n\n**Precedence.** Absent parentheses, star binds tightest, then concatenation, then union. So \\(0\\cup10^*\\) parses as \\(0\\cup(1(0^*))\\), not \\((0\\cup1)0^*\\).\n\n**Key distinctions and identities.** \\(\\varepsilon\\) and \\(\\emptyset\\) are different: \\(L(\\varepsilon)=\\{\\varepsilon\\}\\) (one string) while \\(L(\\emptyset)=\\{\\}\\) (no strings). Hence \\(R\\cup\\emptyset=R\\) and \\(R\\circ\\varepsilon=R\\), but \\(R\\circ\\emptyset=\\emptyset\\) (concatenating with the empty language annihilates). Also \\(\\emptyset^*=\\{\\varepsilon\\}\\), since star can take zero pieces.\n\n**Example.** Over \\(\\{0,1\\}\\), \\(0^*10^*\\) describes strings with exactly one \\(1\\); \"at least one \\(1\\)\" would be \\(\\Sigma^*1\\Sigma^*\\)."
  },
  "1::RE/FA equivalence": {
    title: "Regular expressions = finite automata",
    body: "**The theorem.** A language is regular iff some regular expression describes it (Thm 1.54, Kleene's theorem). The two formalisms have exactly the same descriptive power, so you may freely switch between a machine and an expression.\n\n**Both directions.** RE \\(\\to\\) NFA: build an NFA inductively from the regex, one small gadget per operation (Lemma 1.55). FA \\(\\to\\) RE: convert the DFA into a GNFA and rip out internal states one at a time until only a start and accept state remain; the surviving arrow's label is the regular expression (Lemma 1.60).\n\n**Pitfall.** \"A regular expression exists\" is itself a proof of regularity — you need not exhibit a DFA. Conversely, building a DFA proves a regular expression exists, even if writing one out looks hard.\n\n**Example.** From the regex \\((0\\cup1)^*1\\) you can mechanically build an NFA; from a DFA for \"ends in \\(1\\)\" you can rip states down to recover such an expression."
  },
  "1::GNFA": {
    title: "GNFAs and DFA-to-RE conversion",
    body: "**What it is.** A generalized NFA is an NFA whose transition arrows are labeled with arbitrary REGULAR EXPRESSIONS rather than single symbols, so one arrow can consume a whole block of input matching its label (Def 1.64). In Sipser's special form it has a single start state (no incoming arrows) and a single accept state (no outgoing), with \\(k\\ge2\\) states.\n\n**Ripping out a state.** To delete \\(q_{\\mathrm{rip}}\\), repair each remaining pair \\((q_i,q_j)\\): with \\(R_1=\\delta(q_i,q_{\\mathrm{rip}})\\), \\(R_2=\\delta(q_{\\mathrm{rip}},q_{\\mathrm{rip}})\\), \\(R_3=\\delta(q_{\\mathrm{rip}},q_j)\\), \\(R_4=\\delta(q_i,q_j)\\), the new label is \\((R_1)(R_2)^*(R_3)\\cup(R_4)\\). This captures paths that go through \\(q_{\\mathrm{rip}}\\) any number of times, or bypass it (the \\(R_4\\) term).\n\n**Pitfall.** The \\((R_2)^*\\) self-loop term is easy to drop; without it you miss paths that loop at \\(q_{\\mathrm{rip}}\\). Keep ripping until exactly \\(k=2\\) states remain.\n\n**Result.** At \\(k=2\\), the lone arrow from start to accept is labeled with the equivalent regular expression (Lemma 1.60)."
  },
  "1::Pumping lemma": {
    title: "The pumping lemma for regular languages",
    body: "**Statement.** If \\(A\\) is regular, there is a pumping length \\(p\\) such that every \\(s\\in A\\) with \\(|s|\\ge p\\) can be split \\(s=xyz\\) with (1) \\(xy^iz\\in A\\) for all \\(i\\ge0\\), (2) \\(|y|>0\\), and (3) \\(|xy|\\le p\\) (Thm 1.70). Condition 1 includes \\(i=0\\), i.e. \"pumping down\" to \\(xz\\).\n\n**Why it holds.** Take \\(p\\) = number of states of a DFA for \\(A\\). A string of length \\(\\ge p\\) visits \\(\\ge p+1\\) states, so by the pigeonhole principle some state repeats; the loop between repetitions is the pumpable \\(y\\), and being within the first \\(p\\) symbols gives condition 3.\n\n**How to use it (a game).** Assume \\(A\\) regular to get \\(p\\); YOU pick a hard \\(s\\in A\\) with \\(|s|\\ge p\\); the adversary picks any split obeying (2)–(3); you exhibit some \\(i\\) (often \\(i=0\\) or \\(i=2\\)) with \\(xy^iz\\notin A\\), a contradiction. Condition 3 is what forces \\(y\\) into a chosen region (e.g. all \\(0\\)s of \\(0^p1^p\\)).\n\n**Pitfall.** It is one-directional: it can prove nonregularity but NEVER regularity, since some nonregular languages also pump (Problem 1.54)."
  },
  "1::Regular vs nonregular": {
    title: "Telling regular from nonregular",
    body: "**The dividing line.** Finite automata have only finite memory, so a language needing an UNBOUNDED count or comparison is typically nonregular. Standard nonregular examples: \\(\\{0^n1^n\\mid n\\ge0\\}\\), \\(\\{ww\\mid w\\in\\{0,1\\}^*\\}\\), and \\(\\{w\\mid \\#0=\\#1\\}\\) (Ex 1.73–1.76). Every FINITE language, by contrast, is regular — spell out each string as a regex and take their union.\n\n**Two tools for nonregularity.** Either pump directly with the pumping lemma, or use closure: if \\(A\\) were regular then so would \\(A\\cap R\\) for regular \\(R\\); deriving a known-nonregular intersection is a contradiction. E.g. \\(\\{w\\mid \\#0=\\#1\\}\\cap0^*1^*=\\{0^n1^n\\}\\) forces \\(\\{w\\mid \\#0=\\#1\\}\\) nonregular (Ex 1.74).\n\n**Pitfall.** Surface similarity misleads: \\(\\{w\\mid \\#0=\\#1\\}\\) is nonregular, yet \\(\\{w\\mid \\#01=\\#10\\}\\) (equal counts of the SUBSTRINGS \\(01\\) and \\(10\\)) IS regular. Intuition must be backed by a proof.\n\n**Example.** \"Has at least one \\(1\\)\" is regular (\\(\\Sigma^*1\\Sigma^*\\)); \"as many \\(0\\)s as \\(1\\)s\" is not."
  }
});
