/* Chapter 2 — Context-Free Languages (Sipser 2.1–2.4). Deeper concept explainers.
   Keyed "2::<topic>" to match the question topics in js/questions/ch2.js. */
TOC.addConcepts({
  "2::CFG formal definition": {
    title: "CFG formal definition",
    body: "**The 4-tuple.** A context-free grammar is \\(G=(V,\\Sigma,R,S)\\): a finite set \\(V\\) of variables (nonterminals), a finite set \\(\\Sigma\\) of terminals disjoint from \\(V\\), a finite set \\(R\\) of rules, and a start variable \\(S\\in V\\). Each rule has the form \\(A\\to w\\) where \\(A\\) is a single variable and \\(w\\in(V\\cup\\Sigma)^*\\) is any string of variables and terminals — including \\(\\varepsilon\\). The name \"context-free\" refers to exactly this: the left side is one variable, so \\(A\\) may be replaced wherever it appears regardless of surrounding context.\n\n**The generated language.** Writing \\(uAv\\Rightarrow uwv\\) for one rule application and \\(\\stackrel{*}{\\Rightarrow}\\) for zero or more steps, the language is \\(L(G)=\\{w\\in\\Sigma^*\\mid S\\stackrel{*}{\\Rightarrow}w\\}\\). The crucial restriction is \\(w\\in\\Sigma^*\\): the derivation must end with terminals only, so a sentential form still containing a variable is not yet a member. A language is a context-free language (CFL) precisely when some CFG generates it (Def 2.2).\n\n**Pitfall and example.** Do not conflate variables with terminals or read the start variable as just \"the first rule\"; \\(S\\) is a designated symbol. For instance \\(S\\to 0S1\\mid\\varepsilon\\) has \\(V=\\{S\\}\\), \\(\\Sigma=\\{0,1\\}\\), and generates \\(\\{0^n1^n\\mid n\\ge 0\\}\\)."
  },
  "2::Derivations & parse trees": {
    title: "Derivations and parse trees",
    body: "**Derivation.** A derivation records how \\(S\\) rewrites to a terminal string by repeated rule applications, each step \\(uAv\\Rightarrow uwv\\) replacing one variable \\(A\\) using a rule \\(A\\to w\\). A **leftmost derivation** always expands the leftmost remaining variable; fixing this discipline removes the inessential freedom of which variable to rewrite first.\n\n**Parse tree.** A parse tree displays a derivation as a tree: the root is \\(S\\), each internal node is a variable whose children spell out the right-hand side of the rule used, and the leaves read left to right give the **yield**, a string of terminals. One parse tree corresponds to many derivations that differ only in the order variables are expanded, which is exactly why ambiguity is defined via distinct parse trees (equivalently distinct leftmost derivations) rather than merely \"two derivations.\"\n\n**Pitfall and example.** Finding two derivations does not by itself prove ambiguity — they may yield the same tree. In \\(S\\to 0S1\\mid\\varepsilon\\), the string \\(0011\\) has the single parse tree \\(S\\Rightarrow 0S1\\Rightarrow 00S11\\Rightarrow 0011\\), so this grammar is unambiguous."
  },
  "2::Designing CFGs": {
    title: "Designing CFGs",
    body: "**Core techniques.** Three recurring tricks cover most grammars. Recursion that adds matching symbols on both ends captures linked counts, as in \\(S\\to 0S1\\mid\\varepsilon\\) for \\(\\{0^n1^n\\}\\). For a **union** of CFLs with start variables \\(S_1,S_2\\), combine both rule sets and add a fresh \\(S\\to S_1\\mid S_2\\); for **concatenation** use \\(S\\to S_1S_2\\) instead.\n\n**Linking to regular languages.** Any regular language is context-free, and the conversion is mechanical: from a DFA build one variable \\(R_i\\) per state \\(q_i\\), add \\(R_i\\to aR_j\\) whenever \\(\\delta(q_i,a)=q_j\\), add \\(R_i\\to\\varepsilon\\) for each accept state, and take \\(R_0\\) (the start state) as the start variable. These right-linear rules simulate the automaton reading input one symbol at a time.\n\n**Pitfall and example.** Break the target language into pieces and handle each with its own variable rather than forcing one overloaded rule. To get \\(\\{0^n1^n\\}\\cup\\{1^n0^n\\}\\), write \\(S\\to S_1\\mid S_2\\), \\(S_1\\to 0S_11\\mid\\varepsilon\\), \\(S_2\\to 1S_20\\mid\\varepsilon\\); note \\(S\\to S_1S_2\\) would instead build the concatenation."
  },
  "2::Regular vs context-free": {
    title: "Regular vs context-free",
    body: "**Proper containment.** Every regular language is context-free, so regular \\(\\subsetneq\\) context-free (Cor 2.32). One way to see the inclusion: a finite automaton is just a PDA that never touches its stack. Another is the explicit DFA-to-CFG construction giving a right-linear grammar. The inclusion is strict because \\(\\{0^n1^n\\mid n\\ge 0\\}\\) is context-free yet provably not regular by the regular pumping lemma.\n\n**Why the stack is the difference.** A finite automaton has only finitely many states, so it can compare quantities only up to a fixed bound; a PDA adds an unbounded stack, letting it remember an arbitrarily large count (push the \\(0\\)s, then pop one per \\(1\\)). That extra memory is precisely what separates the two classes.\n\n**Pitfall.** The containment goes one way only: context-free does NOT imply regular, and the two classes are not equal. A language being context-free tells you nothing about whether it is regular without a separate argument."
  },
  "2::Ambiguity": {
    title: "Ambiguity",
    body: "**Definition.** A grammar derives a string \\(w\\) ambiguously if \\(w\\) has two or more distinct leftmost derivations, equivalently two distinct parse trees; the grammar is **ambiguous** if it derives some string ambiguously (Def 2.7). Having several rules with the same left-hand side, or containing an \\(\\varepsilon\\)-rule, is perfectly normal and is not what ambiguity means.\n\n**Inherent ambiguity.** Ambiguity is a property of a grammar, not directly of a language: an ambiguous grammar may have an equivalent unambiguous one (Sipser's expression grammars \\(G_5\\) and \\(G_4\\) generate the same language, one ambiguous and one not). A language is **inherently ambiguous** when EVERY grammar generating it is ambiguous, so no unambiguous grammar exists at all.\n\n**Pitfall and example.** Do not infer from one ambiguous grammar that the language is inherently ambiguous; you must rule out all grammars. The classic inherently ambiguous language is \\(\\{a^ib^jc^k\\mid i=j\\text{ or }j=k\\}\\), where strings with \\(i=j=k\\) force two parse-tree shapes."
  },
  "2::Chomsky normal form": {
    title: "Chomsky normal form",
    body: "**The normal form.** A grammar is in Chomsky normal form (CNF) when every rule is \\(A\\to BC\\) (two variables, and neither \\(B\\) nor \\(C\\) is the start variable) or \\(A\\to a\\) (a single terminal), with the sole exception \\(S\\to\\varepsilon\\) allowed for the start variable (Def 2.8). Every CFL has a CNF grammar (Thm 2.9), which is what makes uniform algorithms like CYK parsing and the pumping-lemma argument possible.\n\n**The conversion order.** Sipser's procedure runs in a fixed order: (1) add a new start variable \\(S_0\\to S\\) so the start never appears on a right-hand side; (2) eliminate \\(\\varepsilon\\)-rules \\(A\\to\\varepsilon\\) for non-start \\(A\\), patching every rule that used \\(A\\); (3) eliminate **unit rules** \\(A\\to B\\), where for each \\(B\\to u\\) you add \\(A\\to u\\); (4) shorten long right-hand sides with new variables and replace stray terminals in long rules by dedicated variables.\n\n**Pitfall and example.** \\(A\\to aB\\) is right-linear form, not CNF — CNF forbids mixing a terminal with a variable on the right. The order matters: removing \\(\\varepsilon\\)-rules before unit rules avoids reintroducing the very rules a later step deletes."
  },
  "2::Pushdown automata": {
    title: "Pushdown automata",
    body: "**The 6-tuple.** A pushdown automaton is \\((Q,\\Sigma,\\Gamma,\\delta,q_0,F)\\): states \\(Q\\), input alphabet \\(\\Sigma\\), a separate **stack alphabet** \\(\\Gamma\\), transition function \\(\\delta\\), start state \\(q_0\\), and accept states \\(F\\subseteq Q\\). A PDA is an NFA equipped with an unbounded last-in-first-out stack, and that extra memory is what lifts it beyond the regular languages.\n\n**The transition function.** Nondeterminism and \\(\\varepsilon\\)-moves are built in: \\(\\delta:Q\\times\\Sigma_\\varepsilon\\times\\Gamma_\\varepsilon\\to\\mathcal{P}(Q\\times\\Gamma_\\varepsilon)\\), where \\(\\Sigma_\\varepsilon=\\Sigma\\cup\\{\\varepsilon\\}\\) and \\(\\Gamma_\\varepsilon=\\Gamma\\cup\\{\\varepsilon\\}\\). So from a (state, input-or-\\(\\varepsilon\\), pop-or-\\(\\varepsilon\\)) triple the machine moves to a SET of (state, push-or-\\(\\varepsilon\\)) pairs; it may move without reading input and without popping. Crucially, nondeterministic PDAs are strictly more powerful than deterministic ones — unlike NFAs versus DFAs — so e.g. \\(\\{ww^{\\mathcal{R}}\\}\\) requires nondeterminism.\n\n**Pitfall and example.** The model has no built-in empty-stack test, so by convention you first push a bottom marker \\(\\$\\) and treat seeing it again as \"empty.\" To recognize \\(\\{0^n1^n\\}\\): push \\(\\$\\), push a symbol per \\(0\\), pop one per \\(1\\), and accept on reaching \\(\\$\\) with the input exhausted."
  },
  "2::CFG/PDA equivalence": {
    title: "CFG / PDA equivalence",
    body: "**The theorem.** A language is context-free if and only if some pushdown automaton recognizes it (Thm 2.20). The two directions are Lemma 2.21 (every CFG converts to an equivalent PDA) and Lemma 2.27 (every PDA converts to an equivalent CFG), so grammars and stack machines describe exactly the same class.\n\n**CFG to PDA.** The PDA simulates a leftmost derivation on its stack. It pushes \\(\\$\\) and the start variable \\(S\\); then repeatedly, if the top is a variable \\(A\\) it nondeterministically replaces it by the right-hand side of some rule \\(A\\to w\\), if the top is a terminal it pops and matches it against the next input symbol (killing that branch on a mismatch), and if the top is \\(\\$\\) it accepts when all input is consumed. The nondeterminism is exactly the guess of which rule to apply.\n\n**PDA to CFG.** Here the grammar has a variable \\(A_{pq}\\) for each ordered pair of states, designed so that \\(A_{pq}\\stackrel{*}{\\Rightarrow}x\\) iff \\(x\\) drives the PDA from \\(p\\) with empty stack to \\(q\\) with empty stack; the start variable is \\(A_{q_0,q_{\\text{accept}}}\\). A standard pitfall is forgetting the normalization (single accept state, every move a single push or pop, stack empties only at start and end) that this construction assumes."
  },
  "2::Pumping lemma (CFL)": {
    title: "Pumping lemma for CFLs",
    body: "**Statement.** If \\(A\\) is context-free there is a pumping length \\(p\\) so that every \\(s\\in A\\) with \\(|s|\\ge p\\) splits as \\(s=uvxyz\\) satisfying three conditions: \\(uv^ixy^iz\\in A\\) for all \\(i\\ge 0\\); \\(|vy|>0\\) (the two pumped pieces are not both empty); and \\(|vxy|\\le p\\) (Thm 2.34). Note the FIVE-part split, the two pieces \\(v,y\\) that get pumped in tandem, and that there is no condition forcing them into the first \\(p\\) symbols — only the window \\(vxy\\) is bounded.\n\n**Why it holds.** In a CNF grammar a string of length \\(\\ge p\\) has a parse tree so tall that some root-to-leaf path repeats a variable \\(R\\), by the pigeonhole principle. The lower \\(R\\)-subtree sits inside the upper one; copying or deleting the section between the two \\(R\\)s pumps \\(v\\) and \\(y\\) together, and the bounded subtree height gives \\(|vxy|\\le p\\).\n\n**Pitfall and example.** The lemma only proves a language is NOT context-free, by contradiction; pumpability proves nothing positive. Use \\(|vxy|\\le p\\) to confine \\(vxy\\) to few blocks: for \\(\\{a^nb^nc^n\\}\\) take \\(s=a^pb^pc^p\\), where \\(vxy\\) touches at most two of the three blocks so pumping unbalances the counts. Some languages, like \\(\\{a^ib^jc^k\\mid 0\\le i\\le j\\le k\\}\\), need \"pumping down\" to \\(i=0\\) (\\(uxz\\)) rather than up."
  },
  "2::Closure properties": {
    title: "Closure properties",
    body: "**What CFLs are closed under.** The context-free languages are closed under union, concatenation, and star, each by an easy grammar construction: \\(S\\to S_1\\mid S_2\\) for union, \\(S\\to S_1S_2\\) for concatenation, and \\(S\\to S_1S\\mid\\varepsilon\\) for star. They are also closed under intersection with a regular language, since running a PDA and a DFA in parallel (a product on the finite control) is still a PDA.\n\n**The asymmetry.** CFLs are NOT closed under intersection: \\(\\{a^nb^nc^m\\}\\) and \\(\\{a^mb^nc^n\\}\\) are both context-free, but their intersection is \\(\\{a^nb^nc^n\\}\\), which is not. By De Morgan, \\(A\\cap B=\\overline{\\overline{A}\\cup\\overline{B}}\\); since CFLs are closed under union but not intersection, they CANNOT be closed under complement either, or intersection would follow.\n\n**Pitfall and example.** Do not assume the regular-language closure menu carries over — intersection and complement are the exceptions. But intersection with a regular language is fine, which is often the easiest tool: to show \\(\\{a^nb^nc^n\\}\\) is not context-free, observe that intersecting a hypothetical CFL for it with the regular \\(a^*b^*c^*\\) would have to stay context-free."
  },
  "2::Deterministic CFLs": {
    title: "Deterministic CFLs",
    body: "**Definition.** A deterministic PDA (DPDA) has at most one legal move from every configuration: for each \\(q\\in Q\\), \\(a\\in\\Sigma\\), \\(x\\in\\Gamma\\), exactly one of \\(\\delta(q,a,x),\\delta(q,a,\\varepsilon),\\delta(q,\\varepsilon,x),\\delta(q,\\varepsilon,\\varepsilon)\\) is nonempty (Def 2.39). A deterministic context-free language (DCFL) is one recognized by some DPDA. Note that \\(\\varepsilon\\)-moves are still permitted, unlike in a DFA.\n\n**Where DCFLs sit.** Every DPDA is a PDA, so DCFL \\(\\subseteq\\) CFL, but the inclusion is strict: \\(\\{ww^{\\mathcal{R}}\\}\\) and \\(\\{a^ib^jc^k\\mid i=j\\text{ or }i=k\\}\\) are context-free yet need nondeterminism, so DCFL \\(\\subsetneq\\) CFL. Unlike general CFLs, DCFLs ARE closed under complement (Thm 2.42), via a careful swap of accepting and non-accepting reading states of a normalized DPDA.\n\n**Pitfall and example.** Endmarkers do not change DPDA power — \\(A\\) is a DCFL iff \\(A\\dashv\\) is (Thm 2.43) — yet they often simplify design by signaling end of input, and the endmarker IS needed for the DPDA-to-DCFG equivalence. A clean DCFL is \\(\\{0^n1^n\\}\\): the machine deterministically pushes on \\(0\\)s and pops on \\(1\\)s with no guessing."
  }
});
