/* Chapter 3 — deeper concept explainers. Keyed "3::<topic>" to match question topics. */
TOC.addConcepts({
  "3::TM formal definition": {
    title: "TM formal definition (the 7-tuple)",
    body: "**What it is.** A Turing machine is the 7-tuple \\((Q,\\Sigma,\\Gamma,\\delta,q_0,q_{accept},q_{reject})\\): a finite set of states \\(Q\\), an input alphabet \\(\\Sigma\\), a tape alphabet \\(\\Gamma\\), a transition function \\(\\delta\\), a start state \\(q_0\\), and two halting states. The machine works on a single two-way-infinite tape with a read/write head, reading the input written at the left end of an otherwise blank tape.\n\n**Alphabet constraints.** Always \\(\\Sigma\\subseteq\\Gamma\\), the blank symbol \\(\\sqcup\\in\\Gamma\\), and \\(\\sqcup\\notin\\Sigma\\). So \\(\\Gamma\\) is strictly larger than \\(\\Sigma\\) (it has at least the blank), giving the machine scratch symbols to write that can never appear in a raw input.\n\n**Pitfall.** Unlike a finite automaton there is no *set* of final states \\(F\\); acceptance is decided by the two single states \\(q_{accept}\\) and \\(q_{reject}\\), and we require \\(q_{accept}\\neq q_{reject}\\). The instant either is entered the machine halts — it does not finish reading the input first, which is how a TM can accept or reject after touching only a few cells.\n\n**Why it matters.** This one definition (Def 3.3) is the formal stand-in for the intuitive idea of an algorithm. Everything later — decidability, reductions, complexity — is phrased in terms of machines built from this tuple."
  },
  "3::Transition function": {
    title: "Transition function \\(\\delta\\)",
    body: "**Form.** For a deterministic one-tape TM, \\(\\delta:Q\\times\\Gamma\\to Q\\times\\Gamma\\times\\{L,R\\}\\). Reading symbol \\(a\\) in state \\(q\\), the value \\(\\delta(q,a)=(r,b,L)\\) says: switch to state \\(r\\), write \\(b\\) over \\(a\\), then move the head left. Each step does all three things at once — change state, overwrite the current cell, and step one cell.\n\n**Reads/writes over \\(\\Gamma\\), not \\(\\Sigma\\).** The head can both sense and write any tape symbol, including the blank and any scratch symbols, which is what lets a TM mark cells and store intermediate data.\n\n**Direction set.** The basic move set is \\(\\{L,R\\}\\): there is no stay-put option in Def 3.3. A stay move \\(S\\) can be faked (move \\(R\\) then \\(L\\)) and adds no power, so the two-direction model loses nothing.\n\n**Pitfall.** For a deterministic machine \\(\\delta\\) is a *total* function on \\(Q\\times\\Gamma\\) — exactly one move per (state, symbol) pair. Don't confuse this with a PDA's \\(\\Sigma_\\varepsilon\\)-based transitions or a nondeterministic machine's power-set codomain."
  },
  "3::Tape & input alphabets": {
    title: "Tape and input alphabets",
    body: "**Two alphabets.** \\(\\Sigma\\) is what inputs are written in; \\(\\Gamma\\) is what may appear on the tape during a computation. The definition forces \\(\\Sigma\\subseteq\\Gamma\\), \\(\\sqcup\\in\\Gamma\\), and \\(\\sqcup\\notin\\Sigma\\), so \\(\\Gamma\\) always contains at least one symbol (the blank) that no input can contain.\n\n**Why the blank is excluded from \\(\\Sigma\\).** Because the tape beyond the input starts blank, the machine can detect where its input ends: the first \\(\\sqcup\\) marks the right boundary of \\(w\\). If the blank were a legal input symbol, the machine could not tell input from empty tape.\n\n**Finiteness.** Both \\(\\Sigma\\) and \\(\\Gamma\\) are finite sets; what is unbounded is the *tape*, not the alphabet. A larger \\(\\Gamma\\) (more scratch symbols) never increases the class of recognizable languages — it is only a convenience.\n\n**Tiny example.** With \\(\\Sigma=\\{0,1\\}\\) a typical tape alphabet is \\(\\Gamma=\\{0,1,x,\\sqcup\\}\\), where \\(x\\) is a marker the algorithm uses to cross off symbols it has already matched."
  },
  "3::Configurations": {
    title: "Configurations and the yields relation",
    body: "**What it captures.** A configuration is an instantaneous snapshot holding exactly three things: the current state, the current tape contents, and the head's position. Sipser writes it compactly as \\(u\\,q\\,v\\), meaning the machine is in state \\(q\\), the tape reads \\(uv\\) (then blanks), and the head sits on the first symbol of \\(v\\).\n\n**Yielding.** One configuration *yields* the next by a single application of \\(\\delta\\). For a rightward move \\(\\delta(q_i,b)=(q_j,c,R)\\), the snapshot \\(ua\\,q_i\\,bv\\) yields \\(uac\\,q_j\\,v\\): write \\(c\\), enter \\(q_j\\), step right onto the next cell. A left move at the very left end is special — the head stays put rather than falling off the tape.\n\n**Special configurations.** The *start* configuration on input \\(w\\) is \\(q_0\\,w\\) (start state, head on the leftmost cell). An *accepting* configuration has state \\(q_{accept}\\) and a *rejecting* one has \\(q_{reject}\\); these are the *halting* configurations, where no further yields occur.\n\n**Acceptance.** \\(M\\) accepts \\(w\\) iff there is a finite sequence \\(C_1,\\dots,C_k\\) with \\(C_1\\) the start configuration, each \\(C_i\\) yielding \\(C_{i+1}\\), and \\(C_k\\) accepting. This makes the phrase runs and accepts a precise, checkable statement."
  },
  "3::Acceptance & looping": {
    title: "Acceptance, rejection, and looping",
    body: "**Three outcomes.** Started on an input, a TM does exactly one of three things: halt in \\(q_{accept}\\), halt in \\(q_{reject}\\), or *loop* (run forever without halting). There is no fourth unknown verdict; failing to accept means it either rejects or loops.\n\n**Looping is the crucial wrinkle.** Not every TM halts on every input — this is what makes Turing machines strictly more subtle than finite automata or PDAs, which always finish. A machine that *does* halt on every input is special and is called a **decider**.\n\n**Language of a machine.** \\(L(M)\\) is the set of strings \\(M\\) accepts — the language *recognized* by \\(M\\). A string not in \\(L(M)\\) is either rejected or loops forever; from the outside these two failures look the same (no acceptance ever comes).\n\n**Pitfall.** Does not accept is not the same as rejects. Because a run may loop, you can never conclude rejection merely from the machine not having accepted yet — there is in general no time bound after which silence means no."
  },
  "3::Recognizable vs decidable": {
    title: "Turing-recognizable vs Turing-decidable",
    body: "**Recognizable.** \\(A\\) is Turing-recognizable iff some TM \\(M\\) has \\(L(M)=A\\): \\(M\\) accepts every string in \\(A\\) and accepts no string outside \\(A\\). On non-members \\(M\\) is allowed to reject *or to loop* — a recognizer need not halt on strings that are not in the language (Def 3.5). Older texts call this class *recursively enumerable*.\n\n**Decidable.** \\(A\\) is Turing-decidable iff some *decider* recognizes it — a TM that halts on **every** input and accepts exactly \\(A\\) (Def 3.6). The one extra demand over recognizability is total halting: a decider always gives a definite accept/reject answer. Older texts call this class *recursive*.\n\n**The inclusion.** Every decider is in particular a recognizer, so decidable \\(\\Rightarrow\\) recognizable. The converse fails: Chapter 4 exhibits \\(A_{TM}\\), which is recognizable but not decidable, so the two classes are genuinely different.\n\n**Pitfall.** The entire gap between the classes is the word halts. When you must show *decidability*, you have to argue the machine always stops — accepting on members is not enough if it might loop on non-members."
  },
  "3::Describing TMs": {
    title: "Three levels of describing a TM",
    body: "**Why levels exist.** Spelling out a TM's full transition table is unbearable for real algorithms, so Sipser permits describing machines at higher levels of abstraction, trusting that the lower levels could be filled in.\n\n**The three levels.** A *formal* description gives the states and \\(\\delta\\) in full detail. An *implementation* description uses prose but still talks about head movements and how the tape is used to store data. A *high-level* description states the algorithm in plain English, ignoring the tape and head entirely — this is the level most proofs use.\n\n**Convention.** From Chapter 3 on, machines are typically written as high-level numbered algorithms (\"On input \\(w\\): 1. ... 2. ...\"), relying on the Church–Turing thesis to know such an algorithm can be turned into a real TM.\n\n**Pitfall.** A high-level step like check whether the graph is connected is legitimate only because that subtask is itself clearly TM-computable. Don't hide an *uncomputable* step inside English prose — abstraction must not smuggle in power the model doesn't have."
  },
  "3::Encoding objects": {
    title: "Encoding objects as strings",
    body: "**The notation.** \\(\\langle O\\rangle\\) denotes a string that *encodes* the object \\(O\\), and \\(\\langle O_1,\\dots,O_k\\rangle\\) encodes several objects bundled into one string. So \\(\\langle M,w\\rangle\\) is a single string encoding both a machine \\(M\\) and an input \\(w\\) together.\n\n**Why it is needed.** A Turing machine's input is always a string, but the objects we reason about — graphs, automata, polynomials, even other Turing machines — are not strings. Encoding lets a TM take any such object as input by first writing it down in some fixed, decodable format.\n\n**Encoding is flexible but harmless.** The exact format (which delimiters, which order) does not matter, because any reasonable encoding can be converted to any other by a TM. Decidability results therefore don't depend on the encoding chosen.\n\n**Pitfall.** \\(\\langle M,w\\rangle\\) is *data* — a static description of \\(M\\) — not \\(M\\) actually running on \\(w\\). This distinction is what makes a *universal* TM (and the diagonal argument of Chapter 4) possible: a machine can read another machine's code as ordinary input."
  },
  "3::TM variants": {
    title: "TM variants and robustness",
    body: "**The robustness theme.** Many natural extensions of the basic TM recognize exactly the same class of languages, so the model is *robust*: tweaking the hardware does not change what is computable. This stability is the empirical backbone of the Church–Turing thesis.\n\n**Multitape.** A \\(k\\)-tape TM has \\(\\delta:Q\\times\\Gamma^k\\to Q\\times\\Gamma^k\\times\\{L,R,S\\}^k\\). Every multitape machine has an equivalent single-tape one (Thm 3.13): store the \\(k\\) tapes on one tape separated by \\(\\#\\), mark each virtual head with a dotted symbol, and shift contents right when a virtual head runs into a \\(\\#\\).\n\n**Nondeterministic.** An NTM has \\(\\delta:Q\\times\\Gamma\\to\\mathcal{P}(Q\\times\\Gamma\\times\\{L,R\\})\\), so a computation is a *tree* of branches; the NTM accepts if *some* branch reaches \\(q_{accept}\\). A deterministic machine simulates it by breadth-first search of that tree (Thm 3.16) — depth-first could dive down one infinite branch forever and miss an accepting configuration elsewhere.\n\n**Pitfall.** Equivalent in *power* is not equivalent in *speed*: these simulations can blow up the running time (e.g. exponentially for the NTM), which is exactly why nondeterminism still matters in complexity theory even though it adds no computability. Two stacks also suffice — a 2-PDA can simulate a tape and so matches a TM (Problem 3.9)."
  },
  "3::Enumerators": {
    title: "Enumerators",
    body: "**What it is.** An enumerator is a Turing machine fitted with a printer. It ignores any input (it starts on a blank work tape) and simply prints a stream of strings; the language it *enumerates* is the set of all strings it ever prints.\n\n**Equivalence with recognizers.** A language is Turing-recognizable iff some enumerator enumerates it (Thm 3.21). Given an enumerator \\(E\\) for \\(A\\), recognize \\(A\\) by running \\(E\\) and accepting \\(w\\) the moment \\(E\\) prints it. Conversely, given a recognizer \\(M\\), enumerate \\(A\\) by *dovetailing* — run \\(M\\) for \\(i\\) steps on the first \\(i\\) strings, for \\(i=1,2,3,\\dots\\), printing each string whose run has accepted.\n\n**No order, repeats allowed.** An enumerator may print in any order and may print the same string many times. Printing in standard string order *without* repetition is a strictly stronger property — it characterizes the *decidable* languages (Exercise 3.18).\n\n**Pitfall.** The dovetailing is essential: you cannot just run \\(M\\) to completion on string 1 before string 2, because \\(M\\) might loop on string 1 and you would never reach the rest. The old name *recursively enumerable* for recognizable languages comes from exactly this enumerator characterization."
  },
  "3::Church–Turing thesis": {
    title: "The Church–Turing thesis",
    body: "**The claim.** The Church–Turing thesis says the intuitive, informal notion of an algorithm (an effective, mechanical procedure) coincides exactly with what a Turing machine can compute. Church's \\(\\lambda\\)-calculus and Turing's machines were shown to define the same functions, and every other reasonable model proposed since matches them too.\n\n**Thesis, not theorem.** It is *not* something one proves, because one side — algorithm — is an informal idea with no prior mathematical definition. The thesis is the bridge that lets us treat there is an algorithm for \\(X\\) and there is a Turing machine deciding \\(X\\) as the same statement.\n\n**Why we believe it.** The robustness results — multitape, nondeterministic, enumerators, two-stack PDAs, plus unrelated formalisms like \\(\\lambda\\)-calculus and the general recursive functions, all yielding the identical class — are the accumulated evidence.\n\n**Why it matters.** It licenses high-level (English) descriptions of algorithms in proofs: once you describe a clearly mechanical procedure, the thesis guarantees a TM implementing it exists, so you needn't write the transition function."
  },
  "3::Hilbert's 10th / algorithms": {
    title: "Hilbert's tenth problem and the notion of algorithm",
    body: "**The problem.** Hilbert's tenth problem (1900) asked for an algorithm that, given a polynomial with integer coefficients, decides whether it has an *integral* root. Phrased in our terms it asks whether \\(D=\\{\\,p\\mid p \\text{ has an integral root}\\,\\}\\) is decidable.\n\n**The answer: no algorithm exists.** Matijasevic (1970), building on Davis, Putnam, and Robinson, proved \\(D\\) is *undecidable* — Hilbert's hoped-for procedure cannot exist. Settling this required first *defining* the word algorithm precisely (via Turing machines), since you cannot prove no algorithm exists until you have pinned down what an algorithm is.\n\n**But it is recognizable.** \\(D\\) is Turing-recognizable: a machine can run through all integer assignments \\(x_1,x_2,\\dots\\) and accept if some assignment makes \\(p\\) evaluate to \\(0\\). If a root exists it is eventually found; if none exists the search runs forever — which is precisely why \\(D\\) is recognizable yet not decidable.\n\n**Pitfall.** The single-variable case *is* decidable (roots of \\(p(x)\\) lie in a bounded range one can check); undecidability is a feature of the general *multivariable* problem. Recognizable-but-not-decidable is the key takeaway, foreshadowing \\(A_{TM}\\) in Chapter 4."
  },
  "3::Closure (decidable)": {
    title: "Closure properties of decidable languages",
    body: "**Closed under the Boolean and regular operations.** If \\(L_1\\) and \\(L_2\\) are decidable, so are \\(L_1\\cup L_2\\), \\(L_1\\cap L_2\\), \\(\\overline{L_1}\\), the concatenation \\(L_1 L_2\\), and the star \\(L_1^{*}\\). The deciders are built by combining the given deciders, and because each given machine always halts, the combination halts too (Exercise 3.15).\n\n**Complement is easy here.** Run \\(L_1\\)'s decider and *swap* its accept and reject outcomes. This works precisely because a decider always halts — there is no loop to get stuck in — so the swap yields a genuine decider for \\(\\overline{L_1}\\).\n\n**Union/intersection.** On input \\(w\\), run both deciders to completion (each halts), then accept for union if *either* accepted, for intersection if *both* did. Halting is guaranteed because both sub-deciders halt.\n\n**Pitfall.** Decidable languages are *not* closed under taking arbitrary subsets — most subsets of \\(\\Sigma^*\\) are not even recognizable, let alone decidable, since there are uncountably many languages but only countably many Turing machines."
  },
  "3::Closure (recognizable)": {
    title: "Closure properties of recognizable languages",
    body: "**Closed under union, intersection, concatenation, star.** If \\(L_1,L_2\\) are Turing-recognizable, so are \\(L_1\\cup L_2\\), \\(L_1\\cap L_2\\), \\(L_1 L_2\\), and \\(L_1^{*}\\) (Exercise 3.16). Intersection is the simple case: run both recognizers and accept only if both accept.\n\n**Union needs interleaving.** Given recognizers \\(M_1,M_2\\), build \\(M'\\) that simulates them *alternately, step by step*, accepting as soon as either accepts. Running \\(M_1\\) fully first is wrong: if \\(w\\notin L_1\\), \\(M_1\\) might loop forever and \\(M'\\) would never get to try \\(M_2\\), which could have accepted.\n\n**NOT closed under complement.** This is the headline difference from decidable languages. In fact a language is *decidable* iff both it and its complement are recognizable (Chapter 4), so a recognizable-but-undecidable language must have a *non-recognizable* complement.\n\n**Pitfall.** The \\(M'\\) built for the union recognizes but need not *decide* \\(L_1\\cup L_2\\) — it may still loop (when \\(w\\) is in neither language and both \\(M_i\\) loop). Closure for recognizers preserves recognizability, not the stronger property of halting."
  }
});
