/* Chapter 4 — Decidability (Sipser 4.1–4.2). Deeper concept explainers.
   Keyed "4::<topic>" to match question topics exactly. */
TOC.addConcepts({
  "4::Deciders vs recognizers": {
    title: "Deciders vs. recognizers",
    body: "**The distinction.** A Turing machine has three fates on an input: accept, reject, or loop (run forever). A **decider** never loops — it halts on every input, so it always answers accept or reject. A **recognizer** may loop, but only on strings it should reject; it must still accept exactly the strings of its language.\n\n**Decidable vs. recognizable.** \\(A\\) is *decidable* (Turing-decidable) if some decider has \\(L(M)=A\\); it is *Turing-recognizable* (recursively enumerable) if some recognizer has \\(L(M)=A\\). Every decidable language is recognizable, but not conversely — the gap is exactly languages like \\(A_{TM}\\) (Thm 4.11) that are recognizable yet have no decider.\n\n**The trap.** \"Recognizes\" does not mean \"halts on every input.\" A recognizer that says nothing (loops) on \\(w\\) has *not* rejected \\(w\\); it simply never decides. Deciding requires a definite halt-and-reject for every non-member.\n\n**Tiny example.** A TM for \\(A_{TM}\\) that simulates \\(M\\) on \\(w\\) accepts when \\(M\\) accepts but loops when \\(M\\) loops — a recognizer, not a decider."
  },
  "4::Decidable: regular languages": {
    title: "Decidable problems about regular languages",
    body: "**The big picture.** Every standard decision problem about finite automata is decidable, because the objects are finite and simulations terminate. The acceptance problems \\(A_{DFA}\\) (Thm 4.1), \\(A_{NFA}\\) (Thm 4.2), and \\(A_{REX}\\) (Thm 4.3) are decidable; so are emptiness \\(E_{DFA}\\) (Thm 4.4), equivalence \\(EQ_{DFA}\\) (Thm 4.5), and totality \\(ALL_{DFA}\\) (Exercise 4.3).\n\n**Why simulation halts.** A DFA reads each input symbol exactly once, so simulating \\(B\\) on \\(w\\) halts after \\(|w|\\) steps — that makes the \\(A_{DFA}\\) decider a genuine decider. NFAs and regular expressions are handled by first converting to a DFA (subset construction, Thm 1.39; \\(R\\to\\) NFA, Thm 1.54) and reusing the \\(A_{DFA}\\) decider.\n\n**Two clever reductions.** \\(E_{DFA}\\): a DFA accepts something iff an accept state is *reachable* from the start state, so a finite marking/graph-search decides emptiness. \\(EQ_{DFA}\\): build the symmetric difference \\(\\big(L(A)\\cap\\overline{L(B)}\\big)\\cup\\big(\\overline{L(A)}\\cap L(B)\\big)\\) as a DFA \\(C\\) (regular languages are closed under \\(\\cap,\\cup,\\) complement) and test \\(L(C)=\\emptyset\\); it is empty exactly when \\(L(A)=L(B)\\).\n\n**The trap.** These results are about the *encodings* \\(\\langle B\\rangle\\), not about running the machine on every string in \\(\\Sigma^*\\) (which would never halt). Note the contrast coming later: \\(EQ_{DFA}\\) is decidable, but \\(EQ_{CFG}\\) is not."
  },
  "4::Decidable: context-free languages": {
    title: "Decidable problems about context-free languages",
    body: "**The membership decider.** \\(A_{CFG}=\\{\\langle G,w\\rangle\\mid G\\text{ generates }w\\}\\) is decidable (Thm 4.7). Naively searching all derivations only *recognizes* it (the search can loop when \\(w\\notin L(G)\\)). The fix is to convert \\(G\\) to Chomsky normal form: then every derivation of a length-\\(n\\) string (\\(n\\ge 1\\)) takes exactly \\(2n-1\\) steps, so only finitely many derivations need checking.\n\n**Emptiness.** \\(E_{CFG}=\\{\\langle G\\rangle\\mid L(G)=\\emptyset\\}\\) is decidable (Thm 4.8) by a bottom-up marking: mark every terminal, then repeatedly mark any variable having a rule whose right-hand side is fully marked; \\(L(G)=\\emptyset\\) iff the start variable is never marked. This terminates because there are finitely many variables.\n\n**Every CFL is decidable (Thm 4.9).** Given a CFG \\(G\\) for a context-free language \\(A\\), the decider runs the \\(A_{CFG}\\) decider on \\(\\langle G,w\\rangle\\). Converting the PDA to a TM directly fails because nondeterministic PDA branches can loop, so go through the grammar instead.\n\n**The trap.** \\(EQ_{CFG}=\\{\\langle G,H\\rangle\\mid L(G)=L(H)\\}\\) is **undecidable** — the symmetric-difference trick fails because CFLs are *not* closed under intersection or complement. So \\(EQ_{DFA}\\) is decidable while \\(EQ_{CFG}\\) is not."
  },
  "4::Language hierarchy": {
    title: "The language-class hierarchy",
    body: "**The chain.** The four classes nest strictly: regular \\(\\subsetneq\\) context-free \\(\\subsetneq\\) decidable \\(\\subsetneq\\) Turing-recognizable. The middle link, context-free \\(\\subseteq\\) decidable, is exactly Theorem 4.9; the others come from earlier chapters and from \\(A_{TM}\\) (Thm 4.11).\n\n**Why each containment is proper.** \\(\\{0^n1^n\\}\\) is context-free but not regular; \\(\\{0^n1^n2^n\\}\\) is decidable but not context-free; and \\(A_{TM}\\) is Turing-recognizable but not decidable, so decidable \\(\\subsetneq\\) recognizable. Each gap is witnessed by a concrete language.\n\n**One more layer.** Beyond Turing-recognizable lie the non-recognizable languages, e.g. \\(\\overline{A_{TM}}\\) (Cor 4.23). A counting argument (Cor 4.18) guarantees such languages exist: countably many TMs cannot recognize uncountably many languages.\n\n**The trap.** \"Decidable\" sits strictly between context-free and recognizable; it is not a synonym for recognizable. Knowing a language is recognizable tells you nothing about whether it is decidable."
  },
  "4::Countability": {
    title: "Countability and correspondences",
    body: "**Same size via correspondence.** Two sets have the same size when a **correspondence** (a *bijection*: a function that is both one-to-one and onto, Def 4.12) pairs their elements. A set \\(A\\) is **countable** (Def 4.14) if it is finite or has the same size as \\(\\mathbb{N}\\) — equivalently, its elements can be listed \\(a_1,a_2,a_3,\\dots\\)\n\n**Surprising countables.** The positive rationals \\(\\mathbb{Q}\\) are countable (Ex 4.15): arrange fractions in a grid by numerator and denominator and sweep along diagonals, skipping repeats, so every fraction is reached in finitely many steps. Listing row-by-row would fail because each row is infinite.\n\n**Why it matters here.** \\(\\Sigma^*\\) is countable (finitely many strings of each length, listed by length then alphabetically), and therefore the set of all Turing machines is countable — each TM has a finite description \\(\\langle M\\rangle\\in\\Sigma^*\\). This is half of the existence argument for non-recognizable languages.\n\n**The trap.** Infinite does not mean uncountable. \\(\\mathbb{N},\\mathbb{Z},\\mathbb{Q},\\Sigma^*\\) are all infinite yet countable; \\(\\mathbb{R}\\) and the set of all languages are the ones that are not."
  },
  "4::Uncountability": {
    title: "Uncountability and diagonalization",
    body: "**The theorem.** \\(\\mathbb{R}\\) is uncountable (Thm 4.17). **Cantor's diagonalization:** suppose a list \\(f(1),f(2),f(3),\\dots\\) contained every real in \\((0,1)\\); build \\(x\\) whose \\(n\\)th decimal digit differs from the \\(n\\)th digit of \\(f(n)\\) (choosing digits to avoid \\(0\\) and \\(9\\), dodging representation ties). Then \\(x\\neq f(n)\\) for every \\(n\\), so \\(x\\) is missing — no list can be complete.\n\n**Lifting to languages.** The set of all languages over \\(\\Sigma\\) is uncountable. Each language \\(L\\) is encoded by its characteristic sequence: an infinite binary string whose \\(i\\)th bit is \\(1\\) iff the \\(i\\)th string of \\(\\Sigma^*\\) is in \\(L\\). The infinite binary sequences are uncountable (same diagonal argument), so the languages are too.\n\n**The punchline (Cor 4.18).** There are only **countably many** Turing machines but **uncountably many** languages. Since each TM recognizes at most one language, some languages are recognized by no TM — i.e. some languages are not Turing-recognizable. This is a non-constructive *existence* proof; it names no specific language.\n\n**The trap.** This counting argument proves a non-recognizable language *exists* but does not exhibit one. Producing a concrete witness, \\(\\overline{A_{TM}}\\), takes the separate argument in Cor 4.23."
  },
  "4::Undecidability of A_TM": {
    title: "Undecidability of \\(A_{TM}\\)",
    body: "**The result.** \\(A_{TM}=\\{\\langle M,w\\rangle\\mid M\\text{ is a TM and }M\\text{ accepts }w\\}\\) is undecidable (Thm 4.11), yet it *is* Turing-recognizable: the **universal Turing machine** \\(U\\) simulates \\(M\\) on \\(w\\) and accepts iff \\(M\\) accepts. \\(U\\) loops exactly when \\(M\\) loops on \\(w\\), so it recognizes but cannot decide \\(A_{TM}\\).\n\n**The diagonalization proof.** Assume a decider \\(H\\) with \\(H\\) accepting \\(\\langle M,w\\rangle\\) iff \\(M\\) accepts \\(w\\). Build \\(D\\) that, on input \\(\\langle M\\rangle\\), runs \\(H\\) on \\(\\langle M,\\langle M\\rangle\\rangle\\) and outputs the **opposite**: \\(D\\) accepts \\(\\langle M\\rangle\\) iff \\(M\\) does *not* accept \\(\\langle M\\rangle\\). Now run \\(D\\) on its own description.\n\n**The contradiction.** \\(D\\) accepts \\(\\langle D\\rangle\\) iff \\(D\\) does not accept \\(\\langle D\\rangle\\) — impossible. So no decider \\(H\\) exists, and \\(A_{TM}\\) is undecidable. The self-reference \\(\\langle M,\\langle M\\rangle\\rangle\\) is the diagonal of the machines-vs-inputs table.\n\n**The trap.** Undecidable is *not* the same as unrecognizable: \\(A_{TM}\\) is recognizable (via \\(U\\)) but not decidable. The unrecognizable language is its complement \\(\\overline{A_{TM}}\\) (Cor 4.23), not \\(A_{TM}\\) itself."
  },
  "4::Co-recognizability": {
    title: "Co-recognizability and \\(\\overline{A_{TM}}\\)",
    body: "**Definition.** A language is **co-Turing-recognizable** when its *complement* is Turing-recognizable. So \\(A\\) is co-recognizable iff \\(\\overline{A}\\) has a recognizer.\n\n**The key theorem (Thm 4.22).** \\(A\\) is decidable iff \\(A\\) is both Turing-recognizable *and* co-Turing-recognizable. Proof: given a recognizer \\(M_1\\) for \\(A\\) and \\(M_2\\) for \\(\\overline{A}\\), run them **in parallel** on \\(w\\); since every \\(w\\) lies in \\(A\\) or \\(\\overline{A}\\), exactly one accepts, so the combined machine always halts — a decider. (Running them sequentially could loop on the first and never reach the second.)\n\n**The non-recognizable witness (Cor 4.23).** \\(\\overline{A_{TM}}\\) is **not** Turing-recognizable. If it were, then \\(A_{TM}\\) would be both recognizable and co-recognizable, hence decidable by Thm 4.22 — contradicting Thm 4.11. So \\(A_{TM}\\) is recognizable but *not* co-recognizable, and \\(\\overline{A_{TM}}\\) is recognizable by no TM.\n\n**The trap.** Recognizable languages are **not** closed under complement. \\(A_{TM}\\) is recognizable but \\(\\overline{A_{TM}}\\) is not, which is exactly the asymmetry Thm 4.22 exposes."
  },
  "4::Classification": {
    title: "Classifying languages: decidable, recognizable, neither",
    body: "**Three boxes.** Sort each language into: decidable, Turing-recognizable-but-not-decidable, or not Turing-recognizable. Decidable: all the finite-automaton problems \\(A_{DFA},E_{DFA},EQ_{DFA},A_{NFA},A_{REX},ALL_{DFA}\\) and the CFG problems \\(A_{CFG},E_{CFG}\\), plus every regular and context-free language (Thm 4.9).\n\n**Recognizable but not decidable.** \\(A_{TM}\\) (Thm 4.11) and \\(HALT_{TM}\\) are recognizable via simulation but have no decider. By Thm 4.22, any recognizable-not-decidable language is *not* co-recognizable, so its complement is not recognizable.\n\n**Not recognizable.** \\(\\overline{A_{TM}}\\) is the canonical non-recognizable language (Cor 4.23). \\(EQ_{CFG}\\) is undecidable; its place in the recognizability hierarchy is settled in Chapter 5.\n\n**The classic traps.** (1) \\(EQ_{DFA}\\) is decidable but \\(EQ_{CFG}\\) is not. (2) \\(A_{TM}\\) is recognizable, but \\(\\overline{A_{TM}}\\) is not. (3) Every CFL is decidable, yet \\(A_{TM}\\) shows decidable \\(\\subsetneq\\) recognizable. When in doubt, ask: does the simulation/marking algorithm *always halt*? If yes, decidable; if it halts only on acceptances, merely recognizable."
  }
});
