/* Chapter 5 — Reducibility: deeper concept explainers. Keyed "5::<topic>" to match question topics. */
TOC.addConcepts({
  "5::Idea of reducibility": {
    title: "The idea of reducibility",
    body: "**The core move.** A reduction converts one problem into another so that a solution to the second yields a solution to the first. In Chapter 5 we use reductions to spread *undecidability*: to show a new problem \\(B\\) is undecidable, we reduce a problem already known to be undecidable (almost always \\(A_{TM}\\)) TO \\(B\\).\n\n**Direction is everything.** To prove \\(B\\) undecidable, show \\(A_{TM}\\le_m B\\) (or argue: a decider for \\(B\\) would let us decide \\(A_{TM}\\)). The reverse, \\(B\\le_m A_{TM}\\), proves nothing about \\(B\\) being hard — it only says \\(B\\) is no harder than \\(A_{TM}\\). Getting this backward is the single most common error in the chapter.\n\n**The proof template.** Assume for contradiction that \\(R\\) decides \\(B\\). From \\(\\langle M,w\\rangle\\) build a gadget object whose membership in \\(B\\) mirrors whether \\(M\\) accepts \\(w\\). Run \\(R\\) on it, read off the answer, and you have decided \\(A_{TM}\\) — impossible (Thm 4.11), so \\(R\\) cannot exist.\n\n**Tiny example.** \\(HALT_{TM}\\): if \\(R\\) decided halting, then given \\(\\langle M,w\\rangle\\) we ask \\(R\\) whether \\(M\\) halts on \\(w\\); if yes we simulate \\(M\\) safely and copy its answer, if no we reject. That decides \\(A_{TM}\\), so \\(R\\) cannot exist."
  },
  "5::Halting problem": {
    title: "The halting problem (HALT_TM)",
    body: "**What it is.** \\(HALT_{TM}=\\{\\langle M,w\\rangle\\mid M\\text{ is a TM that halts on }w\\}\\) — does \\(M\\) eventually stop (accept OR reject) on \\(w\\), rather than loop forever? It is the classic undecidable problem (Thm 5.1).\n\n**Why it is undecidable.** Reduce \\(A_{TM}\\) to it. Suppose \\(R\\) decides \\(HALT_{TM}\\). Build \\(S\\): on \\(\\langle M,w\\rangle\\), run \\(R\\); if \\(R\\) says \\(M\\) loops, reject; if \\(R\\) says \\(M\\) halts, simulate \\(M\\) on \\(w\\) (now safe — it will halt) and give \\(M\\)'s answer. Then \\(S\\) decides \\(A_{TM}\\), contradiction.\n\n**The trap.** The naive \"just simulate \\(M\\) on \\(w\\) and copy the answer\" fails as a decider precisely because if \\(M\\) loops on \\(w\\), the simulation never returns, so it never rejects. The \\(HALT_{TM}\\) oracle is exactly what removes that danger.\n\n**Recognizable, not decidable.** Like \\(A_{TM}\\), \\(HALT_{TM}\\) is Turing-recognizable (simulate and accept if it halts) but not decidable."
  },
  "5::Emptiness E_TM": {
    title: "Emptiness of a TM language (E_TM)",
    body: "**What it is.** \\(E_{TM}=\\{\\langle M\\rangle\\mid M\\text{ is a TM and }L(M)=\\emptyset\\}\\): does \\(M\\) accept no string at all? It is undecidable (Thm 5.2).\n\n**The reduction.** Reduce \\(A_{TM}\\) to \\(E_{TM}\\). From \\(\\langle M,w\\rangle\\) build \\(M_1\\) that immediately rejects any input \\(x\\neq w\\), and on input \\(w\\) runs \\(M\\) and accepts iff \\(M\\) accepts. The only string \\(M_1\\) could accept is \\(w\\), so \\(L(M_1)\\neq\\emptyset\\) exactly when \\(M\\) accepts \\(w\\).\n\n**Why it works.** A decider \\(R\\) for \\(E_{TM}\\) run on \\(\\langle M_1\\rangle\\) tells us whether \\(L(M_1)=\\emptyset\\); inverting that answer decides \\(A_{TM}\\). Note the inversion: \\(M\\) accepts \\(w\\) iff \\(\\langle M_1\\rangle\\notin E_{TM}\\).\n\n**Contrast.** \\(E_{CFG}\\) (emptiness for context-free grammars) IS decidable (Thm 4.8). Emptiness is decidable for CFGs but not for Turing machines — the power of the model is what tips it over."
  },
  "5::REGULAR_TM": {
    title: "Is a TM language regular? (REGULAR_TM)",
    body: "**What it is.** \\(REGULAR_{TM}=\\{\\langle M\\rangle\\mid L(M)\\text{ is a regular language}\\}\\): is the language recognized by \\(M\\) regular? Undecidable (Thm 5.3).\n\n**The reduction.** Reduce \\(A_{TM}\\) to it. From \\(\\langle M,w\\rangle\\) build \\(M_2\\) that on input \\(x\\): accepts immediately if \\(x\\) has the form \\(0^n1^n\\); otherwise runs \\(M\\) on \\(w\\) and accepts iff \\(M\\) accepts \\(w\\). The gadget is engineered so that \\(L(M_2)\\) toggles between a regular and a nonregular language.\n\n**The toggle.** If \\(M\\) accepts \\(w\\), the second clause fires for every \\(x\\), so \\(L(M_2)=\\Sigma^*\\) (regular). If \\(M\\) does not accept \\(w\\), then \\(M_2\\) accepts only the strings \\(0^n1^n\\), which is nonregular. Hence \\(L(M_2)\\) is regular iff \\(M\\) accepts \\(w\\).\n\n**The lesson.** The trick is to make \\(L(M_2)\\) flip between a property and its negation. This same scaffold proves many \\(\\{\\langle M\\rangle\\mid L(M)\\text{ has property }P\\}\\) undecidable — formalized by Rice's theorem."
  },
  "5::Equivalence EQ_TM": {
    title: "Equivalence of TMs (EQ_TM)",
    body: "**What it is.** \\(EQ_{TM}=\\{\\langle M_1,M_2\\rangle\\mid M_1,M_2\\text{ are TMs and }L(M_1)=L(M_2)\\}\\): do two machines accept exactly the same strings? Undecidable (Thm 5.4).\n\n**The reduction.** Reduce \\(E_{TM}\\) to \\(EQ_{TM}\\). Given \\(\\langle M\\rangle\\), output \\(\\langle M, M_1\\rangle\\) where \\(M_1\\) is a fixed machine that rejects everything, so \\(L(M_1)=\\emptyset\\). Then \\(L(M)=L(M_1)\\) iff \\(L(M)=\\emptyset\\), so \\(E_{TM}\\) is the special case of \\(EQ_{TM}\\) with one side pinned to the empty language.\n\n**Why this is legitimate.** \\(E_{TM}\\) is already known undecidable (Thm 5.2), and \\(E_{TM}\\le_m EQ_{TM}\\); by Cor 5.23, \\(EQ_{TM}\\) is undecidable. You may equivalently reduce straight from \\(A_{TM}\\).\n\n**Deeper fact.** \\(EQ_{TM}\\) is far worse than merely undecidable: it is neither Turing-recognizable nor co-Turing-recognizable (Thm 5.30)."
  },
  "5::Computation histories": {
    title: "Computation histories",
    body: "**Definition.** An *accepting computation history* for \\(M\\) on \\(w\\) is a finite sequence of configurations \\(C_1,C_2,\\dots,C_l\\) where \\(C_1\\) is the start configuration on \\(w\\), \\(C_l\\) is an accepting configuration, and each \\(C_{i+1}\\) legally follows \\(C_i\\) under \\(M\\)'s transition function (Def 5.5). A rejecting history ends in a rejecting configuration.\n\n**The key property.** Such a finite history exists iff \\(M\\) halts (accepts) on \\(w\\). If \\(M\\) loops, there is no finite accepting history. This turns the dynamic question \"does \\(M\\) accept \\(w\\)?\" into a static question \"does a valid history-string exist?\"\n\n**Why it matters.** Checking whether a string is a legal history is purely *local*: verify each adjacent pair \\(C_i, C_{i+1}\\) obeys \\(\\delta\\), and the endpoints are right. Weak models — an LBA, or even a PDA/CFG — can perform this local check, which is what powers the reductions for \\(E_{LBA}\\), \\(ALL_{CFG}\\), and \\(PCP\\).\n\n**Trap.** A history is finite and complete; it is not the set \\(L(M)\\) and not the transition table. Each \\(C_{i+1}\\) must *legally* follow \\(C_i\\) — a single illegal step invalidates the whole string."
  },
  "5::Linear bounded automata": {
    title: "Linear bounded automata (LBAs)",
    body: "**What it is.** An LBA is a Turing machine forbidden to move its head off the portion of tape holding the input (Def 5.6). The tape is therefore bounded by the input length \\(n\\), which sharply limits how much memory the machine has.\n\n**Finitely many configurations.** With \\(q\\) states, \\(g\\) tape symbols, and tape length \\(n\\), an LBA has exactly \\(q\\,n\\,g^{n}\\) distinct configurations (state, head position, tape contents) — a finite number (Lemma 5.8). This is the whole leverage.\n\n**\\(A_{LBA}\\) is DECIDABLE.** Simulate \\(M\\) on \\(w\\) for \\(q\\,n\\,g^{n}\\) steps; if it has not halted, it must have repeated a configuration and is looping, so reject (Thm 5.9). Because looping is detectable, \\(A_{LBA}\\) is decidable even though \\(A_{TM}\\) is not — the bounded tape is the difference.\n\n**\\(E_{LBA}\\) is UNDECIDABLE.** Sharp contrast: \\(E_{LBA}=\\{\\langle M\\rangle\\mid M\\text{ is an LBA and }L(M)=\\emptyset\\}\\) is undecidable (Thm 5.10). Reduce \\(A_{TM}\\) via computation histories: build an LBA \\(B\\) accepting exactly the accepting computation histories of \\(M\\) on \\(w\\), so \\(L(B)\\neq\\emptyset\\) iff \\(M\\) accepts \\(w\\). The trap: acceptance is decidable for LBAs, emptiness is not."
  },
  "5::CFG problems": {
    title: "CFG problems: ALL_CFG and EQ_CFG",
    body: "**The surprise.** Many CFG problems are decidable — \\(A_{CFG}\\), \\(E_{CFG}\\) (Thm 4.7, 4.8) — but \\(ALL_{CFG}=\\{\\langle G\\rangle\\mid L(G)=\\Sigma^*\\}\\) is UNDECIDABLE (Thm 5.13). \"Does this grammar generate every string?\" cannot be decided.\n\n**The reduction.** Reduce \\(A_{TM}\\): from \\(\\langle M,w\\rangle\\) build a CFG \\(G\\) (equivalently a PDA) generating every string that is NOT an accepting computation history of \\(M\\) on \\(w\\). Then \\(L(G)=\\Sigma^*\\) iff there is no accepting history iff \\(M\\) does not accept \\(w\\). Note this naturally produces the complement, which is why the construction targets non-histories.\n\n**The reversal trick.** A PDA's stack pops in reverse order, so to compare adjacent configurations \\(C_i, C_{i+1}\\) the construction writes every other configuration reversed; then a pushed \\(C_i\\) pops off in an order that lines up with \\(C_{i+1}\\) (Fig 5.14). This is why histories are written \\(C_1\\,C_2^{R}\\,C_3\\,C_4^{R}\\dots\\).\n\n**EQ_CFG follows.** \\(EQ_{CFG}=\\{\\langle G,H\\rangle\\mid L(G)=L(H)\\}\\) is undecidable too: fix \\(H\\) with \\(L(H)=\\Sigma^*\\); then \\(L(G)=L(H)\\) iff \\(L(G)=\\Sigma^*\\), reducing \\(ALL_{CFG}\\) to \\(EQ_{CFG}\\)."
  },
  "5::Post Correspondence Problem": {
    title: "The Post Correspondence Problem (PCP)",
    body: "**What it is.** A PCP instance is a finite collection of dominos \\(\\left[\\frac{t_i}{b_i}\\right]\\). A *match* is an ordering (repeats allowed) of dominos whose concatenated top string equals the concatenated bottom string. \\(PCP=\\{\\langle P\\rangle\\mid P\\text{ has a match}\\}\\) is undecidable (Thm 5.15).\n\n**The reduction.** Reduce \\(A_{TM}\\): from \\(\\langle M,w\\rangle\\) construct dominos so that any match is forced to spell out, top against bottom, the successive configurations of \\(M\\) running on \\(w\\). A match therefore exists iff \\(M\\) has an accepting computation history on \\(w\\), i.e. iff \\(M\\) accepts \\(w\\).\n\n**MPCP first.** Sipser proves \\(A_{TM}\\le_m MPCP\\) (modified PCP, where the match must START with the first domino), then \\(MPCP\\le_m PCP\\) using the \\(\\star\\)-interleaving trick to force the first domino. Composed, \\(A_{TM}\\le_m PCP\\).\n\n**Trap.** A match corresponds to an ACCEPTING history, so a match exists iff \\(M\\) accepts \\(w\\) (not rejects, not loops). Dominos may be reused and the alphabet is unrestricted."
  },
  "5::Computable functions": {
    title: "Computable functions",
    body: "**Definition.** A function \\(f:\\Sigma^*\\to\\Sigma^*\\) is *computable* if some Turing machine, started on any input \\(w\\), halts with exactly \\(f(w)\\) written on its tape (Def 5.17). The machine must halt on every input — \\(f\\) is total.\n\n**Examples.** Ordinary arithmetic on encoded numbers, and crucially *transformations of machine descriptions*: a TM can read \\(\\langle M,w\\rangle\\) and output \\(\\langle M'\\rangle\\) where \\(M'\\) is a modified machine. This program-rewriting ability is exactly what builds the gadget machines in reductions.\n\n**Role in reducibility.** Mapping reducibility \\(A\\le_m B\\) is defined through a computable function \\(f\\) (Def 5.20). The reduction is the function that converts \\(A\\)-instances into \\(B\\)-instances; \"computable\" guarantees the conversion is itself an effective, always-halting procedure.\n\n**Trap.** Computable is about the output transformation, not about deciding a language: do not confuse \"\\(f\\) is computable\" with \"the range of \\(f\\) is decidable.\" Also, a computable \\(f\\) need not be injective or surjective."
  },
  "5::Mapping reducibility": {
    title: "Mapping reducibility (≤_m)",
    body: "**Definition.** \\(A\\le_m B\\) (\\(A\\) is mapping reducible to \\(B\\)) if there is a computable function \\(f\\) such that for every string \\(w\\), \\(w\\in A\\iff f(w)\\in B\\) (Def 5.20). \\(f\\) is called the reduction from \\(A\\) to \\(B\\).\n\n**Both directions matter.** The biconditional bundles two requirements: if \\(w\\in A\\) then \\(f(w)\\in B\\), AND if \\(w\\notin A\\) then \\(f(w)\\notin B\\). The reduction must map members to members and non-members to non-members; a function that only gets the \"yes\" cases right is not a valid \\(\\le_m\\) reduction.\n\n**Many-one, not one-to-one.** \\(f\\) must be total and computable, but it need NOT be a bijection — many inputs may share one output. That is why \\(\\le_m\\) is also called *many-one* reducibility in other texts.\n\n**Why we care.** \\(\\le_m\\) is the precise tool behind the chapter's theorems: it transports decidability \"downward\" (Thm 5.22) and undecidability \"upward\" (Cor 5.23). Remember the slogan: \\(A\\le_m B\\) means \\(A\\) is *no harder than* \\(B\\)."
  },
  "5::Mapping reducibility theorems": {
    title: "Theorems about ≤_m (decidability)",
    body: "**The downward theorem.** If \\(A\\le_m B\\) and \\(B\\) is decidable, then \\(A\\) is decidable (Thm 5.22). To decide \\(A\\) on input \\(w\\): compute \\(f(w)\\), run the decider for \\(B\\) on it, and output its answer — correct because \\(w\\in A\\iff f(w)\\in B\\).\n\n**The contrapositive — our workhorse.** If \\(A\\le_m B\\) and \\(A\\) is *undecidable*, then \\(B\\) is undecidable (Cor 5.23). This is the engine of every undecidability proof in the chapter: exhibit \\(A_{TM}\\le_m B\\), and undecidability of \\(A_{TM}\\) forces undecidability of \\(B\\).\n\n**Direction check.** To prove \\(B\\) undecidable you need the KNOWN-hard problem on the LEFT: \\(A_{TM}\\le_m B\\). Writing \\(B\\le_m A_{TM}\\) is the classic mistake — it merely shows \\(B\\) is recognizable (since \\(A_{TM}\\) is), proving nothing about hardness.\n\n**Tiny example.** \\(A_{TM}\\le_m HALT_{TM}\\) via \\(f(\\langle M,w\\rangle)=\\langle M',w\\rangle\\) where \\(M'\\) loops instead of rejecting; then \\(M\\) accepts \\(w\\) iff \\(M'\\) halts on \\(w\\). Cor 5.23 then gives undecidability of \\(HALT_{TM}\\)."
  },
  "5::Recognizability via reductions": {
    title: "Recognizability via reductions",
    body: "**The recognizability analog.** If \\(A\\le_m B\\) and \\(B\\) is Turing-recognizable, then \\(A\\) is Turing-recognizable (Thm 5.28). Contrapositive: if \\(A\\) is NOT recognizable and \\(A\\le_m B\\), then \\(B\\) is not recognizable (Cor 5.29). Same \\(\\le_m\\) tool, now transporting recognizability.\n\n**Complement symmetry.** The same computable \\(f\\) that witnesses \\(A\\le_m B\\) also witnesses \\(\\overline{A}\\le_m\\overline{B}\\), since \\(w\\in A\\iff f(w)\\in B\\) is logically the same as \\(w\\in\\overline{A}\\iff f(w)\\in\\overline{B}\\). Hence \\(A\\le_m B \\Leftrightarrow \\overline{A}\\le_m\\overline{B}\\).\n\n**The standard recipe.** To prove \\(B\\) is NOT Turing-recognizable, show \\(\\overline{A_{TM}}\\le_m B\\), because \\(\\overline{A_{TM}}\\) is not recognizable (Cor 4.23). By the complement symmetry, \\(\\overline{A_{TM}}\\le_m B\\) is the same as \\(A_{TM}\\le_m\\overline{B}\\) — so often you build a reduction \\(A_{TM}\\le_m\\overline{B}\\) and conclude \\(B\\) is non-recognizable.\n\n**Trap.** Showing \\(A_{TM}\\le_m B\\) only proves \\(B\\) undecidable; \\(A_{TM}\\) IS recognizable, so that reduction says nothing about non-recognizability. For non-recognizability you must start from a non-recognizable source like \\(\\overline{A_{TM}}\\)."
  },
  "5::EQ_TM recognizability": {
    title: "EQ_TM: neither recognizable nor co-recognizable",
    body: "**The claim.** \\(EQ_{TM}\\) is neither Turing-recognizable nor co-Turing-recognizable (Thm 5.30). This is strictly worse than \\(A_{TM}\\), which is at least recognizable; \\(EQ_{TM}\\) sits outside both halves.\n\n**Not recognizable.** Show \\(\\overline{A_{TM}}\\le_m EQ_{TM}\\), i.e. \\(A_{TM}\\le_m\\overline{EQ_{TM}}\\). Map \\(\\langle M,w\\rangle\\) to \\(\\langle M_1,M_2\\rangle\\) where \\(M_1\\) rejects all inputs and \\(M_2\\) accepts all inputs iff \\(M\\) accepts \\(w\\); the two are equal exactly when \\(M\\) does NOT accept \\(w\\). Since \\(\\overline{A_{TM}}\\) is non-recognizable (Cor 4.23), so is \\(EQ_{TM}\\).\n\n**Not co-recognizable.** Show \\(\\overline{A_{TM}}\\le_m\\overline{EQ_{TM}}\\), i.e. \\(A_{TM}\\le_m EQ_{TM}\\), with a similar gadget making the machines equal iff \\(M\\) accepts \\(w\\). This makes \\(\\overline{EQ_{TM}}\\) non-recognizable, i.e. \\(EQ_{TM}\\) is not co-recognizable.\n\n**Why it matters.** A language is decidable iff it is both recognizable AND co-recognizable (Thm 4.22). \\(EQ_{TM}\\) failing both shows it is not just undecidable but maximally so among these examples."
  },
  "5::Rice's theorem": {
    title: "Rice's theorem",
    body: "**The statement.** Any *nontrivial* property of the language recognized by a Turing machine is undecidable (Sipser Problem 5.28). Formally, a property \\(P\\) is a set of TM descriptions such that (1) it depends only on the language — if \\(L(M_1)=L(M_2)\\) then \\(\\langle M_1\\rangle\\in P\\iff\\langle M_2\\rangle\\in P\\) — and (2) it is nontrivial — some TMs have it and some do not. Then \\(P\\) is undecidable.\n\n**Two conditions, both needed.** Language-dependence rules out properties of the machine's syntax; nontriviality rules out the always-true and always-false properties. Drop either and the theorem does not apply.\n\n**What it does NOT cover.** Trivial properties (held by all TMs, or by none) are decidable. Syntactic properties like \"\\(M\\) has at least 5 states\" or \"\\(M\\) has 3 tapes\" depend on the description, not on \\(L(M)\\), so Rice says nothing — and they are typically decidable.\n\n**Instant verdicts.** By Rice, these are undecidable in one line: \\(\\{\\langle M\\rangle\\mid L(M)=\\emptyset\\}\\), \\(\\{\\langle M\\rangle\\mid L(M)\\text{ is regular}\\}\\), \\(ALL_{TM}\\), \\(INFINITE_{TM}\\), and \\(\\{\\langle M\\rangle\\mid 1011\\in L(M)\\}\\) — each is a nontrivial property of \\(L(M)\\)."
  },
  "5::Decidability classification": {
    title: "Decidability classification (the big map)",
    body: "**Three buckets.** Every language here is *decidable*, *recognizable-but-undecidable*, or *not even recognizable*. Knowing which bucket each canonical language lands in is the heart of the chapter, and the distractors exploit near-misses (especially the LBA pair).\n\n**Decidable.** \\(A_{DFA}, A_{CFG}, E_{CFG}, EQ_{DFA}\\) (Chapter 4) and \\(A_{LBA}\\) (Thm 5.9) are decidable. The LBA's bounded tape makes looping detectable, so acceptance is decidable.\n\n**Recognizable but undecidable.** \\(A_{TM}\\) and \\(HALT_{TM}\\) (Thm 5.1): you can simulate and accept, but no decider exists. Also undecidable are \\(E_{TM}, REGULAR_{TM}, EQ_{TM}, E_{LBA}, ALL_{CFG}, EQ_{CFG}, PCP\\) (several of these, like \\(ALL_{CFG}\\) and \\(EQ_{TM}\\), are not even recognizable — check carefully).\n\n**Outside recognizable.** \\(\\overline{A_{TM}}\\) is not recognizable (Cor 4.23); \\(EQ_{TM}\\) is neither recognizable nor co-recognizable (Thm 5.30). **The classic trap:** \\(A_{LBA}\\) is DECIDABLE while \\(E_{LBA}\\) is UNDECIDABLE — same machine model, opposite verdicts, because emptiness quantifies over all inputs whereas acceptance fixes one."
  }
});
