/* Chapter 6 — deeper concept explainers. Keyed "6::<topic>" to match question topics. */
TOC.addConcepts({
  "6::Recursion theorem": {
    title: "The recursion theorem",
    body: "**What it says.** The recursion theorem (Thm 6.3) guarantees that a Turing machine can obtain its own description \\(\\langle M\\rangle\\) and then go on to compute with it. Formally, from any TM \\(T\\) computing \\(t(\\langle R\\rangle, w)\\) you can build a TM \\(R\\) with \\(r(w)=t(\\langle R\\rangle, w)\\): it behaves exactly as if its own code had been handed to it for free, in addition to the real input \\(w\\).\n\n**The engine: the \\(q\\) function.** Lemma 6.1 gives a computable \\(q\\) where \\(q(w)=\\langle P_w\\rangle\\), the description of a machine \\(P_w\\) that erases its input, prints \\(w\\), and halts. This 'hard-code a string into a printer' step lets a machine talk about pieces of itself as data.\n\n**Self-reference without circularity.** The self-printing machine \\(\\mathit{SELF}=AB\\) shows the trick: \\(A\\) prints \\(\\langle B\\rangle\\) onto the tape, then \\(B\\) reads that \\(\\langle B\\rangle\\), recomputes \\(\\langle A\\rangle=q(\\langle B\\rangle)\\), and assembles the full \\(\\langle AB\\rangle\\). Note \\(B\\) does not call \\(q(\\langle A\\rangle)\\) directly — that would be circular since \\(A\\) is defined from \\(B\\); instead \\(B\\) finds \\(\\langle B\\rangle\\) waiting on the tape.\n\n**The common trap.** Self-reference is not forbidden and does not require an oracle or a paradox. When you design a machine \\(M\\), the recursion theorem fully justifies writing 'obtain own description \\(\\langle M\\rangle\\)' as a legitimate instruction; having \\(\\langle M\\rangle\\), \\(M\\) may print it, count its states, or simulate itself. The same mechanism is what a self-replicating computer virus uses to copy its own code."
  },
  "6::Recursion theorem applications": {
    title: "Applications of the recursion theorem",
    body: "**The pattern.** Most applications build a machine that obtains its own description \\(\\langle M\\rangle\\), feeds it to an assumed decider, and then deliberately does the opposite of what the decider predicts — a direct contradiction that needs no diagonal table.\n\n**A new proof that \\(A_{TM}\\) is undecidable (Thm 6.5).** Suppose \\(H\\) decides \\(A_{TM}\\). Build \\(B\\) that obtains \\(\\langle B\\rangle\\), runs \\(H\\) on \\(\\langle B,w\\rangle\\), and then does the opposite of \\(H\\)'s answer. Then \\(B\\)'s real behavior contradicts \\(H\\)'s verdict about \\(B\\), so \\(H\\) cannot exist. This replaces Cantor's diagonalization from Thm 4.11 with one act of self-reference. The same template proves Rice's theorem (Problem 6.9): pick \\(A\\) inside a nontrivial property \\(P\\) and \\(B\\) outside it, and have \\(R\\) simulate whichever one makes \\(R\\)'s own membership in \\(P\\) inconsistent with the assumed decider \\(X\\).\n\n**\\(MIN_{TM}\\) is not Turing-recognizable (Thm 6.7).** Let \\(MIN_{TM}\\) be the descriptions of minimal TMs (no equivalent machine is shorter). If an enumerator \\(E\\) listed it, a machine \\(C\\) could obtain \\(\\langle C\\rangle\\), wait for \\(E\\) to output some \\(D\\) with \\(|\\langle D\\rangle|>|\\langle C\\rangle|\\) (possible since \\(MIN_{TM}\\) is infinite), and then simulate \\(D\\). Now \\(C\\equiv D\\) yet \\(C\\) is shorter, so \\(D\\) is not minimal — contradicting that \\(E\\) listed it.\n\n**The trap, and the fixed-point theorem (Thm 6.8).** Do not read 'fixed point' as 'unchanged string'. For any computable transformation \\(t\\) of descriptions there is a TM \\(F\\) with \\(t(\\langle F\\rangle)\\) describing a machine equivalent to \\(F\\) — equal in behavior, not necessarily as a string. \\(F\\) obtains \\(\\langle F\\rangle\\), computes \\(t(\\langle F\\rangle)=\\langle G\\rangle\\), and simulates \\(G\\)."
  },
  "6::Turing reducibility": {
    title: "Turing reducibility and oracles",
    body: "**Oracles.** An oracle for a language \\(B\\) is an external device that answers, for any string \\(w\\), whether \\(w\\in B\\) in a single step — with no concern for whether \\(B\\) is even decidable (Def 6.18). An oracle Turing machine \\(M^{B}\\) is an ordinary TM augmented with the power to pose such queries.\n\n**The reduction.** \\(A\\) is Turing reducible to \\(B\\), written \\(A\\le_T B\\), when some oracle TM \\(M^{B}\\) decides \\(A\\) — that is, \\(A\\) is decidable relative to \\(B\\) (Def 6.20). This is the most general notion of 'solving \\(A\\) using a subroutine for \\(B\\)'. For example \\(E_{TM}\\le_T A_{TM}\\): to test \\(L(M)\\neq\\emptyset\\), build \\(N\\) that runs \\(M\\) on all inputs and ask the oracle whether \\(\\langle N,0\\rangle\\in A_{TM}\\).\n\n**Relation to mapping reducibility — the trap.** \\(A\\le_m B\\) (a computable \\(f\\) with \\(w\\in A\\Leftrightarrow f(w)\\in B\\)) always implies \\(A\\le_T B\\), but not conversely. The classic witness: \\(\\overline{A_{TM}}\\le_T A_{TM}\\) by simply flipping the oracle's yes/no answer, yet \\(\\overline{A_{TM}}\\not\\le_m A_{TM}\\) — because a mapping reduction would make \\(\\overline{A_{TM}}\\) recognizable, which it is not. So Turing reducibility is strictly more permissive: it lets you negate answers and query many times."
  },
  "6::Descriptive complexity": {
    title: "Descriptive (Kolmogorov) complexity",
    body: "**Definition.** The descriptive (Kolmogorov) complexity \\(K(x)\\) of a binary string \\(x\\) is the length of its shortest description (Def 6.23). A description is a string \\(\\langle M,w\\rangle\\) such that \\(M\\) run on \\(w\\) halts with \\(x\\) on its tape; \\(d(x)\\) is the shortest such (lexicographically first if tied), and \\(K(x)=|d(x)|\\). Intuitively \\(K(x)\\) is the amount of information in \\(x\\): a highly patterned string is cheap to describe, a structureless one is not.\n\n**The upper bound.** For a universal constant \\(c\\) and every \\(x\\), \\(K(x)\\le|x|+c\\) (Thm 6.24): just describe \\(x\\) as \\(\\langle M\\rangle x\\) where \\(M\\) is the identity machine, with \\(c=|\\langle M\\rangle|\\). So no string costs more than a fixed constant beyond its own length.\n\n**Incompressible strings.** A string is incompressible when \\(K(x)\\ge|x|\\) — no description beats writing it out (Def 6.28). A counting argument shows they exist at every length \\(n\\): there are \\(2^n\\) strings of length \\(n\\) but only \\(2^n-1\\) candidate descriptions of length \\(<n\\), and each description yields at most one string, so some length-\\(n\\) string is left uncompressed (Thm 6.29). Incompressible strings behave like random ones (roughly balanced \\(0\\)s and \\(1\\)s).\n\n**The trap: none of this is computable.** \\(K\\) is not a computable function (Problem 6.23), so no algorithm prints \\(K(x)\\) from \\(x\\); and the set of incompressible strings is undecidable (Problem 6.24). If you could decide incompressibility you could effectively produce incompressible strings, which is impossible — a Berry-paradox-style obstruction. (Relatedly, those strings contain no infinite recognizable subset, Problem 6.25.)"
  }
});
