/* Chapter 7 — deeper concept explainers. Keyed "7::<topic>" to match question topics. */
TOC.addConcepts({
  "7::Big-O and small-o": {
    title: "Big-O and small-o",
    body: "**Big-O (asymptotic upper bound).** \\(f(n)=O(g(n))\\) means there are constants \\(c>0\\) and \\(n_0\\) with \\(f(n)\\le c\\,g(n)\\) for all \\(n\\ge n_0\\). You keep the highest-order term and drop constant factors: \\(5n^3+2n^2+22n+6=O(n^3)\\). It is a ceiling up to a constant, so \\(O(n^3)\\) is also \\(O(n^4)\\), just looser.\n\n**Small-o (strictly smaller).** \\(f(n)=o(g(n))\\) means \\(\\lim_{n\\to\\infty} f(n)/g(n)=0\\); \\(f\\) is dominated by \\(g\\). Big-O is to \\(\\le\\) as small-o is to \\(<\\): \\(f(n)=O(f(n))\\) always, but \\(f(n)=o(f(n))\\) is never true because the ratio is \\(1\\), not \\(0\\).\n\n**Polynomial vs exponential.** A bound \\(n^c\\) for constant \\(c\\) is polynomial; a bound \\(2^{(n^{\\delta})}\\) for \\(\\delta>0\\) is exponential. Sipser treats all polynomial differences as small (the \"reasonable\" regime) and exponential blow-ups as the real barrier.\n\n**Common trap.** Bigger growth means the OTHER function is the small-o one: \\(n^2=o(2^n)\\), not the reverse. And \\(O\\) describes worst-case running time as a function of input length \\(n\\), not of the input's numeric value."
  },
  "7::TIME(t(n))": {
    title: "The time complexity class TIME(t(n))",
    body: "**Definition.** \\(\\mathrm{TIME}(t(n))\\) is the collection of all languages decidable by some \\(O(t(n))\\)-time deterministic (single-tape) Turing machine (Def 7.7). \"Running time\" is the worst-case number of steps over all inputs of length \\(n\\).\n\n**The model matters.** Time is measured on a specific machine model, so the same language can sit in different \\(\\mathrm{TIME}\\) classes depending on tapes. The cross-off machine for \\(A=\\{0^k1^k\\mid k\\ge 0\\}\\) makes up to \\(n/2\\) scans of cost \\(O(n)\\) each, so it runs in \\(O(n^2)\\) and \\(A\\in\\mathrm{TIME}(n^2)\\); a two-tape machine can do it in \\(O(n)\\).\n\n**Why we abstract to P.** Because constant-factor and small-polynomial differences depend on the model, Sipser groups all polynomial bounds together into \\(\\mathrm{P}\\). The nondeterministic analog is \\(\\mathrm{NTIME}(t(n))\\).\n\n**Common trap.** \\(\\mathrm{TIME}(t(n))\\) requires a DECIDER (it halts on every input), and the \\(O(\\cdot)\\) means \"at most this,\" not \"exactly this.\""
  },
  "7::Model relationships": {
    title: "Complexity relationships among models",
    body: "**Multitape costs at most squaring.** Every \\(t(n)\\)-time multitape TM (with \\(t(n)\\ge n\\)) has an equivalent single-tape TM running in \\(O(t^2(n))\\) time (Thm 7.8). Simulating one multitape step scans the whole single tape in \\(O(t(n))\\), and there are \\(t(n)\\) steps, hence the square.\n\n**Nondeterminism costs at most exponentiation.** Every \\(t(n)\\)-time nondeterministic single-tape TM (with \\(t(n)\\ge n\\)) has an equivalent deterministic single-tape TM running in \\(2^{O(t(n))}\\) time (Thm 7.11). The deterministic machine searches the computation tree, which has up to \\(b^{t(n)}\\) branches.\n\n**The big picture.** Switching deterministic models is a polynomial change, which is why \\(\\mathrm{P}\\) is robust. Removing nondeterminism is (as far as we know) an exponential change, which is exactly the gap that makes \\(\\mathrm{P}\\) vs \\(\\mathrm{NP}\\) hard.\n\n**Common trap.** The multitape-to-single-tape slowdown is polynomial (squaring), not exponential; only the nondeterministic-to-deterministic conversion is known to risk an exponential blow-up."
  },
  "7::The class P": {
    title: "The class P",
    body: "**Definition.** \\(\\mathrm{P}=\\bigcup_k \\mathrm{TIME}(n^k)\\): the languages decidable in polynomial time on a deterministic single-tape TM (Def 7.12). \\(\\mathrm{P}\\) is taken to capture \"realistically solvable,\" and it is invariant across all reasonable deterministic models.\n\n**Reasonable encodings.** Inputs must be encoded sensibly: numbers in base \\(k\\ge 2\\), graphs as adjacency lists, etc. Unary is forbidden because writing \\(17\\) as seventeen \\(1\\)s is exponentially longer than its binary length, which would distort what \"polynomial in \\(n\\)\" means.\n\n**Canonical members.** \\(PATH\\) (is there a directed \\(s\\)-to-\\(t\\) path?) is in \\(\\mathrm{P}\\) via breadth-first marking of reachable nodes (Thm 7.14). \\(RELPRIME\\) is in \\(\\mathrm{P}\\) via the Euclidean algorithm (Thm 7.15), and every context-free language is in \\(\\mathrm{P}\\) (Thm 7.16).\n\n**Common trap.** A brute-force algorithm existing does not put a problem in \\(\\mathrm{P}\\); you need a polynomial-time one. Trying all \\(s\\)-to-\\(t\\) paths is exponential, so the marking algorithm, not brute force, is what shows \\(PATH\\in\\mathrm{P}\\)."
  },
  "7::The class NP": {
    title: "The class NP",
    body: "**Two equivalent definitions.** \\(\\mathrm{NP}\\) is the class of languages with a polynomial-time VERIFIER, equivalently those decided by a nondeterministic polynomial-time TM (Thm 7.20). The \"N\" is NONDETERMINISTIC polynomial time, NOT \"non-polynomial\"; indeed \\(\\mathrm{P}\\subseteq\\mathrm{NP}\\).\n\n**Verifiers and certificates.** A verifier \\(V\\) satisfies \\(A=\\{w\\mid V\\text{ accepts }\\langle w,c\\rangle\\text{ for some }c\\}\\) (Def 7.18). The extra string \\(c\\) is a certificate (witness): a short, easily checkable proof that \\(w\\in A\\). Poly-time in \\(|w|\\) forces useful certificates to have polynomial length.\n\n**Canonical members.** \\(CLIQUE\\) (does \\(G\\) have \\(k\\) pairwise-adjacent nodes?), \\(SUBSET\\text{-}SUM\\) (does some subcollection sum to \\(t\\)? e.g. \\(4+21=25\\)), and \\(HAMPATH\\) are all in \\(\\mathrm{NP}\\): the clique, the subset, or the path is the certificate, and the verifier just checks it.\n\n**Common trap.** Membership in \\(\\mathrm{NP}\\) only needs a YES-certificate. The complement \\(\\overline{HAMPATH}\\) is not obviously in \\(\\mathrm{NP}\\), because certifying that NO Hamiltonian path exists is not known to be easy."
  },
  "7::P versus NP": {
    title: "P versus NP",
    body: "**The question.** \\(\\mathrm{P}\\) is \"solvable quickly\"; \\(\\mathrm{NP}\\) is \"checkable quickly.\" Whether \\(\\mathrm{P}=\\mathrm{NP}\\) is OPEN, the central unsolved problem of the field; no one has produced a single language in \\(\\mathrm{NP}\\setminus\\mathrm{P}\\), nor proved one cannot exist.\n\n**What we do know.** \\(\\mathrm{P}\\subseteq\\mathrm{NP}\\) because any decider is a trivial verifier that ignores the certificate. And \\(\\mathrm{NP}\\subseteq\\mathrm{EXPTIME}=\\bigcup_k\\mathrm{TIME}(2^{n^k})\\), since a deterministic machine can brute-force all polynomially-long certificates. Whether either containment is proper is unknown.\n\n**Belief vs proof.** Most researchers believe \\(\\mathrm{P}\\neq\\mathrm{NP}\\) (finding seems harder than checking), but belief is not a theorem. A proof either way would be a landmark.\n\n**Common trap.** \\(\\mathrm{NP}\\) is not \"problems too hard for \\(\\mathrm{P}\\).\" Easy problems live in \\(\\mathrm{NP}\\) too. If \\(\\mathrm{P}=\\mathrm{NP}\\) then essentially every nontrivial language in \\(\\mathrm{P}\\), including \\(PATH\\), becomes NP-complete; so showing \\(PATH\\) is not NP-complete would prove \\(\\mathrm{P}\\neq\\mathrm{NP}\\)."
  },
  "7::Polynomial-time reducibility": {
    title: "Polynomial-time reducibility",
    body: "**Definition.** \\(A\\le_p B\\) means there is a polynomial-time computable function \\(f\\) with \\(w\\in A\\iff f(w)\\in B\\) for every \\(w\\) (Def 7.29). The map \\(f\\) translates instances of \\(A\\) into equivalent instances of \\(B\\), efficiently and preserving membership.\n\n**What it transfers.** If \\(A\\le_p B\\) and \\(B\\in\\mathrm{P}\\), then \\(A\\in\\mathrm{P}\\) (Thm 7.31): compute \\(f(w)\\) in poly time, then run \\(B\\)'s poly-time decider, and the composition of polynomials is polynomial. So \\(\\le_p\\) says \"\\(A\\) is no harder than \\(B\\).\"\n\n**Direction is everything.** \\(A\\le_p B\\) lets an algorithm for \\(B\\) solve \\(A\\), never the reverse. \\(A\\in\\mathrm{P}\\) tells you nothing about \\(B\\), since an easy \\(A\\) can reduce to a hard \\(B\\). To prove hardness you reduce FROM a known-hard problem TO your target.\n\n**Tiny example.** In \\(3SAT\\le_p CLIQUE\\), a \\(3cnf\\)-formula with \\(k\\) clauses maps to a graph with one node per literal; edges join non-contradictory literals in different clauses, so \\(\\phi\\) is satisfiable iff \\(G\\) has a \\(k\\)-clique (Thm 7.32)."
  },
  "7::NP-completeness": {
    title: "NP-completeness",
    body: "**Definition.** \\(B\\) is NP-complete if (1) \\(B\\in\\mathrm{NP}\\) and (2) every \\(A\\in\\mathrm{NP}\\) satisfies \\(A\\le_p B\\) (Def 7.34). These are the hardest problems in \\(\\mathrm{NP}\\): everything in \\(\\mathrm{NP}\\) reduces INTO \\(B\\).\n\n**Why they are pivotal.** If any single NP-complete \\(B\\) is in \\(\\mathrm{P}\\), then \\(\\mathrm{P}=\\mathrm{NP}\\) (Thm 7.35): every \\(A\\in\\mathrm{NP}\\) has \\(A\\le_p B\\), so by Thm 7.31 every \\(A\\in\\mathrm{P}\\). A polynomial algorithm for one of them collapses the whole class.\n\n**How to prove a new problem is NP-complete.** To show \\(C\\) is NP-complete: first show \\(C\\in\\mathrm{NP}\\); then pick a KNOWN NP-complete \\(B\\) (often \\(3SAT\\)) and give a poly-time reduction \\(B\\le_p C\\), proving \\(w\\in B\\iff f(w)\\in C\\) (Thm 7.36).\n\n**Common trap.** The reduction direction is \\(B\\le_p C\\) (from known-hard \\(B\\) to new \\(C\\)), NOT \\(C\\le_p B\\). Reducing your problem to a hard one shows it is easy, the opposite of what you want."
  },
  "7::Cook–Levin theorem": {
    title: "The Cook–Levin theorem",
    body: "**Statement.** \\(SAT=\\{\\langle\\varphi\\rangle\\mid \\varphi\\text{ is a satisfiable Boolean formula}\\}\\) is NP-complete (Thm 7.37, Cook–Levin). It is the first NP-complete problem and the seed from which all others are grown by reduction. A formula is satisfiable when some \\(0/1\\) assignment makes it evaluate to \\(1\\).\n\n**Idea of the proof.** For any \\(A\\in\\mathrm{NP}\\) decided by an NTM \\(N\\) in time \\(n^k\\), the reduction builds a formula \\(\\varphi=\\varphi_{cell}\\wedge\\varphi_{start}\\wedge\\varphi_{move}\\wedge\\varphi_{accept}\\) describing an \\(n^k\\times n^k\\) tableau of \\(N\\)'s configurations. \\(\\varphi_{start}\\) fixes the first row, \\(\\varphi_{move}\\) forces every \\(2\\times 3\\) window to be legal, and \\(\\varphi_{accept}\\) demands an accepting state appear, so \\(\\varphi\\) is satisfiable iff \\(N\\) accepts \\(w\\).\n\n**Consequences.** The formula has size \\(O(n^{2k})\\), so the reduction is polynomial. \\(SAT\\in\\mathrm{P}\\iff\\mathrm{P}=\\mathrm{NP}\\) (Thm 7.27), and converting \\(\\varphi\\) to \\(3cnf\\) form shows \\(3SAT\\) is NP-complete too (Cor 7.42).\n\n**Common trap.** The tableau is polynomial-sized, so the reduction runs in polynomial time, not exponential; the \"hard\" part is solving \\(SAT\\), not building \\(\\varphi\\)."
  },
  "7::Additional NP-complete problems": {
    title: "Additional NP-complete problems",
    body: "**The reduction chain.** From Cook–Levin's \\(SAT\\), Sipser derives \\(3SAT\\) (Cor 7.42), then reduces \\(3SAT\\) to \\(CLIQUE\\) (Thm 7.32), \\(VERTEX\\text{-}COVER\\) (Thm 7.44), \\(HAMPATH\\) (Thm 7.46), \\(UHAMPATH\\), and \\(SUBSET\\text{-}SUM\\) (Thm 7.56). Each new proof reduces FROM an already-established NP-complete problem.\n\n**Knowing the definitions.** A vertex cover is a set of nodes such that every edge touches at least one chosen node (do not confuse it with a clique, which is a pairwise-adjacent set). \\(VERTEX\\text{-}COVER=\\{\\langle G,k\\rangle\\mid G\\text{ has a }k\\text{-node vertex cover}\\}\\), and the cover or path or subset is always the certificate.\n\n**A worked extension.** \\(3COLOR\\) (can \\(G\\) be colored with three colors so no edge joins two same-colored nodes?) is NP-complete (Problem 7.29); the coloring is a short certificate and gadgets reduce \\(3SAT\\) to it.\n\n**Common trap.** \\(PATH\\in\\mathrm{P}\\) and is believed NOT to be NP-complete, even though it looks superficially like \\(HAMPATH\\); the Hamiltonian constraint (visit every node exactly once) is what pushes \\(HAMPATH\\) into NP-completeness."
  }
});
