/* Chapter 8 — deeper concept explainers. Keyed "8::<topic>" to match question topics. */
TOC.addConcepts({
  "8::Space complexity": {
    title: "Space complexity",
    body: "**Definition.** For a deterministic TM \\(M\\) that halts on all inputs, the space complexity \\(f(n)\\) is the maximum number of tape cells \\(M\\) scans on any input of length \\(n\\) (for a nondeterministic machine, the max over all branches). It measures a high-water mark of memory, not time, and \\(\\mathrm{SPACE}(f)\\) / \\(\\mathrm{NSPACE}(f)\\) are the languages decidable within that bound.\n\n**Intuition: space is reusable.** Tape cells can be overwritten and reused, whereas a step of time is gone forever. This is why a single block of memory can be cycled through exponentially many possibilities, making space a far cheaper resource than time.\n\n**The key trap.** Do not equate space with time. \\(SAT\\in\\mathrm{SPACE}(n)\\) by trying each assignment in turn and reusing the same \\(O(n)\\) cells, even though \\(SAT\\) is \\(\\mathrm{NP}\\)-complete and not known to be in \\(\\mathrm{P}\\) (Sipser Ex 8.3). Small space does not imply small time.\n\n**Tiny example.** To decide \\(ALL_{NFA}=\\{\\langle A\\rangle\\mid L(A)=\\Sigma^*\\}\\), the complement is decided in \\(\\mathrm{NSPACE}(n)\\) by guessing a rejected string symbol-by-symbol while storing only the set of currently-active states (Ex 8.4)."
  },
  "8::Savitch's theorem": {
    title: "Savitch's theorem",
    body: "**Statement.** For any \\(f(n)\\ge\\log n\\), \\(\\mathrm{NSPACE}(f(n))\\subseteq\\mathrm{SPACE}(f^2(n))\\) (Thm 8.5). Removing nondeterminism costs at most a SQUARING of space, not the exponential blowup one might fear.\n\n**Why squaring, not linear.** The deterministic simulator asks whether the start configuration can reach the accept configuration, via a recursive procedure \\(\\mathrm{CANYIELD}(c_1,c_2,t)\\) that splits on a midpoint \\(c_m\\): does \\(c_1\\) reach \\(c_m\\) in \\(t/2\\) steps and \\(c_m\\) reach \\(c_2\\) in \\(t/2\\) steps. Recursion depth is \\(\\log t = O(f(n))\\) and each stack frame stores a configuration of size \\(O(f(n))\\), giving \\(O(f^2(n))\\) total because the same space is reused across the two halves.\n\n**The trap.** It is a squaring, not a linear increase; claiming a linear cost would be a much stronger, unknown result. Also note \\(t\\) can be exponential (there are \\(2^{O(f)}\\) configurations), but storing \\(t\\) as a counter only takes \\(O(f)\\) space.\n\n**Consequence.** Taking \\(f(n)=\\log n\\) gives \\(\\mathrm{NL}\\subseteq\\mathrm{SPACE}(\\log^2 n)\\); taking \\(f\\) polynomial yields \\(\\mathrm{PSPACE}=\\mathrm{NPSPACE}\\)."
  },
  "8::PSPACE": {
    title: "PSPACE and NPSPACE",
    body: "**Definition.** \\(\\mathrm{PSPACE}=\\bigcup_k\\mathrm{SPACE}(n^k)\\) is the class of languages decidable in polynomial space on a deterministic TM; \\(\\mathrm{NPSPACE}\\) is the nondeterministic analogue.\n\n**PSPACE = NPSPACE is settled.** Savitch gives \\(\\mathrm{NSPACE}(n^k)\\subseteq\\mathrm{SPACE}(n^{2k})\\), and the square of a polynomial is still a polynomial, so \\(\\mathrm{PSPACE}=\\mathrm{NPSPACE}\\). This is a theorem, NOT an open problem; the common trap is to treat it like \\(\\mathrm{P}\\) vs \\(\\mathrm{NP}\\), which remains open.\n\n**Where it sits.** \\(\\mathrm{P}\\subseteq\\mathrm{NP}\\subseteq\\mathrm{PSPACE}\\), and because \\(\\mathrm{PSPACE}\\) is closed under complement also \\(\\mathrm{coNP}\\subseteq\\mathrm{PSPACE}\\). A space-\\(f(n)\\) machine has only \\(2^{O(f(n))}\\) distinct configurations, so it runs in time \\(2^{O(f(n))}\\), giving \\(\\mathrm{PSPACE}\\subseteq\\mathrm{EXPTIME}\\).\n\n**The chain.** \\(\\mathrm{P}\\subseteq\\mathrm{NP}\\subseteq\\mathrm{PSPACE}=\\mathrm{NPSPACE}\\subseteq\\mathrm{EXPTIME}\\). The time hierarchy theorem forces \\(\\mathrm{P}\\neq\\mathrm{EXPTIME}\\), so at least one containment is proper, though no one knows which."
  },
  "8::PSPACE-completeness": {
    title: "PSPACE-completeness",
    body: "**Definition.** \\(B\\) is \\(\\mathrm{PSPACE}\\)-complete if \\(B\\in\\mathrm{PSPACE}\\) and every \\(A\\in\\mathrm{PSPACE}\\) is polynomial-TIME reducible to \\(B\\) (Def 8.8). The reduction is poly-time, not poly-space: it must be weaker than the class itself, or a fast algorithm for \\(B\\) would not transfer to all of \\(\\mathrm{PSPACE}\\).\n\n**The canonical problem: TQBF.** \\(TQBF=\\{\\langle\\phi\\rangle\\mid\\phi\\text{ is a true fully quantified Boolean formula}\\}\\) is \\(\\mathrm{PSPACE}\\)-complete (Thm 8.9). It generalizes \\(SAT\\) by allowing \\(\\forall\\) and \\(\\exists\\) over \\(\\{0,1\\}\\), and is decided in polynomial space by recursively evaluating each quantifier.\n\n**Why the reduction works.** Unlike Cook–Levin, you cannot write out the whole tableau, because a poly-space machine may run for exponential time, making the tableau exponentially tall. Instead the reduction recursively halves the time interval and uses a single \\(\\forall\\) to share one subformula across both halves, keeping the formula \\(O(f^2(n))\\) in size, exactly Savitch's idea.\n\n**Games are PSPACE-complete too.** \\(FORMULA\\text{-}GAME\\) equals \\(TQBF\\) (player E wins iff the formula is true, Thm 8.11), and \\(GG\\) (generalized geography, alternately extending a simple path) is \\(\\mathrm{PSPACE}\\)-complete via \\(FORMULA\\text{-}GAME\\le_P GG\\) (Thm 8.14). Two-player games of polynomial length are the signature of \\(\\mathrm{PSPACE}\\)."
  },
  "8::L and NL": {
    title: "L and NL (logarithmic space)",
    body: "**The model.** To make sublinear space meaningful, the machine has a read-only input tape plus a separate read/write work tape, and ONLY work-tape cells count toward space. This lets the machine read all of the input without having room to copy it.\n\n**Definitions.** \\(\\mathrm{L}=\\mathrm{SPACE}(\\log n)\\) is deterministic log space and \\(\\mathrm{NL}=\\mathrm{NSPACE}(\\log n)\\) is nondeterministic log space (Def 8.17). Log space holds a constant number of pointers into the input, since an index into an \\(n\\)-cell input needs \\(O(\\log n)\\) bits.\n\n**Tiny example: counting, not crossing off.** \\(A=\\{0^k1^k\\}\\in\\mathrm{L}\\): the input is read-only, so instead of marking symbols the machine keeps two binary counters on the work tape and compares them, using only \\(O(\\log n)\\) space (Ex 8.18).\n\n**The NL trap.** \\(PATH\\) (directed \\(s\\)-\\(t\\) reachability) is in \\(\\mathrm{NL}\\) by storing only the current node and a step counter while guessing the next neighbor (Ex 8.19). Storing the whole guessed path would blow the log-space budget, so the certificate must be consumed one node at a time."
  },
  "8::NL-completeness": {
    title: "NL-completeness",
    body: "**Why a weaker reduction.** \\(\\mathrm{NL}\\)-completeness is defined with log-space reducibility \\(\\le_L\\), not poly-time \\(\\le_P\\). Because \\(\\mathrm{NL}\\subseteq\\mathrm{P}\\), nearly every \\(\\mathrm{NL}\\) problem is \\(\\le_P\\)-interreducible, so \\(\\le_P\\) is too coarse to distinguish them; the reduction must be weaker than the class.\n\n**Log-space transducer.** A log-space computable function is produced by a machine with a read-only input tape, an \\(O(\\log n)\\) work tape, and a write-only output tape whose head never moves left (Def 8.21), so the possibly-large output is not charged against the log-space bound. Crucially \\(\\le_L\\) composes: if \\(A\\le_L B\\) and \\(B\\in\\mathrm{L}\\) then \\(A\\in\\mathrm{L}\\) (Thm 8.23).\n\n**The canonical problem.** \\(PATH\\) is \\(\\mathrm{NL}\\)-complete (Thm 8.25): it is in \\(\\mathrm{NL}\\), and any \\(\\mathrm{NL}\\) language reduces to it by building the configuration graph of its log-space NTM, where an \\(s\\)-\\(t\\) path corresponds to an accepting computation.\n\n**Consequence.** \\(\\mathrm{NL}\\subseteq\\mathrm{P}\\) (Cor 8.26): a log-space machine has only polynomially many configurations, so its configuration graph is polynomial and reachability is solvable in \\(\\mathrm{P}\\). The trap is to think log space implies the problem is trivial; \\(\\mathrm{NL}\\)-complete problems are as hard as anything in \\(\\mathrm{NL}\\)."
  },
  "8::NL = coNL": {
    title: "NL = coNL (Immerman–Szelepcsényi)",
    body: "**The surprise.** Nondeterministic log space is closed under complement: \\(\\mathrm{NL}=\\mathrm{coNL}\\) (Thm 8.27). This was unexpected, since the analogous \\(\\mathrm{NP}\\) vs \\(\\mathrm{coNP}\\) question is famously open; verifying a YES is easy, but here one can also verify a NO in the same resource.\n\n**Proof strategy.** It suffices to show \\(\\overline{PATH}\\in\\mathrm{NL}\\). Since \\(PATH\\) is \\(\\mathrm{NL}\\)-complete, \\(\\overline{PATH}\\) is \\(\\mathrm{coNL}\\)-complete, so putting it in \\(\\mathrm{NL}\\) drags every \\(\\mathrm{coNL}\\) language into \\(\\mathrm{NL}\\); combined with \\(\\mathrm{NL}\\subseteq\\mathrm{coNL}\\) this forces equality.\n\n**The engine: inductive counting.** To certify that \\(t\\) is unreachable from \\(s\\), the algorithm computes \\(c\\), the EXACT number of nodes reachable from \\(s\\), by obtaining each \\(c_{i+1}\\) (nodes reachable in \\(\\le i+1\\) steps) from the previous count \\(c_i\\). Knowing \\(c\\), it nondeterministically exhibits exactly \\(c\\) reachable nodes, none equal to \\(t\\), all within log space.\n\n**The summary chain.** \\(\\mathrm{L}\\subseteq\\mathrm{NL}=\\mathrm{coNL}\\subseteq\\mathrm{P}\\subseteq\\mathrm{NP}\\subseteq\\mathrm{PSPACE}\\). Because \\(\\mathrm{NL}\\subsetneq\\mathrm{PSPACE}\\) (space hierarchy), at least one inclusion is proper, but which one is unknown."
  }
});
